### ISSUE TITLE
Core metrics

### ISSUE THREAD

**Issue by maelstraggiotti** [Riverside-Software/sonar-openedge#1]
Hi,

Thank you for the great work on this plugin. I ran a succesful analysis, showing some metrics but the Structure section in SonarQube is not correcly populated. I have a "Lines" metrics which seems correct but not used as a the standard component's size reporting.

Is there any reason that core metrics such as CoreMetrics.LINES are not reported (at least I didn't found any reference to it in the code) ?

![image](https://cloud.githubusercontent.com/assets/2782049/12954885/c890a164-d020-11e5-9c51-627c47bdfd35.png)

Thank you

**Comment by jakejustus** [comment]
This bug is already reported in our internal bug tracker, and will be taken care of.
Thanks for reporting the issue !

**Comment by maelstraggiotti** [comment]
Excellent !

Merci

**Comment by jakejustus** [comment]
Fixed in the latest release
