### ISSUE TITLE
ERROR: Error during SonarQube Scanner execution

### ISSUE THREAD

**Issue by mebrighton** [Riverside-Software/sonar-openedge#10]
I have the following running Sonar from the Jenkins plugin...

Not sure how to run with -X value?

INFO: Using schema : config/devopsys.df
INFO: ------------------------------------------------------------------------
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
INFO: Total time: 5.601s
INFO: Final Memory: 44M/439M
INFO: ------------------------------------------------------------------------
ERROR: Error during SonarQube Scanner execution
java.lang.IllegalStateException: Unable to load component class org.sonar.plugins.openedge.foundation.OpenEdgeSettings
............

Caused by: java.lang.IllegalArgumentException: No enum constant eu.rssw.antlr.database.objects.TriggerType.WRITE 
	at java.lang.Enum.valueOf(Enum.java:236)

**Comment by jakejustus** [comment]
Hi,

Do you use the latest release ? While this message should still appear (that will be included in the next version), it shouldn't stop the analysis. Could you confirm with this latest version ?

Thanks

**Comment by mebrighton** [comment]
Hi Gilles,
I think I’m using the latest release.
sonar-openedge-db-plugin-1.5.jar   &  sonar-openedge-plugin-1.7.jar
I was using a full path to the dump file  - this did not stop the analysis (but gave a proparse error instead and  the analysis showed that my db tables wer not recognised)

This new error occurs with a relative path to dump file. This stops the analysis.

Regards,
Michael.

**Comment by jakejustus** [comment]
Version 1.7.1 was released shortly after 1.7, please check with this version, and there was an internal dependency problem with the DF file parser.

**Comment by mebrighton** [comment]
Hi,
updated to 1.7.1 but still the same error
[analysis.txt](https://github.com/Riverside-Software/sonar-openedge/files/206520/analysis.txt)

**Comment by jakejustus** [comment]
New release available which will help find the issue ; you'd still have an error message, but that won't interrupt the analysis.

**Comment by mebrighton** [comment]
Thanks - the above issue is now resolved (no error message is displayed) and analysis completes.

a couple of things have come to light now the analysis has completed...

Proparse error: Error during generation of Proparse AST
and
JaCoCoSensor: JaCoCo report not found : C:\Jenkins\jobs\DevABLUnitTests\workspace\target\jacoco.exec

**Comment by jakejustus** [comment]
JaCoCo error message is worthless in this case, as it only applies to Java source code (but the Java plugin is automatically installed and executed). So you can ignore this message.

Regarding Proparse errors : I'd be interested in having more details ; the full stacktraces are only available with the -X option (an option will be available soon to generate a debug file). Please open new issues for those errors with the stack trace and if possible the lines generating an error. Or contact me privately if you don't want to share code details publicly.
