### ISSUE TITLE
WHOLE INDEX with BY

### ISSUE THREAD

**Issue by movedoa** [Riverside-Software/sonar-openedge#100]
The following code should not generate an error since it uses the intended index.
(Even though it is technically WHOLE INDEX, but this is intended and afaik there is no other or better way to do this)

![1](https://cloud.githubusercontent.com/assets/13309951/20262572/0f0c3dca-aa63-11e6-8ef6-f543a805aef5.PNG)

![2](https://cloud.githubusercontent.com/assets/13309951/20262630/516518fe-aa63-11e6-9121-3da65ca9acde.PNG)

**Comment by gquerret** [comment]
Information is not available from the XREF file, so the structure of the underlying analyzers have to be changed in order to have access to both XREF and AST at the same time.
There's some refactoring involved here, so I have to delay this issue a bit.

**Comment by gquerret** [comment]
And don't forget Mike's comment on issue #116

**Comment by KWSMaster** [comment]
This applies to FIND FIRST and FIND LAST as well.

**Comment by gquerret** [comment]
Refactoring has been done, so work on this rule could start in the next version

**Comment by gquerret** [comment]
All `FIND` / `FOR` statements (on both temp-tables and database tables) without a `WHERE` clause now don't report WholeIndex issues.
