### ISSUE TITLE
How is the df mapped to the database?

### ISSUE THREAD

**Issue by lievencardoen** [Riverside-Software/sonar-openedge#1010]
Hi, maybe a stupid question, but if I have 3 databases and let's say 5 df files, how are tables of a df mapped to the correct database?

Does the name of the df file matter?

I'm getting errors like

`Syntax error -- target/src/man/xml_nbuf.p:44:27 -- no viable alternative at input 'genro.ds_Table'`

But the ds_Table is defined in one of the df files.

In ptgenro.df

`ADD TABLE "ds_Table" TYPE PROGRESS`

And some of the sonar properties:

```
sonar.oe.databases=${target.dir}/dbf/glims.df,${target.dir}/dbf/cpage_sh.df,${target.dir}/dbf/genro.df,${target.dir}/dbf/ptgenro.df,${target.dir}/dbf/genrw.df
sonar.oe.aliases=glims,glimssha;genrw,rtgenrw,qrlibgenrw,genrwsha;genro,rtgenro,qrlibgenro,genrosha,source,target,vstdb,dictdb1,dictdb2,SourceGenro,TargetGenro,DB1,DB2,basic,defdb
```

I'm asking because in a df file there's nothing that points to the name of the database itself... 

Is the name of the database by default also an alias?

**Comment by lievencardoen** [comment]
The schema of genro is both located in genro.df and ptgenro.df. I have the idea that the ones in ptgenro.df are ignored.

**Comment by gquerret** [comment]
While including the [link to the documentation](https://github.com/Riverside-Software/sonar-openedge/wiki/Property-list), I saw that the description of sonar.oe.databases was not complete. So yes, the DF file name is the logical name of the DB. This can be overridden by appending `:logicalName`, i.e. `sonar.oe.databases=path/to/foo.df:bar,/path/to/xxx.df:yyy`

**Comment by gquerret** [comment]
And with the current implementation, it's not possible to have tables defined in two separate DF files mapped to a single logical name.

**Comment by lievencardoen** [comment]
Thx. I'll try merging the two files and add :genro to it.
