### ISSUE TITLE
FP in Invalid case for keyword rule with buffer access

### ISSUE THREAD

**Issue by movedoa** [Riverside-Software/sonar-openedge#1013]
Version 2.18

I have uppercase set as default.

This is a field name not a keyword, it has the correct casing.

![grafik](https://user-images.githubusercontent.com/13309951/203548118-6dcec2f4-8368-44a1-a88e-ad030b9a6733.png)

**Comment by gquerret** [comment]
Reproduced

**Comment by gquerret** [comment]
Fixed in develop
