### ISSUE TITLE
Method call incorrectly identified as an abbreviated keyword

### ISSUE THREAD

**Issue by chrisjriddell** [Riverside-Software/sonar-openedge#1016]
Progress' `ILogWriter` interface includes a method named `Info`, the use of which is incorrectly identified as an abbreviation of the `INFORMATION` keyword.

Sample code:
`this-object:logger:Info( substitute( "Loading default system configuration file &1", cConfigFilePath ) ).`

**Comment by gquerret** [comment]
Confirmed, will be fixed in next release.

**Comment by gquerret** [comment]
Fixed
