### ISSUE TITLE
OF keyword instead of WHERE rule should report currently used find fields

### ISSUE THREAD

**Issue by mikefechner** [Riverside-Software/sonar-openedge#102]
It would be very helpful, if the error message would show the fields currently used in the query implicitly by the "OF"

**Comment by KWSMaster** [comment]
Is that even possible? I'm assuming you could pull them out of the XREF if you cross-reference it against the code by line.

**Comment by gquerret** [comment]
The parser has access to the two buffers, and knows their physical structure, so finding the relation used by the `OF` keyword could be done.

**Comment by gquerret** [comment]
Rule enhancement available on [Jenkins](https://ci.rssw.eu/job/sonar-openedge-rules/view/change-requests/job/PR-130/).
Only implemented for now on database tables, not on temp-tables

**Comment by mikefechner** [comment]
Proper modern applications make more use of temp-tables than of the database. :-(

**Comment by gquerret** [comment]
You mean that you write modern applications based on temp-tables, but still work with OF ??

**Comment by mikefechner** [comment]
My clients do.

**Comment by gquerret** [comment]
TT indexes are not yet stored in the ParseUnit, it has to be done before being able to enhance the rule for TT. Next release will only have DB support, TT support will be done shortly after.

**Comment by gquerret** [comment]
Message for DB tables is now available in master branch.
Still WIP for TT, won't be included in 2.1.4

**Comment by gquerret** [comment]
Included in upcoming 2.1.5

**Comment by mikefechner** [comment]
@gquerret 

> Included in upcoming 2.1.5

Is that for DB only or including temp-tables? Is 2.1.5 already released? Or is that functionality currently only available in a feature branch?

**Comment by gquerret** [comment]
Both TT and DB tables in 2.1.5, which has been released one week ago.
