### ISSUE TITLE
Sonar unused parameter issue is reported to wrong author

### ISSUE THREAD

**Issue by ccecvb** [Riverside-Software/sonar-openedge#1020]
This is probably unsolvable, but I post this in the off chance there is a way to fix this.

cvb gets a new sonar issue because ppy removed the code that used the parameter

![image](https://user-images.githubusercontent.com/74775499/212855634-25094537-6db8-42ca-aa0e-794558c41d2e.png)

**Comment by gquerret** [comment]
Is it inherited from another class or interface. I was browsing issues on a project and saw hundreds (if not thousands) of issues raised on methods that inherit an interface, so there's nothing to do. That shouldn't be reported.

**Comment by gquerret** [comment]
And I didn't correctly read the title. Assigning issues is done by SonarQube, not by plugins.
