### ISSUE TITLE
Openedge 11 and CABL 2.19 - compatibility

### ISSUE THREAD

**Issue by clement-brodu** [Riverside-Software/sonar-openedge#1024]
Hello Gilles,

Is your last version (2.19) compatible with openedge 11 ?

I tried to install the eclipse plugin, but I can't.
org.sonarlint.eclipse.site-7.6.2302.zip

I'm using Openedge `11.7.14` with an upgraded eclipse `4.7.3`

Thanks

**Comment by gquerret** [comment]
Version 2.19 is compatible with OE 11.7. However, you have to stay with SonarLint 6.2 on PDSOE 11 (see https://github.com/Riverside-Software/sonar-openedge/wiki/SonarLint-for-Eclipse )

**Comment by clement-brodu** [comment]
ok, sorry for that, next time I will read the documentation 😄
