### ISSUE TITLE
REPOSITION-BACKWARDS vs REPOSITION-BACKWARD?

### ISSUE THREAD

**Issue by LievenDeFoor** [Riverside-Software/sonar-openedge#1032]
Sonar flags REPOSITION-BACKWARD as an abbreviation of REPOSITION-BACKWARDS.
I can't find any occurrence of the string with added S in the OpenEdge documentation.
It does get recognized in the OpenEdge editor but not in OEDT (see https://github.com/omecra/de.omecra.oedt.updatesite/issues/125).
Is this some undocumented "feature" in OpenEdge?

**Comment by PeterJudgeZA** [comment]
The ABL thinks it should be plurarlised. It's at least a doc bug.

![grafik](https://user-images.githubusercontent.com/8291561/223172959-5289b555-2aef-48b5-baab-9927bd42b4f3.png)

**Comment by gquerret** [comment]
Keyword list in the parser is currently generated from the output of `prowin -zgenkwlist`, which says `reposition-backwards`. I don't think Progress will ever change the documentation to match that, I'll probably add the keyword in the default exclusion list.

**Comment by gquerret** [comment]
Fixed in develop
