### ISSUE TITLE
Enhancement request:  message only match statement

### ISSUE THREAD

**Issue by ccecvb** [Riverside-Software/sonar-openedge#1038]
```
    hide message.
```
triggers the message (rssw-oe-main:message) rule

OpenEdge plugin version: 2.16.0-93e1c62f

**Comment by gquerret** [comment]
Not a real FP, as the `message` keyword is spotted . However, I assume you'd like to only see `message` statements, so an enhancement request could be to be to add a "Only match statements" in the rule.

**Comment by gquerret** [comment]
There already was a way to detect two-parts statements with `DEFINE^VARIABLE` or `CREATE^BROWSE` parameter. It's now possible to use `MESSAGE^`  to detect only MESSAGE statements.
