### ISSUE TITLE
Conversion overflow rule not considered by SonarLint

### ISSUE THREAD

**Issue by maelstraggiotti** [Riverside-Software/sonar-openedge#1046]
Hi, 

we recently activated the VariableOverflow rule which is correctly executing on the server. However, SonarLint doesn't report it correctly. 

The server issues are correctly fetched. The console gives no errors and a correct issue count, but that particular issue is not shown in the SonarLint Report view. For instance : 

`Wrote 10 issues in store | took 4ms`

![image](https://github.com/Riverside-Software/sonar-openedge/assets/2782049/96d9d585-5dbc-48b8-b073-4fec7c280526)

On-The-Fly and manual analysis gives the same result. I tried with multiple files and contexts.

Latest plugin and SonarLint versions. SonarQube 8.8. OE 12.2.11.

Thanks

**Comment by gquerret** [comment]
Apologies for the delay. I'll verify if this rule could have an issue with SonarLint.

**Comment by maelstraggiotti** [comment]
Got any news? I might have several other similar behaviors with Xref rules not indicated by SonarLint that requires further investigation. Thanks.

**Comment by gquerret** [comment]
Fixed in [SonarLint 9.1.2906](https://github.com/Riverside-Software/sonar-openedge/releases/tag/V2.24.1)
