### ISSUE TITLE
False positive on statement should be on a separate line.

### ISSUE THREAD

**Issue by mikefechner** [Riverside-Software/sonar-openedge#106]
![image](https://cloud.githubusercontent.com/assets/13220627/20453348/a93b4fb4-ae21-11e6-8be4-195bbc32ea3a.png)

**Comment by mikefechner** [comment]
Or here: 

![image](https://cloud.githubusercontent.com/assets/13220627/20453351/d69feec4-ae21-11e6-9c9a-ab1436d41222.png)

**Comment by gquerret** [comment]
File index is not correctly checked in this rule. Last statement of previous include file is also on line 39, so the `DEFINE VARIABLE` was considered to be on the same line.

**Comment by gquerret** [comment]
Will be fixed today.

**Comment by gquerret** [comment]
Fixed in master
