### ISSUE TITLE
Sonarlint - OE11.7 - internal error occured

### ISSUE THREAD

**Issue by clement-brodu** [Riverside-Software/sonar-openedge#1067]
Hello, 

Since we update to plugins 2.22.0, we have this error in Openedge 11.7

![image](https://github.com/Riverside-Software/sonar-openedge/assets/37274615/2300104d-fb5e-4424-8838-01ee16622b9f)

The error is the same for every files.

Do you have an idea ?

**Comment by gquerret** [comment]
[Hotfix 2.22.2](https://github.com/Riverside-Software/sonar-openedge/releases/tag/V2.22.0) is now available. Install in SonarQube and don't forget to refresh the binding in Developer Studio.
Sorry for the inconvenience !
