### ISSUE TITLE
Consider Interface and Enum's as always executed during code-coverage

### ISSUE THREAD

**Issue by mikefechner** [Riverside-Software/sonar-openedge#107]
I assume Interfaces and Enum's will never appear in the profiler output. But I guess they count towards the total line number count. If that's correct, I'd suggest that Interfaces and Enums are always considered as executed so that there is no penalty for using Interfaces in the test coverage quota.

**Comment by gquerret** [comment]
Interfaces and Enum's don't have executable line in rcode, so they won't increase the total number of LoC (at least in 11.6).
You could double-check that by looking for interface or enum in your profiler output.

**Comment by mikefechner** [comment]
OK - in that case we can close this ticket. I was not aware how you compute the total number of lines - from SRC or R-Code.

**Comment by gquerret** [comment]
Total number of lines is extracted from the profiler output which mentions for each file the executable lines.
This information can also be retrieved from the rcode.
