### ISSUE TITLE
Sonar scanner execution killed - where can I find details about the error / how to debug

### ISSUE THREAD

**Issue by SimonJohnAde** [Riverside-Software/sonar-openedge#1070]
Afternoon.

I am having some strange/random results when running the sonarscanner (v5.0.1)
For context, I am in the process of scaling up and scanning the the entire code base. Currently just 2 directories (one with 1925 files in it and the second 114 files)

I start the sonar scanner and it fails at different places when I re-run it. Does not seem to fail at the same place every time.
When it does fail. the last line on screen just displays: 'Killed'  with no further error message or stack.

I am using the -X parameter to envoke the full debug on output

**80% of the time the preceeding debug line says:**
`DEBUG: Listing file for '<theFileName>' not found or contains space character - Was looking for 'null'`
**20% of the time, the preceeding debug line says:**
`INFO: 342/1787 - current file: <theFileName>`

Something else I tried was: take the filename that failed during the scan, and point the scanner to analyse just that single file by updating the build.xml and sonar-project.properties.
The scanner completed successfully so the file was not causing the scanner to fail.

As it is random, I'm thinking system resources but not sure how to track it down.
I have also tried increasing available memory with:
`export SONAR_SCANNER_OPTS="-Xmx4096m"`

Does anyone have any ideas please?
Much appreciated

I will attach a few screen shots for more info but happy to answer any questions.

**Fail attempt 1**
![Picture1_fail](https://github.com/Riverside-Software/sonar-openedge/assets/25798292/ce50c7fe-1e1d-4938-ad55-4724b8c0e1ce)

**Fail attempt 2**
![Picture2_fail](https://github.com/Riverside-Software/sonar-openedge/assets/25798292/a631afe6-99a5-4fad-ba42-b62d72704069)

**Fail attempt 3**
![Picture3_fail](https://github.com/Riverside-Software/sonar-openedge/assets/25798292/f53ab41a-606d-4829-817b-925f053fa735)

**Fail attempt 4**
![Picture4_fail](https://github.com/Riverside-Software/sonar-openedge/assets/25798292/63287fc1-cc45-49d7-849f-15f276ffbfb5)

**Success scanning single file that failed previously_a**
![Picture5_succes_scanOneFile](https://github.com/Riverside-Software/sonar-openedge/assets/25798292/31401105-c415-48d6-9840-ea4f41ea5d21)

**Success scanning single file that failed previously_b**
![Picture6_succes_scanOneFile](https://github.com/Riverside-Software/sonar-openedge/assets/25798292/a10c2a18-50bb-412b-8aed-20b7ece43d92)

**Comment by gquerret** [comment]
The screenshots are really small, it's difficult to see what happens exactly. You can redirect the standard output and standard error with `sonar-scanner -X > output.txt 2>&1`

The message `DEBUG: Listing file for '<theFileName>' not found or contains space character - Was looking for 'null'` is not an error message, you can discard them. I assume you didn't compile with the listing option (or not with PCT).

The message `INFO: 342/1787 - current file: <theFileName>`  is displayed every minute, so it's just in indicator of how fast the analysis is being done.

What I see is that the process seems to be killed. Do you run the analysis on a machine which doesn't have a lot of memory ? That could be the OOM killer that kills the sonar-scanner process.

**Comment by SimonJohnAde** [comment]
That was it, not enough memory.
I thought I had enough but it was the combination of the scanner plus our own product that just tipped the scales.

I am running this in WSL2 and so configured the VM with 10GB and ran successfully first time.

Thank you for the help.
