### ISSUE TITLE
Conversion could overflow variable

### ISSUE THREAD

**Issue by stefandrissen** [Riverside-Software/sonar-openedge#1076]
To prevent ``{&_proparse_ prolint-nowarn(overflow)}`` noise to suppress Conversion from DECIMAL to INT can overflow if source expression is larger than 2^32:
````
DEFINE VARIABLE ifoo AS INTEGER NO-UNDO.

ifoo = ifoo / 2.
````
Can the expression parser be improved?

**Comment by gquerret** [comment]
Expression engine evaluates datatypes, but doesn't really know the values (though it could). It's however clear that `int` divided by `int` results in a decimal rounded to an int, but within the integer range. Will be fixed.

**Comment by gquerret** [comment]
Fixed in develop branch
