### ISSUE TITLE
Assigned but never used

### ISSUE THREAD

**Issue by LievenDeFoor** [Riverside-Software/sonar-openedge#1077]
```
DEFINE VARIABLE Publisher AS HANDLE NO-UNDO.
ASSIGN Publisher = SomeHandle.
PUBLISH "MyEvent":U FROM Publisher (Parameters).
```

Publisher gets flagged with "Variable Publisher is assigned but never read"

If there are no parameters (`PUBLISH "MyEvent":U FROM Publisher.`) then the warning disappears.

**Comment by gquerret** [comment]
CABL version ?

I couldn't reproduce.  Is this the exact code ?
![image](https://github.com/Riverside-Software/sonar-openedge/assets/6498723/f508fd1d-917c-4ce6-a40d-a94a0a330b67)

**Comment by stefandrissen** [comment]
Ran into this today - there are several prerequisites:
1. must be in a class
2. publish must pass parameters
````
CLASS foo:

   METHOD VOID bar ():

      DEFINE VARIABLE hp   AS HANDLE      NO-UNDO.

      hp = SESSION:FIRST-PROCEDURE.
      PUBLISH 'bar':u FROM hp ( ? ).

   END METHOD.

END CLASS.
````

**Comment by stefandrissen** [comment]
The same issue applies to ``run on`` - also only in a class and with parameters:
````
class foo:

   constructor foo ():

      define variable bar as handle no-undo.

      bar = session.

      run something on bar (?).

   end constructor.

end class.
````

**Comment by gquerret** [comment]
Thanks, reproduced.
