### ISSUE TITLE
Filelist support for CABL

### ISSUE THREAD

**Issue by ssaulius123** [Riverside-Software/sonar-openedge#1086]
It is more question, then ticket. We have situation, that our Jenkins+PCTCompile build need to use different database connections sets or PROPATH list for files in the same directory. We manage it by special text files, where we list which files to use with specific compilation configuration. In CABL documentation I find, that it is possible only, if files is in different directories. Nuu, if I write something like bellow to sonar-project.properties:
```
sonar.oe.module1.pattern=${env.WORKSPACE}/src/git/payments/src/nbsf-services
sonar.oe.module1.databases=${env.WORKSPACE}/dump/ar2022/ar2022.df,${env.WORKSPACE}/dump/bank/bank.df,${env.WORKSPACE}/dump/logbank/logbank.df,${env.WORKSPACE}/dump/tl/tl.df,${env.WORKSPACE}/dump/req/req.df
sonar.oe.module1.aliases=archive;bank;logbank;tl
sonar.oe.module1.propath=${env.WORKSPACE}/src/git/payments/src/nbsf-services,${env.WORKSPACE}/src/git/payments/src/includes,${env.WORKSPACE}/src/git/nbsx-shared/src/nbsf-services,${env.WORKSPACE}/src/git/nbsx-shared/src/includes,${env.WORKSPACE}/src/svn/nbsx/includes,${env.WORKSPACE}/src/git/payments/src/progress,${env.WORKSPACE}/src/git/nbsx-shared/src/progress
```
Do we have any plans to use text file for `sonar.oe.module1.pattern=` or maybe I miss something in documentation?

Thank you

**Comment by gquerret** [comment]
This is currently not on the roadmap. As a workaround, you may use Ant to generate the file list, and use the value in `sonar.oe.module.pattern`.

**Comment by ssaulius123** [comment]
Thank you @gquerret . I expected this answer, and just wanted double check.
