### ISSUE TITLE
Is CABL/SQ support database aliases in source code?

### ISSUE THREAD

**Issue by ssaulius123** [Riverside-Software/sonar-openedge#1087]
Hi,

I try to continue to work with my "complex repo modularization", and have some strange issue. 

I move some files in sonar-project.properties to separate module:

```
##Default parameters
<...skip...>
sonar.sources=${env.WORKSPACE}/src/git/cards/src/progress,${env.WORKSPACE}/src/git/cards/src/includes
sonar.oe.propath=${env.WORKSPACE}/src/git/cards/src/progress,${env.WORKSPACE}/src/git/cards/src/includes,${env.WORKSPACE}/src/git/cards/src/nbsf-services,${env.WORKSPACE}/src/git/nbsx-shared/src/includes,${env.WORKSPACE}/src/git/nbsx-shared/src/progress,${env.WORKSPACE}/src/git/nbsx-shared/src/nbsf-services,${env.WORKSPACE}/src/svn/nbsx/includes,${env.DLC},${env.DLC}/tty
sonar.oe.dlc.propath=true
##sonar.exclusions=src/procedures/sample/excl/** - do I need list here all our my modules exclusions ?
sonar.oe.databases=${env.WORKSPACE}/dump/bank/bank.df,${env.WORKSPACE}/dump/logbank/logbank.df,${env.WORKSPACE}/dump/stat/stat.df,${env.WORKSPACE}/dump/tl/tl.df,${env.WORKSPACE}/dump/sulabaas/sulabaas.df,${env.WORKSPACE}/dump/tmpbank/tmpbank.df,${env.WORKSPACE}/dump/ar2022/ar2022.df,${env.WORKSPACE}/dump/kar/kar.df
sonar.oe.aliases=bank;logbank;stat;tl;sulabaas;tmpbank;archive;archive0
<...skip...>
##Module for CRM modules
sonar.oe.module2.pattern=${env.WORKSPACE}/src/git/cards/src/progress/card-createPrime*.p
sonar.oe.module2.databases=${env.WORKSPACE}/dump/bank/bank.df,${env.WORKSPACE}/dump/logbank/logbank.df,${env.WORKSPACE}/dump/crm/crm.df
sonar.oe.module2.aliases=bank;logbank;crm
sonar.oe.module2.propath=${env.WORKSPACE}/src/git/cards/src/nbsf-services,${env.WORKSPACE}/src/git/cards/src/includes,${env.WORKSPACE}/src/git/nbsx-shared/src/nbsf-services,${env.WORKSPACE}/src/git/nbsx-shared/src/includes,${env.WORKSPACE}/src/svn/nbsx/includes,${env.WORKSPACE}/src/git/cards/src/progress,${env.WORKSPACE}/src/git/nbsx-shared/src/progress
<...skip...>
```

I expect, that my modules with **card-createPrime** pattern, will be compiled with different database set, and will be excluded from default pattern, as is written in documentation https://github.com/Riverside-Software/sonar-openedge/wiki/Property-list#modules-since-290 

> During the analysis, file names are compared with the pattern of all modules (using the order in which they are defined). If the file name matches a pattern (first match wins), then it will be analyzed with those specific values (propath and db connections). If the file name doesn't match any pattern, then it will be analyzed with the default parameters.

But I get error's like:

```
[2023-11-13T07:18:52.620Z] ERROR: Syntax error -- src/progress/card-createPrimeClosedContracts.p:580:10 -- no viable alternative at input 'crm.leping'
[2023-11-13T07:18:52.620Z] ERROR: Parser error in 'src/progress/card-createPrimeClosedContracts.p' at position src/progress/card-createPrimeClosedContracts.p:580:10
```
Error line is 
```
FIND crm.leping WHERE crm.leping.number = mer_cont.lepnr NO-LOCK NO-ERROR.
```
And source code **card-createPrimeClosedContracts.p** analysis by SQ isn't done. Where can be problem?

1. For some reasons it is taken to default pattern ? For example, because module2.pattern falls into it? 
2. Do SQ/CABL support database aliases? crm in crm.lepping is database alias, and as I understand it parse .df file, where we have leping tabel without crm alias?
3. Case sensitive. In .df file, table is LEPING, in source code crm.leping.
4. Some another error?

I do not want share whole config files in public, but if you need more quotes from it, I would be happy to provide it.

Thank you

**Comment by ssaulius123** [comment]
I tested another module without db alias:

`
sonar.oe.module3.pattern=${env.WORKSPACE}/src/git/cards/src/progress/atm-konto.p
sonar.oe.module3.databases=${env.WORKSPACE}/dump/bank/bank.df,${env.WORKSPACE}/dump/req/req.df
#${env.WORKSPACE}/dump/logbank/logbank.df,${env.WORKSPACE}/dump/tl/tl.df,${env.WORKSPACE}/dump/crm/crm.df,${env.WORKSPACE}/dump/req/req.df,${env.WORKSPACE}/dump/ar2022/ar2022.df
sonar.oe.module3.aliases=bank,req
#sonar.oe.module3.propath=${env.WORKSPACE}/src/git/cards/src/nbsf-services,${env.WORKSPACE}/src/git/cards/src/includes,${env.WORKSPACE}/src/git/nbsx-shared/src/nbsf-services,${env.WORKSPACE}/src/git/nbsx-shared/src/includes,${env.WORKSPACE}/src/svn/nbsx/includes,${env.WORKSPACE}/src/git/cards/src/progress,${env.WORKSPACE}/src/git/nbsx-shared/src/progress
`
And got another error:
`
[2023-11-13T08:39:37.308Z] ERROR: Syntax error -- src/progress/atm-konto.p:335:33 -- Unknown table: acc
[2023-11-13T08:39:37.308Z] ERROR: Parser error in 'src/progress/atm-konto.p' at position src/progress/atm-konto.p:335:33
`
In req.df file we have 
`
ADD TABLE "acc"
  AREA "acc_data"
  DESCRIPTION "Pangaobjektide puhver"
  DUMP-NAME "acc----1"

ADD FIELD "type" OF "acc" AS character 
  FORMAT "x(1)"
  INITIAL ""
  POSITION 2
  MAX-WIDTH 2
  ORDER 10
`
In source code
`
                  THEN DO:
                     FIND FIRST acc 
                     WHERE acc.tcif = atm-kood AND acc.type = "SEANS" AND
                              acc.acc = "TMLIST" NO-LOCK NO-ERROR.
                     IF AVAILABLE acc AND
                       /* acc.dbaaa = aaa.aaa */
                       /* acc.dbaaa = TRIM(v2-aaa) + TRIM(s-code)  VAR_2 */
`

**Comment by gquerret** [comment]
Can you run the analysis with debug log output ? Files belonging to a specific module will be displayed. I'll also do extra checks about the databases and aliases, maybe there's an issue here.
Database schema is not case sensitive.

**Comment by ssaulius123** [comment]
Mmm, it depend how. Our Jenkins is managed by other team, and after run delete working dir. Only log's goes t Jenkins.
----
Can you clarify how it can be done? (in sonar-project.properties or somehow) Thank you.

**Comment by gquerret** [comment]
Add `-X` to the sonar-scanner command line. See https://docs.sonarsource.com/sonarqube/9.9/analyzing-source-code/scanners/sonarscanner/

**Comment by ssaulius123** [comment]
Thnx. I will ask my automation team, who can do it.

**Comment by ssaulius123** [comment]
We get huge output, but I do not see nothing special there.

`
[2023-11-13T10:32:20.205Z] 12:32:20.023 DEBUG: 'src/progress/card-createPrimeClosedContracts.p' indexed with language 'oe'
[2023-11-13T10:32:23.765Z] 12:32:23.539 DEBUG: 'src/progress/card-createPrimeClosedContracts.p' generated metadata with charset 'windows-1257'
`

**Comment by ssaulius123** [comment]
Some update. I moved modules to separate directory, but did not manage yet run SQ scan from new one. Will continue tomorrow.

**Comment by gquerret** [comment]
Files matching module patterns are visible in the log output:
```
File xxx matches pattern zzzz in module X
```
It seems the pattern matching doesn't work. Can you try removing the `${env.WORKSPACE}` prefix ? I suspect that it's the cause of the problem. Or maybe you can try `**/something*.p` for example.

**Comment by ssaulius123** [comment]
Hi @gquerret . Yep, I managed to fix, if put modules to separate directories. And like it, because in this case you can understand better, which file is compiling.

I playing with patterns from the same directory now. Will wrote, when finish.

Thank you for immediate support.

**Comment by ssaulius123** [comment]
Question (maybe it help to improve documentation ;-) ). I decided to make so, that all my source codes is "in modules". I have file, which in directory of module-1 (pattern=<full directory>/*), but I want scan it by module-X (pattern=<full directory>/concrete_file.p). At this stage, I see error (not connected database), because it was scanned in module-1. If I want to scan it in module-X... Is it mean, that I need reorder modules (file-pattern make module-1, and directory-patern - module-X)?

Thank you

Thank you

**Comment by gquerret** [comment]
Module patterns are applied sequentially. A file belongs to the first module whose pattern matches its name.

**Comment by ssaulius123** [comment]
Ok, clear. Thnx. 

I'm ready to close issue, but have one more question (not related with modules, but maybe you can answer here too). SQ plugin do not find listing files. Errors is like
`
[2023-11-14T09:26:05.732Z] 11:25:55.433 DEBUG: Listing file for 'src/progress/crd-req1.p' not found or contains space character - Was looking for 'null'
`
Files itself is generated by PCT, and are in folder
![image](https://github.com/Riverside-Software/sonar-openedge/assets/108174688/e226eac1-1beb-4ba4-bc8c-1e235e7fac74)

Folder is mentioned in 
`
sonar.oe.dotpct=${env.WORKSPACE}/build/progress/xref,${env.WORKSPACE}/build/nbsf-services/xref,${env.WORKSPACE}/build/progress/debug,${env.WORKSPACE}/build/nbsf-serivces/debug
`

Maybe I need another type of listings?

BTW, how important is listing in source code scanning? Maybe I do not need dig deeply in it?

Thank you

**Comment by gquerret** [comment]
Listing files are only useful to report an issue when the transaction scope spans the entire procedure.

What is the full path of the listing file in this environment?

**Comment by gquerret** [comment]
If you have this structure:
```
<root_dir>
  \__ src
    \__ subdir1
      \__ foo.p
```
When using PCTCompile with `target` build directory, and `src` (with `**/*.p`pattern) as the source directory, you'll end up with this structure:
```
<root_dir>
  \__ target
    \__ .pct
      \__ subdir1
        \__ foo.p ## Listing file
    \__ subdir1
      \__ foo.r   ## RCode
```

If you have the same structure for `sonar.sources`, `sonar.oe.binaries` and `sonar.oe.dotpct`, then sonar-scanner will search for `subdir1/foo.p` (filename relative to `src`) in all `.pct` directories.

**Comment by ssaulius123** [comment]
Ok. It is only one rule, but quite important - we really have some old files with "whole transaction scope".

Directory structure is something like:
`
output_dir
  build
    debug
	proprocess
	rcode
	xref
  dump
    *.df
  src
    git
	  cards
	  shared
`
There is one PCTCompile fragment for one module (I changed some variables to directory names like "build/debug" quickly - there can be mistakes).

I see that build/debug folder do not have subfolders. In other folders there is "sub-folders" based on source tree, but most files is in the root.
![image](https://github.com/Riverside-Software/sonar-openedge/assets/108174688/c43af5e4-e63a-44d9-9490-0231521485d9)

At the same time, I find listing files not only in  build/debug, but on xref folder too. Maybe problem is there?

If you want to make some "testing", I can. ;-)

Thank you

![image](https://github.com/Riverside-Software/sonar-openedge/assets/108174688/8f4408bc-a708-41a0-8477-e37879171bd6)

**Comment by ssaulius123** [comment]
Hi.

I tried to simplify debugging. Leave in SQ properties only one directory: `sonar.oe.dotpct=${env.WORKSPACE}/build/progress/rcode/.dbg`

In workspace directory exist 
![image](https://github.com/Riverside-Software/sonar-openedge/assets/108174688/7958808f-7ea8-45cc-afd6-428910b630d4)

And have files like 

![image](https://github.com/Riverside-Software/sonar-openedge/assets/108174688/87ccac62-6cc1-413d-bdcf-eb2791d4ec5f)

But in log's I see errors like:

`[2023-11-17T08:46:24.270Z] 10:46:24.209 INFO: 939 files proparse'd, 0 XREF files, 0 listing files, 5 failure(s), 338494 NCLOCs
`
and 

 `[2023-11-17T08:46:17.701Z] 10:46:17.447 DEBUG: Listing file for 'src/progress/activateCard.p' not found or contains space character - Was looking for 'null'
`
Maybe we need another type of listing file?

**Comment by ssaulius123** [comment]
And I see another bad message "0 XREF files". What mean, that xref files most probable do not see... :-(
