### ISSUE TITLE
Accessing a protected temp-table from base class throws error in sonarlint

### ISSUE THREAD

**Issue by movedoa** [Riverside-Software/sonar-openedge#1088]
V2.23.1 

SonarLint doesnt work in SecondClass.cls
The same class is analyzed without any erorrs in the ant task, the error only happenes in SonarLint.

`Parser error in '[uri=file:/SomePath/App/Prog/Src/SecondClass.cls]' at position App/Prog/Src/SecondClass.cls:4:18`

```
CLASS BaseClass:
   DEFINE PROTECTED TEMP-TABLE ttFoo NO-UNDO
      FIELD foo1 AS CHARACTER
   .
END CLASS.
```

```
CLASS SecondClass INHERITS BaseClass:
   METHOD PRIVATE VOID FooMethod(
   ):
      FIND FIRST ttFoo NO-LOCK NO-ERROR.
   END METHOD.
END CLASS.
```

**Comment by gquerret** [comment]
Isn't that similar to issue #819?

**Comment by movedoa** [comment]
> Isn't that similar to issue #819?

i guess but i don't see any config problems

**Comment by movedoa** [comment]
Can i provide any more infos to help narrow this problem down?
We have a lot of issues that only pop up when running the analysis on the server.

**Comment by gquerret** [comment]
I'll contact you offline to get extra details.
