### ISSUE TITLE
Can Fast branch analysis be used with sonarqube-community-branch-plugin

### ISSUE THREAD

**Issue by ccecvb** [Riverside-Software/sonar-openedge#1094]
Release 2.24 introduces Fast branch analysis https://github.com/Riverside-Software/sonar-openedge/releases/tag/V2.24.1.

Can this be used with https://github.com/mc1arke/sonarqube-community-branch-plugin.

If not, could it be adapted to also work for that plugin ?

As far as I can tell, onarqube-community-branch-plugin also requires `-Dsonar.pullrequest.branch` to be set. Is that the only requirement to activate the fast branch analysis ?

**Comment by gquerret** [comment]
CABL does a [check](https://github.com/Riverside-Software/sonar-openedge/blob/develop/openedge-plugin/src/main/java/org/sonar/plugins/openedge/foundation/OpenEdgeSettings.java#L546) against the SQ edition being used. You could remove the check and compile your own version of the plugin, but I can't guarantee anything.

A quick glance at the project shows that you have to enable a Java agent on the SonarQube runtime, so it probably works by modifying the bytecode at runtime to enable branch support. I really don't think that's a long term solution to work with branches.
