### ISSUE TITLE
Scanner Performance issue after installing 2.24

### ISSUE THREAD

**Issue by ccecvb** [Riverside-Software/sonar-openedge#1097]
I noticed our sonarscan is taking a lot longer now than before.

scan now, build 151, using 2.24.x, takes 1 hour 14 minutes
![image](https://github.com/Riverside-Software/sonar-openedge/assets/74775499/dbaa3552-e708-4d66-af1c-e98c30f42205)

```
15:13:15  INFO: ------------------------------------------------------------------------
15:13:15  INFO: EXECUTION SUCCESS
15:13:15  INFO: ------------------------------------------------------------------------
15:13:15  INFO: Total time: 1:14:13.409s
15:13:15  INFO: Final Memory: 550M/2048M
15:13:15  INFO: ------------------------------------------------------------------------
``` 

same scan build 148, before using snapshot 2.25, took 26 minutes
![image](https://github.com/Riverside-Software/sonar-openedge/assets/74775499/0d84bbe0-40fe-4f8a-878e-87b131d6e736)

```
01:40:44  INFO: ------------------------------------------------------------------------
01:40:44  INFO: EXECUTION SUCCESS
01:40:44  INFO: ------------------------------------------------------------------------
01:40:44  INFO: Total time: 26:45.943s
01:40:45  INFO: Final Memory: 550M/2048M
01:40:45  INFO: ------------------------------------------------------------------------
``` 

One difference on our side is that build 150 was during office hours and build 148 was during the night. I should have data of the next nightly build tomorrow.
I also activated a few extra rules, but I would not expect this performance impact.  I'll attach full scanner logs for both builds

Versions 
* sonar-scanner-5.0.1.3006-windows
* riverside latest 2.24.x versions
* sonarqube community edittion 9.9.1 (build 69595)

**Comment by gquerret** [comment]
Log output contains execution time of the proparse sensor, as well as execution time of each rule (search for `AST Generation` in log). Could you include the log here?
FWIW, no difference has been spotted during regression testing.

**Comment by ccecvb** [comment]
found this significant difference, it causes extra 44 minutes

build 148
INFO: Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.LowerCaseKeywords | time=545494 ms

vs build 151 (got wrong number before)
INFO: Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.KeywordCase | time=1593736 ms
and apparently I forgot to turn off the deprecated one
INFO: Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.LowerCaseKeywords | time=1622626 ms

I'll attach the logs

**Comment by ccecvb** [comment]
[scan148.log](https://github.com/Riverside-Software/sonar-openedge/files/13637976/scan148.log)
[scan151.log](https://github.com/Riverside-Software/sonar-openedge/files/13637977/scan151.log)

**Comment by gquerret** [comment]
* Did you upgrade sonar-scanner at the same time ?
* Is the number of issues different between build 148 and 151 ?

**Comment by ccecvb** [comment]
* scanner version did not change
* I think the number iof detections did not change but I don't know how to verify this . Is there a way to detect the number of violations in the log or check in sonarqube; old and new rule report same amount in current log

[scan148.log](https://github.com/Riverside-Software/sonar-openedge/files/13646180/scan148.log)
[scan151.log](https://github.com/Riverside-Software/sonar-openedge/files/13646181/scan151.log)
[scan152.log](https://github.com/Riverside-Software/sonar-openedge/files/13646182/scan152.log)

* last night, build 152 the time was significantly lower than build 151 but still higher than build 148
INFO: Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.LowerCaseKeywords | time=880621 ms
INFO: Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.KeywordCase | time=858282 ms

**Comment by gquerret** [comment]
Just had a look at the version number of the plugins. Build 148 is using 2.25.0-SNAPSHOT that I sent you, while builds 151 and 152  are using 2.24.2. There's strictly no difference between those two versions except for the IndentationCheck rule, so the difference is coming from your systems.

**Comment by gquerret** [comment]
> I think the number iof detections did not change but I don't know how to verify this . Is there a way to detect the number of violations in the log or check in sonarqube; old and new rule report same amount in current log

You can check the Activity tab on the project. You can see the total number of issues over time.

**Comment by gquerret** [comment]
If you have hundreds of thousands or millions of issues being reported by this rule, you can expect it to take quite some time. As an example, on a 1M LOC project, where the coding standard is uppercase, it takes 11 seconds to execute the rule to report lowercase keywords. If I switch the config to report uppercase keywords, then it takes 230 seconds to execute the rule (and report 1.5 million issues).

**Comment by ccecvb** [comment]
@gquerret FYI the Activity tab indication shows a growth consistent with testing the same issue with 2 rules, new and deprecated.
I'll drop the rule from the scanner rules and try use it only in SonarLint interactive checking.
