### ISSUE TITLE
pre processor issue with compile and parsing

### ISSUE THREAD

**Issue by Gpandye** [Riverside-Software/sonar-openedge#11]
I came across an issue with parsing of file.
here is the scenario -

- debug-list is generated for program.
- debug-list output file is copied to srcdbg with the help of com.phenix.pct.DebugListingFilterReader
- when running pct compile with this new program, it is failing, because pre-processor statements are not removed and due to that we are getting compile error.

the statement in .i program is as below -

    &IF DEFINED(NO-CHNGINFO) = 0
    &THEN
        T-PROC.CHANGESRCE
        T-PROC.CHANGEDATE
     &ENDIF

when it was used in a .p program NO-CHNGINFO was passed as parameter to .i program, so it compiled, but since this new program (which is created from debug-list) is not having NO-CHNGINFO as parameter and this statement stays valid, hence it didn't compiles.

Another thing i was thinking that why we are using debug-list program for generating a listing and xref, why can't we use preprocess file and the do listing and xref. By that way we can fix preprocess issues.

**Comment by jakejustus** [comment]
Debug listing is now only used for code coverage, so there shouldn't be any need to compile the debug listing anymore (as opposed to what is said in the documentation, that will be fixed).

**Comment by Gpandye** [comment]
Thanks! So with new release we can run sonar scanner on preprocessed programs? Please update the process (as currently we create debuglist and then copy it and compile).

**Comment by jakejustus** [comment]
Updated the 'Getting started' page. Debug listing is only for code coverage and doesn't have to be compiled anymore.
