### ISSUE TITLE
False positive for missing :U on .NET inner type

### ISSUE THREAD

**Issue by mikefechner** [Riverside-Software/sonar-openedge#110]
The `System.Environment+SpecialFolder` in this sample 
![image](https://cloud.githubusercontent.com/assets/13220627/20571236/e966bec4-b1a6-11e6-85ad-4d1fd1ae6290.png)
should not be requiring the `:U`

1. it's not going to appear in the string-xref as the compiler interprets this as a .NET inner type (the quote is required here)
2. on some Progress releases a few random occurances of :U on .NET inner types and generic types and arrays crash the compiler (OpenEdge 11.6.3 does not crash at this sample).

But for those two reasons I consider :U'ing a quoted .NET type name a mistake.

**Comment by movedoa** [comment]
If you do this, please make it optional, i want :U everywhere for consistency.

Offtopic: @mikefechner  Is this case you don't need the quotes ;-)  (at least in 11.6)

**Comment by gquerret** [comment]
@mikefechner  Just for clarity, how would you want to detect those strings ? Any string which is in fact a .Net type ? And could you confirm movedoa comment on quotes which are not required ?

**Comment by mikefechner** [comment]
Surprisingly enough, the inner type reference (+ sign) does work without quotes now - but didn't in an earlier release.

```
DEFINE VARIABLE o AS "System.Windows.Forms.Control[]" NO-UNDO .
DEFINE VARIABLE o2 AS "System.Collections.Generic.List<System.Windows.Forms.Control>" NO-UNDO .

```

.NET Arrays (and that's different from an ABL EXTENT variable) and .NET Generic types still require quotes. The values are still compile time validated, they don't appear in the STRING-XREF and when I discussed the occasional compiler crashes caused by :U's on those type name references, Laura Stern said she considers it a bug, that the compiler accepts :U on a quoted .NET type name ....

**Comment by gquerret** [comment]
Internal enhancement request (still WIP) logged to transform such quoted strings into an ID (where :U rule doesn't apply).
