### ISSUE TITLE
SonarLint - Fix for #1095 works intermittently in bigger source files

### ISSUE THREAD

**Issue by movedoa** [Riverside-Software/sonar-openedge#1105]
2.24 with sonarlint 9.1.2906

When i open a bigger source file and save, i see issues like "Use enumRef:getValue() instead of INTEGER(enumRef)" no problem.
If i then save/analyze again all the issues vanish and i see only those that where there before the #1095 fix.

If i then compile again with an syntax error in the file, solve the error and compile again, all issues are back until i save again.
What i noticed is that i get "PDSOE currently building code model, rcode information not yet available" when it doesnt work, so i guess this is a race condition/timing problem somewhere.

**Comment by gquerret** [comment]
Fixed, that will be available in 9.1.2912
