### ISSUE TITLE
Character conversion error from encoding UTF-8

### ISSUE THREAD

**Issue by clement-brodu** [Riverside-Software/sonar-openedge#1111]
Hello, 

With last 2.25.0 version, in Openedge 11.7.14 we have those problems : 

```
Character conversion error in S:\Somewhere\toto-api.i at line 196 column 127 from encoding UTF-8
Character conversion error in S:\Somewhere\titi.i at line 2 column 21 from encoding UTF-8
```

![image](https://github.com/Riverside-Software/sonar-openedge/assets/37274615/2a3c0f53-9bad-4556-b191-962457cac95e)

Our Sonarlint plugins are up to date.

All our sources are in windows-1252/Cp1252.

We have the problem on `*.w` files, but it seems to be OK in other extensions `*.cls` and `*.p`

We don't have the problem in Openedge 12

```
Trigger: EDITOR_CHANGE
Clear markers on 0 excluded files
SonarLint processing file /archi-erp/Src/copylig_ph.w...
Language on L/archi-erp/Src/copylig_ph.w
Entering canConfigure...
useXrefXML: false
sonar.sources set to 'D:\Openedge\workspace-oe11\archi-erp\Src'
sonar.oe.propath set to 'D:\Openedge\workspace-oe11\archi-erp\Src,D:\Openedge\workspace-oe11\archi
/********************************/
No PL cache overwrite
Project has DB connections, looking for file D:\Openedge\workspace-oe11\archi-erp\.sonarlint\dblist.txt
Reading dblist.txt
Connected mode (using configuration of 'archi-erp' in connection 'sonarqubepgs.proginov.eu')
Starting analysis with configuration:
[
  projectKey: archi-erp
  baseDir: D:\Openedge\workspace-oe11\archi-erp
  extraProperties: {sonar.sourceEncoding=Cp1252, sonar.oe.propath=D:\Openedge\workspace-oe11\archi-
/***************************************************************/
sonar.oe.binaries=D:/Openedge/workspace-oe11/archi-erp/Obj, sonar.sources=D:\Openedge\workspace-oe11\archi-erp\Src, sonar.oe.lint.pl.cache=D:\Openedge\workspace-oe11\archi-erp\.sonarlint\pl.txt, sonar.oe.aliases=*******************************
sonar.oe.lint.databases=****************************************}
  moduleKey: null
  inputFiles: [
    file:/D:/Openedge/workspace-oe11/archi-erp/Src/copylig_ph.w (UTF-8) [oe]
  ]
]





```

**Comment by gquerret** [comment]
Since 2.25, encoding is now provided directly by Developer Studio, so you should check that this specific file has the right encoding. Right-click on the file, then properties:
![image](https://github.com/Riverside-Software/sonar-openedge/assets/6498723/14474fed-c80f-4709-b324-98ba12f4768f)

The error with Optional.isEmpty will be fixed (Java 8 again...)

**Comment by clement-brodu** [comment]
Encoding of my file is OK : 

![image](https://github.com/Riverside-Software/sonar-openedge/assets/37274615/777e1f46-dcfc-492b-9f86-534766ce3acb)

But, includes files are outside of the workspace (but in my propath).

Project : `D:\workspace-oe11\project1\Src\myProg.w`
Propath : `D:\workspace-oe11\project1\Src,S:\Commun\Includes`
the include file : `S:\Commun\Includes\toto.i`

```
/*------------------------------------------------------------------------
    File        : toto.p

  ----------------------------------------------------------------------*/
BLOCK-LEVEL ON ERROR UNDO, THROW.
*************************  Main Block  *************************** */
{toto.i}

MESSAGE "Hello"  VIEW-AS ALERT-BOX INFORMATION BUTTONS OK IN WINDOW CURRENT-WINDOW.
```

**Comment by gquerret** [comment]
Issue has been fixed. CABL 2.25.1 will be released later today, along with the new versions of the Eclipse plugin.
