### ISSUE TITLE
Detect FOR FIRST/LAST with BY

### ISSUE THREAD

**Issue by movedoa** [Riverside-Software/sonar-openedge#1114]
FOR FIRST/LAST with a BY does not honor the BY statement, the records don't get sorted.
There should be a rule to detect this, FOR FIRST/LAST should never be used in combination with BY.
Always use FOR EACH and LEAVE.

See:
[https://documentation.progress.com/output/ua/OpenEdge_latest/pdsoe/PLUGINS_ROOT/com.openedge.pdt.langref.help/rfi1424919813003.html](https://documentation.progress.com/output/ua/OpenEdge_latest/pdsoe/PLUGINS_ROOT/com.openedge.pdt.langref.help/rfi1424919813003.html)

```
Uses the criteria in the record-phrase to find the first record in the table that meets that criteria. The AVM finds the first record before any sorting.
The following statement displays Customer 1 (CustNum is the primary index of the Customer table), not the Customer with the lowest CreditLimit:
...
```

**Comment by gquerret** [comment]
Makes sense, and very quick development. Added to the backlog.

**Comment by gquerret** [comment]
Will be limited to FOR statement with a single buffer in the query. Running the rule on various codebases showed FP with this kind of query (on sp2k):
```
for each customer, first invoice of customer [break] by invoicedate
```
