### ISSUE TITLE
'project-mate-abl-sources/xyz/abc.p' cannot be converted from IDE to server path for project binding: 'project-abl-sources-dev' / 'project-abl-sources' / 'target/src'

### ISSUE THREAD

**Issue by lievencardoen** [Riverside-Software/sonar-openedge#1119]
Hi,

I'm getting this error/warning in my sonar output in Development Studio.

Any idea why?

Thx, Lieven

**Comment by gquerret** [comment]
What is the SonarLint version ? And OpenEdge version ?

**Comment by gquerret** [comment]
And is that the exact message ? I can't find any reference to this string (or substring) in SonarLint source code

**Comment by lievencardoen** [comment]
Hi Gilles,

OE 12.8.0
SonarLint 9.3.3002

The exact message is:
...
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.VariableReadButNotAssigned | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.WhereCanDo | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.WrongAssignWhen | time=0 ms
Found 0 issue(s)
Done in 435 ms
**'<source>' cannot be converted from IDE to server path for project binding: 'x' / 'y' / 'z'**

**Comment by gquerret** [comment]
That's a debug message from SonarLint core ; it just means that the file which was analyzed is not found on the server (in order to look for closed issues for example). You can ignore the message, but if you don't want to see it then you should remove "Verbose output" from SonarLint console.
