### ISSUE TITLE
LIKE input parameters: use of default buffer

### ISSUE THREAD

**Issue by dominickdm** [Riverside-Software/sonar-openedge#1127]
Hello,

When an input parameter of a method is defined as ‘LIKE’, it leads to a ‘usage of default buffer’ issue.

![image](https://github.com/Riverside-Software/sonar-openedge/assets/40289256/fe7f42ad-13d1-4f35-89ed-392bb6aa9c32)
![image](https://github.com/Riverside-Software/sonar-openedge/assets/40289256/b5e3d5f0-3c20-4504-b45d-55dfc80723eb)

**Comment by gquerret** [comment]
Fixed in develop
