### ISSUE TITLE
Unable to suppress unused output parameter of method

### ISSUE THREAD

**Issue by stefandrissen** [Riverside-Software/sonar-openedge#1129]
````
CLASS foo:

   METHOD VOID bar (
      {&_proparse_ prolint-nowarn(varusage)}
      isuppress_1 AS INTEGER,
      {&_proparse_ prolint-nowarn(varusage)}
      OUTPUT icannot_suppress AS INTEGER,
      {&_proparse_ prolint-nowarn(varusage)}
      isuppress_2 AS INTEGER
   ):

      // something

   END METHOD.

END CLASS.
````
![image](https://github.com/Riverside-Software/sonar-openedge/assets/5297464/a1c61a0a-0b2f-48da-a0ed-d24c081d80e6)

**Comment by gquerret** [comment]
You can insert the preprocessor reference before `icannot_suppress`. Before you say it, it's not beautiful, but it works. I'll add a fix so that it will be possible to have the preprocessor reference before `output` keyword.

**Comment by gquerret** [comment]
Fixed in develop
