### ISSUE TITLE
Error in SonarLint accessing TEMP-TABLE in base class

### ISSUE THREAD

**Issue by dominickdm** [Riverside-Software/sonar-openedge#1130]
It seems that the issue reported in #819 is failing again

![image](https://github.com/Riverside-Software/sonar-openedge/assets/40289256/e72de4ae-8311-4afb-98a3-0c100f213ce7)

![image](https://github.com/Riverside-Software/sonar-openedge/assets/40289256/110c85ef-aaf8-424d-b1a1-ef141b91a6a6)

I got a parse error in the console:
![image](https://github.com/Riverside-Software/sonar-openedge/assets/40289256/f607bc69-c10e-48d4-abdc-7aecebee41a9)

**Comment by gquerret** [comment]
What version of SonarLint plugin and OE plugin in SonarQube ?

**Comment by dominickdm** [comment]
OpenEdge - 2.26.0
Riverside Rules - 2.26.1
SonarLint for Eclipse - 7.6.2312

**Comment by dominickdm** [comment]
It seems that updating my plugin version is necessary. 
According to issue #1088, the resolution is in version 9.1.2906.
