### ISSUE TITLE
Ascending function detected

### ISSUE THREAD

**Issue by ccecvb** [Riverside-Software/sonar-openedge#1132]
This came up during our 12.2 to 12.8 migration

Before 12.3 OpenEdge wrongfully interpreted ascending(x) as asc(x), see https://community.progress.com/s/article/Compiler-interprets-ASCENDING-as-ASC-function.

We found code where the ASC function had been expanded incorrectly to ASCENDING.
OpenEdge 12.2 did not have any issues with that.

Maybe this could be part of a "code migration rule set", it could help fixing this kind of issue before the actual migration.

**Comment by gquerret** [comment]
Yes, easy to implement, and makes sense to have issues reported in this case.

**Comment by gquerret** [comment]
Merged in develop branch
