### ISSUE TITLE
Running SonarLint - ABL in Visual Studio Code shows different number of issues every time I run without changing the code

### ISSUE THREAD

**Issue by ionpaseabroadridge** [Riverside-Software/sonar-openedge#1143]
I installed the latest SonarLint ABL extension in Visual Studio Code. It connects properly to SonarQube, and binds to the project in SonarQube properly. Everything seems to be running. I opened a file in the VSC and it shows a number of problems based on the CABL rules that we have activated in SonarQube. If I make a change that has no effect like (add a space at the end of a line and save) the number of problems being reported is different than before. If I delete the space and save again, the number of problems is different again (different than the two situations before). This issue is not new. It was there with the original SonarLint and the workaround of generating the cabl.json and placing it in <project>\.vscode

**Comment by gquerret** [comment]
Just to keep you posted about this issue, this issue has been reproduced in a different environment. This is being worked on.

**Comment by gquerret** [comment]
Issue found, fix will be available in sonar-openedge 2.29.
