### ISSUE TITLE
DF Import - ODBC

### ISSUE THREAD

**Issue by movedoa** [Riverside-Software/sonar-openedge#12]
The Type "ODBC" doesn't work with the df import (for field and database)

mismatched input 'ODBC' expecting {'MSS', 'ORACLE'}
mismatched input 'ODBC' expecting {'MSS', 'ORACLE', 'SQL'}

Also the PROGRESS-RECID can be negative in this case which also produces an error:
[sonar:sonar] Syntax error <unknown>:13228:14 mismatched input '-7' expecting NUMBER

**Comment by jakejustus** [comment]
Fixed in dev, will be included in next version
