### ISSUE TITLE
Unused variables - FP on CATCH

### ISSUE THREAD

**Issue by movedoa** [Riverside-Software/sonar-openedge#121]
The rule should ignore input variables in catch, since they are mandatory

![grafik](https://cloud.githubusercontent.com/assets/13309951/20703293/80327b0e-b61b-11e6-82f6-ca684c6aac1f.png)

**Comment by gquerret** [comment]
This will go in a different rule, just as in the Java ruleset. So the entire rule can be skipped or kept depending on your requirements.
So the main rule won't report unused variables from the exception instance, but a second rule will.

**Comment by movedoa** [comment]
Is this already implemented?
I see the "Log or rethrow exception" rule and i don't have it active, but the unused parameter rule still flags this:

![grafik](https://cloud.githubusercontent.com/assets/13309951/21926256/475f5d86-d981-11e6-9efa-23507c71485b.png)

**Comment by gquerret** [comment]
Unused parameter shouldn't be reported here, and there's even a test case available for this, but that doesn't seem to be enough.

**Comment by gquerret** [comment]
Reproduced, the test case was on procedures with catch blocks, and FP happens only on classes...

**Comment by gquerret** [comment]
Fixed in master
