### ISSUE TITLE
Integrate proparse changes for TENANT-ID function from Consultingwerk/proparse

### ISSUE THREAD

**Issue by mikefechner** [Riverside-Software/sonar-openedge#122]
SonarSource proparse rule fails with TENANT-ID ("dbname") function. 

Just like our proparse :-) I've asked Marian to fix that. 

https://github.com/consultingwerk/proparse/pull/5

**Comment by gquerret** [comment]
Will be done !

**Comment by gquerret** [comment]
Missing keywords for now:
* SET-EFFECTIVE-TENANT
* GET-EFFECTIVE-TENANT-NAME
* GET-EFFECTIVE-TENANT-ID
* BUFFER-TENANT-ID
* BUFFER-TENANT-NAME
* IS-MULTI-TENANT
* IS-DB-MULTI-TENANT
* BUFFER-GROUP-ID
* BUFFER-GROUP-NAME
* TENANT-WHERE
* SKIP-GROUP-DUPLICATES

Missing syntax change in:
* CURRENT-VALUE
* DYNAMIC-CURRENT-VALUE
* CREATE [FOR TENANT]
* BUFFER-CREATE

**Comment by gquerret** [comment]
Merged in master
