### ISSUE TITLE
Error with Matching keyword in source code Rule

### ISSUE THREAD

**Issue by movedoa** [Riverside-Software/sonar-openedge#13]
I created a few rules with the "Matching keyword in source code" template. (For all the OS-* Keyowords)
But i get errors during the analysis.

[sonar:sonar] Unable to find token number for keyword OS-COPY
[sonar:sonar] Unable to find token number for keyword OS-APPEND
[sonar:sonar] Unable to find token number for keyword OS-DELETE
[sonar:sonar] Unable to find token number for keyword OS-CREATE-DIR
[sonar:sonar] Unable to find token number for keyword OS-RENAME
[sonar:sonar] Unable to find token number for keyword OS-COMMAND

**Comment by jakejustus** [comment]
The wrong function was used to retrieve the keyword list ; in the meantime, you can specify OSCOPY, OSAPPEND, ... (i.e. no dash in keywords)

![2016-04-14 15_47_15-clipboard](https://cloud.githubusercontent.com/assets/6498730/14530209/3436e41e-0258-11e6-919e-787ca2d111c7.png)

**Comment by jakejustus** [comment]
Fixed
