### ISSUE TITLE
Issue with sonar.oe.dlc.propath

### ISSUE THREAD

**Issue by gquerret** [Riverside-Software/sonar-openedge#138]
On Windows, it seems that some files still can't be found (such as src/web/method/cgidefs.i)
To be investigated, but could be related to forward slashes ???

**Comment by cverbiest** [comment]
I have the same issue

some observations
* if there is an entry in the propath that does not exist, that entry and all the following entries are ignored, maybe that should be logged as a separate issue
* I have not yet found a syntax that allows for a drive letter, tried c:/progress/oe116 c:\progress\oe116 and c:\\progress\\oe116

I worked around the issue by creating a symbolic link dlc that points to the progress installation , example in proenv assuming PROJECT_DIR points to the project root

    cd %PROJECT_DIR%
    mklink /j /d dlc %DLC%

**Comment by gquerret** [comment]
First point will be tested, thanks for having reported.
Second point: property `sonar.oe.propath.dlc` can be set to true to append the standard DLC directories to the propath

**Comment by gquerret** [comment]
@cverbiest I'm not able to reproduce your first issue (wrong path in propath hides the following entries)
Are you sure that was your exact problem ?

And were you able to use sonar.oe.propath.dlc successfully ?

**Comment by gquerret** [comment]
Not reproduced anymore
