### ISSUE TITLE
[Request] Provide an eclipse plugin

### ISSUE THREAD

**Issue by movedoa** [Riverside-Software/sonar-openedge#143]
Basically SonarLint :)

**Comment by gquerret** [comment]
I'll keep it open for future reference, but that's something PSC would have to provide as the source code of the Eclipse plug-in is not available. But please submit an idea on communities.progress.com, and talk to product managers next time you can see them !

**Comment by movedoa** [comment]
A bit unrelated but should we post rule/feature suggestions here or still in confluence?

**Comment by gquerret** [comment]
Please submit them on GitHub with the 'enhancement' tag, that will be easier to triage them.

**Comment by mikefechner** [comment]
H&H is maintaining their own commercial Eclipse plugin on top of Progress Developer Studio.

https://www.hh-berlin.de/oedt/

Which parts of the Progress Eclipse plugin do you need access to?

- Builder
- Editor
- Parser

They have their own implementations of all. Plus I guess their product management might be easier to deal with.

**Comment by gquerret** [comment]
For your information, a first version of SonarLint for command line should be available by the end of the week. This version can be really useful for pre-commit hooks.
Work on the Eclipse plugin will start mid-March.

**Comment by movedoa** [comment]
great news :)

**Comment by gquerret** [comment]
SonarLint for command line: https://github.com/Riverside-Software/sonar-openedge/releases/tag/V1.9.8

**Comment by gquerret** [comment]
SonarLint for Eclipse will be available in a few days / weeks, depending on feedback of beta testers.

**Comment by mikefechner** [comment]
Beta testers say ... "release it, release it, release it!!!!"

**Comment by movedoa** [comment]
Imho it is stable enough for a public beta :)

**Comment by gquerret** [comment]
Just a couple more changes in the engine, and the entire stack will be released !
