### ISSUE TITLE
Error while analysing listing with 1.8.0

### ISSUE THREAD

**Issue by movedoa** [Riverside-Software/sonar-openedge#15]
Same Projekt worked with 1.7.4
Seems to happen with every Enum class

Here is the -v output:

`[sonar:sonar] Import listing for Common/Enum/CustomControls/moveToolTipPosition.cls
[sonar:sonar] Unknown block type ENUM
[sonar:sonar] Analysis report generated in C:\Buildtools\Jenkins\workspace\Sonar_Runner\Sonar_Temp\batch-report
[sonar:sonar] Couldn't delete lock file: C:\Buildtools\Jenkins\workspace\Sonar_Runner\.sonar_lock java.nio.file.NoSuchFileException: C:\Buildtools\Jenkins\workspace\Sonar_Runner\.sonar_lock
[sonar:sonar] 	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:79)
[sonar:sonar] 	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
[sonar:sonar] 	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
[sonar:sonar] 	at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:269)
[sonar:sonar] 	at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
[sonar:sonar] 	at java.nio.file.Files.delete(Files.java:1126)
[sonar:sonar] 	at org.sonar.home.cache.DirectoryLock.unlock(DirectoryLock.java:98)
[sonar:sonar] 	at org.sonar.batch.scan.ProjectLock.stop(ProjectLock.java:57)
[sonar:sonar] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[sonar:sonar] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[sonar:sonar] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[sonar:sonar] 	at java.lang.reflect.Method.invoke(Method.java:497)
[sonar:sonar] 	at org.picocontainer.lifecycle.ReflectionLifecycleStrategy.invokeMethod(ReflectionLifecycleStrategy.java:110)
[sonar:sonar] 	at org.picocontainer.lifecycle.ReflectionLifecycleStrategy.stop(ReflectionLifecycleStrategy.java:96)
[sonar:sonar] 	at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.stop(AbstractInjectionFactory.java:88)
[sonar:sonar] 	at org.picocontainer.behaviors.AbstractBehavior.stop(AbstractBehavior.java:179)
[sonar:sonar] 	at org.picocontainer.behaviors.Stored$RealComponentLifecycle.stop(Stored.java:141)
[sonar:sonar] 	at org.picocontainer.behaviors.Stored.stop(Stored.java:118)
[sonar:sonar] 	at org.picocontainer.DefaultPicoContainer.stopAdapters(DefaultPicoContainer.java:1048)
[sonar:sonar] 	at org.picocontainer.DefaultPicoContainer.stop(DefaultPicoContainer.java:803)
[sonar:sonar] 	at org.sonar.core.platform.ComponentContainer.stopComponents(ComponentContainer.java:166)
[sonar:sonar] 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:123)
[sonar:sonar] 	at org.sonar.batch.task.ScanTask.execute(ScanTask.java:55)
[sonar:sonar] 	at org.sonar.batch.task.TaskContainer.doAfterStart(TaskContainer.java:86)
[sonar:sonar] 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
[sonar:sonar] 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:120)
[sonar:sonar] 	at org.sonar.batch.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:122)
[sonar:sonar] 	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:119)
[sonar:sonar] 	at org.sonar.runner.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:67)
[sonar:sonar] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[sonar:sonar] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[sonar:sonar] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[sonar:sonar] 	at java.lang.reflect.Method.invoke(Method.java:497)
[sonar:sonar] 	at org.sonar.runner.impl.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:61)
[sonar:sonar] 	at com.sun.proxy.$Proxy0.execute(Unknown Source)
[sonar:sonar] 	at org.sonar.runner.api.EmbeddedRunner.doExecute(EmbeddedRunner.java:274)
[sonar:sonar] 	at org.sonar.runner.api.EmbeddedRunner.runAnalysis(EmbeddedRunner.java:165)
[sonar:sonar] 	at org.sonar.runner.api.EmbeddedRunner.runAnalysis(EmbeddedRunner.java:152)
[sonar:sonar] 	at org.sonarsource.scanner.ant.SonarQubeTask.launchAnalysis(SonarQubeTask.java:72)
[sonar:sonar] 	at org.sonarsource.scanner.ant.SonarQubeTask.execute(SonarQubeTask.java:55)
[sonar:sonar] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
[sonar:sonar] 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[sonar:sonar] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[sonar:sonar] 	at java.lang.reflect.Method.invoke(Method.java:497)
[sonar:sonar] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[sonar:sonar] 	at org.apache.tools.ant.Task.perform(Task.java:348)
[sonar:sonar] 	at org.apache.tools.ant.Target.execute(Target.java:435)
[sonar:sonar] 	at org.apache.tools.ant.Target.performTasks(Target.java:456)
[sonar:sonar] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
[sonar:sonar] 	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
[sonar:sonar] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
[sonar:sonar] 	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:440)
[sonar:sonar] 	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
[sonar:sonar] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
[sonar:sonar] 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[sonar:sonar] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[sonar:sonar] 	at java.lang.reflect.Method.invoke(Method.java:497)
[sonar:sonar] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[sonar:sonar] 	at org.apache.tools.ant.Task.perform(Task.java:348)
[sonar:sonar] 	at org.apache.tools.ant.Target.execute(Target.java:435)
[sonar:sonar] 	at org.apache.tools.ant.Target.performTasks(Target.java:456)
[sonar:sonar] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
[sonar:sonar] 	at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
[sonar:sonar] 	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
[sonar:sonar] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
[sonar:sonar] 	at org.apache.tools.ant.Main.runBuild(Main.java:851)
[sonar:sonar] 	at org.apache.tools.ant.Main.startAnt(Main.java:235)
[sonar:sonar] 	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
[sonar:sonar] 	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)`

**Comment by jakejustus** [comment]
Crap :-(
You're absolutely right, there are no enum test cases (because the parser has not been updated yet to support them), leading to an unwanted side effect in the listing parser. I'll do a quick update this afternoon.

**Comment by jakejustus** [comment]
Fixed in 1.8.1 (available in the releases page). And thanks for reporting issues !
