### ISSUE TITLE
GlobalDefine performance issue

### ISSUE THREAD

**Issue by gquerret** [Riverside-Software/sonar-openedge#154]
Checked on SC codebase - GlobalDefine rule with 4 excluded files, on 10k .p files, takes 6 hours, 100x more than any other rule.

**Comment by mikefechner** [comment]
Hi Gilles, in case the SC codebase is our SmartComponent Library, the runtime of the rule was 160.000 msec. That's under 3 minutes. The whole scanning of our code base takes ~ 10 minutes. So this is relevant - but far from 6 hours.

**Comment by gquerret** [comment]
@mikefechner It's not the SmartComponent library.
In this issue, the GlobalDefine rule takes more than 90% of the total time. There's probably an implementation issue, which is clearly visible in this case.

**Comment by gquerret** [comment]
Fixed in master
