### ISSUE TITLE
Rule idea : error handling directive

### ISSUE THREAD

**Issue by gquerret** [Riverside-Software/sonar-openedge#155]
In all compile unit without `BLOCK-LEVEL ON ERROR UNDO, THROW` (so those with no error handling directive or ROUTINE-LEVEL ON ERROR UNDO, THROW), alert all `FOR` or `REPEAT` loops with no explicit error handling directive.

**Comment by gquerret** [comment]
Adding `DO TRANSACTION` loops (per documentation)

**Comment by gquerret** [comment]
@mikefechner https://ci.rssw.eu/job/sonar-openedge-rules/job/PR-30/

**Comment by mikefechner** [comment]
Works as expected! :-) Merci!

**Comment by gquerret** [comment]
Merged in master
