### ISSUE TITLE
All "whole index" and "sort access" rules stopped working in 1.8

### ISSUE THREAD

**Issue by movedoa** [Riverside-Software/sonar-openedge#16]
All rules with whole index and sort access stopped working with 1.8 (the new temp-table rules won't work either).

The analysis runs without errors but i have 0 issues for all these rules (had a few hundred with 1.7)

**Comment by jakejustus** [comment]
Could you confirm if the rules are activated in the profile used by the project :
![2016-04-21 16_41_59-clipboard](https://cloud.githubusercontent.com/assets/6498730/14713083/fe8984c4-07df-11e6-8627-67e5d0dbc424.png)
Then :
![2016-04-21 16_42_48-clipboard](https://cloud.githubusercontent.com/assets/6498730/14713119/1de2e4c8-07e0-11e6-9208-d41509ed5a8e.png)

**Comment by movedoa** [comment]
Yes they are ative

![unbenannt](https://cloud.githubusercontent.com/assets/13309951/14713370/2a3996a8-07e1-11e6-8499-bd786175479a.png)

**Comment by jakejustus** [comment]
In the log file of your analysis, do you have those lines :
![2016-04-21 16_55_23-clipboard](https://cloud.githubusercontent.com/assets/6498730/14713570/df865136-07e1-11e6-952e-eb929a2e3220.png)
And is it only for XREF rules ? Are you able to execute the parser rules ?
If you migrated from 1.7.x, you'll have a new Quality profile, which may or may not be the default one, and it might be confusing which one is taken for existing projects and new ones.
Last point : do you have a permanent ID on this server ?

**Comment by movedoa** [comment]
yes i have these lines in the log 
```
[sonar:sonar] Rule eu.rssw.xref.checks.TempTableWholeIndexAnalyzer | time=54251 ms
[sonar:sonar] Rule eu.rssw.xref.checks.SortAccessAnalyzer | time=40642 ms
[sonar:sonar] Rule eu.rssw.xref.checks.WholeIndexAnalyzer | time=39280 ms
[sonar:sonar] Rule eu.rssw.xref.checks.SortAccessWholeIndexAnalyzer | time=39789 ms
[sonar:sonar] Rule eu.rssw.xref.checks.TempTableSortAccessWholeIndexAnalyzer | time=40010 ms

```

I created a new custom quality profile (and made it default) and the analysis says in the output that it uses this profile.

I will try to create a new project with a new name/key just to be sure there in so confusion from sonar (i will post here when i have the results)

I have no permanent ID on my server.

**Comment by movedoa** [comment]
Ok i created a new project, same problem

**Comment by jakejustus** [comment]
Could you verify the status of the background task for the project ? Administration menu => background task
And also confirm if the parser rules (such as "Long strings" for example) still report issues ?

**Comment by movedoa** [comment]
The background Task has the status success

Other rules still report issues
![unbenannt](https://cloud.githubusercontent.com/assets/13309951/14715634/c51b37f0-07e9-11e6-83b3-c1dfacf084a9.PNG)

**Comment by jakejustus** [comment]
I think I've found the issue, will keep you posted

**Comment by jakejustus** [comment]
Could you try those snapshots ?
* http://pugfr.riverside-software.fr/riverside-rules-plugin-1.0.1-SNAPSHOT.jar
* http://pugfr.riverside-software.fr/sonar-openedge-db-plugin-1.8.2-SNAPSHOT.jar
* http://pugfr.riverside-software.fr/sonar-openedge-plugin-1.8.2-SNAPSHOT.jar

**Comment by movedoa** [comment]
The problem is fixed in this version, thx

**Comment by jakejustus** [comment]
Thanks for your report, 1.8.2 final will be available during next week
