### ISSUE TITLE
Unused variables - FP on .Net event methods

### ISSUE THREAD

**Issue by movedoa** [Riverside-Software/sonar-openedge#162]
Issue #62 seems to be only partially fixed, it still happens but not always.
I don't see any difference between the events where it works and the ones were it doesn't.

![grafik](https://cloud.githubusercontent.com/assets/13309951/21926563/8df6e470-d982-11e6-9efb-ddf0777c1870.png)

**Comment by gquerret** [comment]
Fixed in master
