### ISSUE TITLE
Backwards-compatibility VALID-HANDLE vs. VALID-OBJECT

### ISSUE THREAD

**Issue by mikefechner** [Riverside-Software/sonar-openedge#163]
Rumors say that in 11.7 VALID-OBJECT and VALID-HANDLE will be synonyms for each other. Cool.

But this will break backwards-compatibility with 11.6 and before.

So a rule might report is VALID-OBJECT is used on a HANDLE variable.

**Comment by gquerret** [comment]
Is there a mention of that in the ESAP forum ?

**Comment by gquerret** [comment]
@mikefechner Is this rumor true ?

**Comment by mikefechner** [comment]
Yes

**Comment by gquerret** [comment]
With 11.6 being now quite old and 11.7 being the stable version in the 11.x cyle, I'll flag this issue as Won't fix as it won't bring enough value.
