### ISSUE TITLE
The "Replace public variable ValidateDateInOpenPeriod by property" doesn't work.

### ISSUE THREAD

**Issue by WayneHanson** [Riverside-Software/sonar-openedge#168]
This rule seems to be reporting an error for lines which are actually still correct.

See this example.

![image](https://cloud.githubusercontent.com/assets/17933182/22075914/cbff87a0-dda5-11e6-927f-d4b86c878fa8.png)

**Comment by gquerret** [comment]
Could you include version number of the rules plugin ?

**Comment by WayneHanson** [comment]
It's 1.9.3

**Comment by gquerret** [comment]
Time to upgrade ;-)
