### ISSUE TITLE
Matching keyword in source code - false positives with properties

### ISSUE THREAD

**Issue by movedoa** [Riverside-Software/sonar-openedge#17]
I created rules for YES/NO since we want to be consistent in our code and should only use TRUE/FALSE.

But now i get many false positives for properties that are named yes/no.
It seems the parser thinks these are keywords, which has big error potential in my eyes.

.Net and the Infragistics Controls both have such properties.

For Example:
System.ComponentModel.BrowsableAttribute:No

**Comment by jakejustus** [comment]
It could be possible to have an option to skip issues on widget references as this is where most of this kind of issue will happen (with .Net classes and ActiveX)

**Comment by movedoa** [comment]
I would expect to find only real keywords with this rule not variables or anything else.
I don't really see the need for an option here this should be default.

**Comment by jakejustus** [comment]
Fixed in dev
