### ISSUE TITLE
[Rule Idea] Deprecate classes

### ISSUE THREAD

**Issue by movedoa** [Riverside-Software/sonar-openedge#173]
A rule to deprecate classes (.Net and OE) would be very useful.
We have several instances where we inherit some base class and extend it with custom features.
So the base class should not be used anywhere else.

It should work like the "Matching keyword in sourcecode" rule and it should be possible to suppress the issue with an annotation.

The rule should always take the full namespace since classnames are not unique.

**Comment by gquerret** [comment]
Deprecation will be implemented in #164 
I'm just wondering how inheritance should be handled...
