### ISSUE TITLE
Problem with the "Backslash" rule.

### ISSUE THREAD

**Issue by WayneHanson** [Riverside-Software/sonar-openedge#174]
The backslash rule appears to be incorrectly  interpreting certain combinations of characters as backslashes.

For example, the following string does not contain backslashes but thinks that there are multiple occurrences of them.

![image](https://cloud.githubusercontent.com/assets/17933182/22328846/329e5aac-e3b6-11e6-928c-080dff81c59e.png)

**Comment by gquerret** [comment]
Not a good reason for this issue, but the preprocessor expands {&FILE-NAME} with the full path, which then contains backslash when analysis is executed on Windows. 
Refactoring is currently in progress at the lexer level, which will give access to the unpreprocessed string ; this rule should test this value. 
If necessary, I can introduce a workaround in the mean time, as the new lexer won't be available before two months at best.

**Comment by jurjendijkstra-vma** [comment]
Yeah this is a false positive that happens a lot when you have used the Progress Appbuilder, in fact it is in almost every sourcefile! The code fragment with the statement message "&file-name} should only be run persistent." is generated by Appbuilder and is found in a section that begins with the line &ANALYZE-SUSPEND _PROCEDURE-SETTINGS and ends with the line &ANALYZE-RESUME _END-PROCEDURE-SETTINGS, the Appbuilder shows the section as read-only so it is not the developers fault. 

Would it be an idea to suppress the backslash warning for this specific statement? 
Or even more generic: to suppress backslash warnings from Appbuilder sections that are read-only, e.q. that are marked with &ANALYZE-SUSPEND without _UIB-CODE-BLOCK ?

**Comment by gquerret** [comment]
@jurjendijkstra-vma The second solution is to my mind the right one, but that shouldn't be limited to backslash warnings only.

**Comment by gquerret** [comment]
Fixed in master
