### ISSUE TITLE
FP unused variable in procedure file

### ISSUE THREAD

**Issue by mikefechner** [Riverside-Software/sonar-openedge#178]
![image](https://cloud.githubusercontent.com/assets/13220627/22402492/64c5fd2e-e5f9-11e6-9600-7d89b338bbf3.png)

**Comment by gquerret** [comment]
Don't you also have issue "Log or rethrow oLoader"  at the same line ?

**Comment by mikefechner** [comment]
> Don't you also have issue "Log or rethrow oLoader" at the same line ?

No. Just activated that rule.

**Comment by gquerret** [comment]
Fixed as part of PR #184 (yes, that was related)
