### ISSUE TITLE
Proparse error - CREATE TEMP-TABLE THIS-OBJECT:hVar

### ISSUE THREAD

**Issue by movedoa** [Riverside-Software/sonar-openedge#18]
I hava a class with a private handle variable.
DEFINE PRIVATE VARIABLE hTempTableAS HANDLE NO-UNDO.

And in a method i create a TEMP-TABLE like this:

CREATE TEMP-TABLE THIS-OBJECT:hTempTable.

This created the following Error:
"unexpected token: THIS-OBJECT"

**Comment by jakejustus** [comment]
Fixed in dev
