### ISSUE TITLE
FP on variable never read - public property

### ISSUE THREAD

**Issue by mikefechner** [Riverside-Software/sonar-openedge#180]
![image](https://cloud.githubusercontent.com/assets/13220627/22406341/069ad52c-e652-11e6-90ff-5385004bb738.png)

**Comment by gquerret** [comment]
Issue is that THIS-OBJECT is not correctly resolved. PR #183 is likely to be merged in master, and will fix this issue.

**Comment by gquerret** [comment]
Pretty interesting issue, a couple problems were fixed at the same time. That will go in master by the end of the week.

**Comment by gquerret** [comment]
Merged in master
