### ISSUE TITLE
Proparse error - expecting LEFTPAREN, found '.' -> DYNAMIC-NEW lcProgName().

### ISSUE THREAD

**Issue by movedoa** [Riverside-Software/sonar-openedge#19]
The following code creates the proparse error "expecting LEFTPAREN, found '.'  "

loVariable = DYNAMIC-NEW lcProgName().

**Comment by jakejustus** [comment]
Do you have a bit more context, I'm currently unable to reproduce the issue.

**Comment by movedoa** [comment]
I have sent you an email with an example.

**Comment by jakejustus** [comment]
Reproduced, that only happens when the dynamic-new is inside a method (not from a procedure).

**Comment by jakejustus** [comment]
Fixed in dev
