### ISSUE TITLE
Unused variables - FP on .Net event methods

### ISSUE THREAD

**Issue by movedoa** [Riverside-Software/sonar-openedge#193]
See https://github.com/Riverside-Software/sonar-openedge/issues/162

Error still happens with 1.9.8

![grafik](https://cloud.githubusercontent.com/assets/13309951/23353667/eca63070-fccd-11e6-9f15-2760afcd87a2.png)

**Comment by gquerret** [comment]
My heuristic is proven wrong !
Isn't the second argument supposed to extend something like System.*EventArgs ?

**Comment by movedoa** [comment]
Yes you are right, i didn't see that this uses System.Object.
I guess it is technically possible to use System.Object.
This is the only event in my code that does this and i can fix it to use EventArgs.
Imho you can close this bug.

**Comment by gquerret** [comment]
Excellent, thanks !
