### ISSUE TITLE
FOREIGN-MAXIMUM should be NUMBER

### ISSUE THREAD

**Issue by laumingis** [Riverside-Software/sonar-openedge#194]
FOREIGN-MAXIMUM should be defined as NUMBER in Dump File Grammar (now it is QUOTED_STRING). 

An excerpt from our Oracle DataService df looks like this:
```
ADD FIELD "FIELD_NAME" OF "TABLE_NAME" AS character
  FORMAT "x(3)"
  INITIAL ?
  POSITION 2
  LENGTH 3
  ORDER 1160
  MANDATORY
  CASE-SENSITIVE
  FOREIGN-POS 16
  FOREIGN-CODE 1
  FOREIGN-NAME "FIELD_NAME"
  FOREIGN-TYPE "VARCHAR2"
  FOREIGN-MAXIMUM 3
  FIELD-MISC13 3
  FIELD-MISC14 1
```

File to be fixed: sonar-openedge/database-parser/src/main/antlr4/eu/rssw/antlr/database/DumpFileGrammar.g4

**Comment by gquerret** [comment]
You're right, `FOREIGN-MAXIMUM` is defined as an integer in the prodict procedures.
We'll verify there's no other error in FOREIGN-* fields and include this modification

**Comment by gquerret** [comment]
Changed `FOREIGN-SCALE`,  `FOREIGN-SPACING`, `FOREIGN-XPOS`, `FOREIGN-ALLOCATED` and `FOREIGN-MAXIMUM` to NUMBER

**Comment by gquerret** [comment]
Merged in master (one month ago)
