### ISSUE TITLE
DF parser does not understand ADD CONSTRAINT PRIMARY

### ISSUE THREAD

**Issue by laumingis** [Riverside-Software/sonar-openedge#195]
DF parser throws error at Oracle DataServer dump:
```
ADD CONSTRAINT "CONSTRAINT_PK" ON "TABLE_NAME"
  PRIMARY
  ACTIVE
  CONSTRAINT-INDEX "CONSTRAINT_PK"
```
`ERROR: Syntax error <unknown>:1023:4 no viable alternative at input 'ADD CONSTRAINT'`

It looks like PRIMARY key is not understood there (other constraints are parsed properly).

**Comment by gquerret** [comment]
Weird, `ADD CONSTRAINT` is not yet included in the grammar.
We'll add this syntax as soon as possible, but in the mean time, could you remove those statements from the DF file ?

**Comment by gquerret** [comment]
Fixed in master
