### ISSUE TITLE
SonarQube Filter on OpenEdgeDB doesn't show DB rules

### ISSUE THREAD

**Issue by cverbiest** [Riverside-Software/sonar-openedge#197]
I'm trying to create a quality profile for databases but I only see rules that do not seem relevant for databases such as unit test coverage and comments

![image](https://cloud.githubusercontent.com/assets/1312691/23958867/ba079694-09a3-11e7-9557-94b4bbde1577.png)

**Comment by gquerret** [comment]
You should use OpenEdge as the language, not OpenEdgeDB. That's an artifact coming from the early releases, it will be cleaned up.

**Comment by gquerret** [comment]
Fixed in master branch.
