### ISSUE TITLE
Enhancement: Add exclude pattern list to default widget name rule

### ISSUE THREAD

**Issue by cverbiest** [Riverside-Software/sonar-openedge#198]
The default widget name rule does not have an exclude list.
Some "default" names are meaningful to us e.g. TAB-TEXT-1, TAB-TEXT-2, TAB-TEXT-3 are the texts on the first, second and third tab .

It would be nice if there was a parameter in this rule to exclude certain patterns

**Comment by gquerret** [comment]
A list of regexp could be added as a parameter

**Comment by gquerret** [comment]
Fixed in master
