### ISSUE TITLE
Code duplication check requires configurable exceptions

### ISSUE THREAD

**Issue by mikefechner** [Riverside-Software/sonar-openedge#20]
Especially for generated code the duplication check is problematic. I'd suggest to implement exceptions to classes/methods that are checked for duplications:

Based on a name pattern for classes and methods:

e.g. Class name: *Form.cls
MethodName: InitializeComponent

There should be multiple combinations of the class and method filter.

**Comment by jakejustus** [comment]
Wouldn't annotated methods be easier for maintenance ? Something like @Generated on the outer scope. That would also avoid reporting issue on such code, as issues would be meaningless.

**Comment by mikefechner** [comment]
Sure

Outlook for Android<https://aka.ms/ghei36> herunterladen



On Thu, May 26, 2016 at 12:44 PM -0700, "Gilles QUERRET" <notifications@github.com<mailto:notifications@github.com>> wrote:


Wouldn't annotated methods be easier for maintenance ? Something like @Generated<https://github.com/Generated> on the outer scope. That would also avoid reporting issue on such code, as issues would be meaningless.

-

**Comment by gquerret** [comment]
Property sonar.oe.cpd.annotations can now be used to specify a list of annotations. Annotated code will tell the CPD engine to skip the next code block.
```
@rssw.lang.Generated
procedure generateUI:
  create button xxx.
end procedure.
```

**Comment by gquerret** [comment]
Not working correctly in latest release

**Comment by gquerret** [comment]
Fixed in master
