### ISSUE TITLE
False positives for abbreviated keyword FORWARDS

### ISSUE THREAD

**Issue by mikefechner** [Riverside-Software/sonar-openedge#21]
![image](https://cloud.githubusercontent.com/assets/13220627/15532657/3b6726a8-2261-11e6-933c-310df485f16b.png)

According to the online help of the FUNCTION statement, FORWARD is the actual keyword:

![image](https://cloud.githubusercontent.com/assets/13220627/15532686/670b13be-2261-11e6-8ea9-4604026f8c0d.png)

**Comment by jakejustus** [comment]
Will add that as an exception directly in the rule.

**Comment by jakejustus** [comment]
Fixed
