### ISSUE TITLE
Semi-FP on long lines

### ISSUE THREAD

**Issue by mikefechner** [Riverside-Software/sonar-openedge#211]
**
![image](https://cloud.githubusercontent.com/assets/13220627/24603331/9ebdf970-1860-11e7-8c0e-673d4afd6346.png)
**

The comment is indeed filles with 142 characters - but most chars are white space. Due to the documented purpose of that rule, I'd consider this a false positive. 

Or are least there should be an option not to alert when only which space characters cause the rule violation.

**Comment by gquerret** [comment]
In fact not an issue when working with the GUI editor, but still an issue in ChUI.
So added a parameter to control this behavior (default behavior doesn't change)

**Comment by mikefechner** [comment]
Chui???? ;-)

Sent from Nine<http://www.9folders.com/>
________________________________
Von: Gilles QUERRET <notifications@github.com>
Gesendet: 07.05.2017 10:12 vorm.
An: Riverside-Software/sonar-openedge
Cc: Mike Fechner; Author
Betreff: Re: [Riverside-Software/sonar-openedge] Semi-FP on long lines (#211)


In fact not an issue when working with the GUI editor, but still an issue in ChUI.
So added a parameter to control this behavior (default behavior doesn't change)

**Comment by gquerret** [comment]
Fixed in master

**Comment by mikefechner** [comment]
Merci!

Sent from Nine<http://www.9folders.com/>
________________________________
Von: Gilles QUERRET <notifications@github.com>
Gesendet: 07.05.2017 10:47 vorm.
An: Riverside-Software/sonar-openedge
Cc: Mike Fechner; Author
Betreff: Re: [Riverside-Software/sonar-openedge] Semi-FP on long lines (#211)


Fixed in master
