### ISSUE TITLE
END FINALLY issue - potentially proparse

### ISSUE THREAD

**Issue by mikefechner** [Riverside-Software/sonar-openedge#22]
![image](https://cloud.githubusercontent.com/assets/13220627/15571199/cc990e4c-2339-11e6-94da-2ab9f7d64421.png)

Might be the nested FOR EACH in the FINALLY block....

![image](https://cloud.githubusercontent.com/assets/13220627/15571217/e4b66bc8-2339-11e6-8030-93cec0a115d1.png)

**Comment by jakejustus** [comment]
A few cases like this one have already been reported, all different constructs in the FINALLY block.
Will be fixed !

**Comment by jakejustus** [comment]
The finally block was considered a block label.
Fixed in dev.
