### ISSUE TITLE
Compilation problem

### ISSUE THREAD

**Issue by samixchoumi** [Riverside-Software/sonar-openedge#223]
Hello,

After reviewing the code and fixing several import that did not happen through Maven, I still have only the following packages not detected / found by Maven :

- eu.rssw.antlr.database.DumpFileGrammarParser ==> DumpFileVisitor.java
- eu.rssw.antlr.database.DumpFileGrammarLexer ==> OpenEdgeDBKeywords.java
- eu.rssw.antlr.profiler.ProfilerGrammarParser ==> ProfilerSessionVisitor.java

I can not find any solution to this problem on the site or on GitHub, so I have 6 classes that do not compile following this error, I suppose

The files generated during the compilation are them (without having made any modification beforehand)

https://pastebin.com/ytWrwZRm <-- Command line test.xml
https://pastebin.com/UsNKECu1 <-- tesng-failed.xml

I don't know what to do following this issues, I have tried several probable solution, none working.

**Comment by samixchoumi** [comment]
Les fichiers généré lors de la compilation sont ceux là (sans avoir effectué aucune modification au préalable)
`<?xml version="1.0" encoding="UTF-8"?>

<testsuite hostname="FRNTE21859" name="Command line test" tests="171" failures="3" timestamp="26 Apr 2017 13:36:35 GMT" time="3.297" errors="0">
  <testcase name="test01" time="0.015" classname="org.prorefactor.core.unittest.AliasesTest"/>
  <testcase name="test02" time="0.0" classname="org.prorefactor.core.unittest.AliasesTest"/>
  <testcase name="test03" time="0.0" classname="org.prorefactor.core.unittest.AliasesTest"/>
  <testcase name="test04" time="0.0" classname="org.prorefactor.core.unittest.AliasesTest"/>
  <testcase name="test05" time="0.0" classname="org.prorefactor.core.unittest.AliasesTest"/>
  <testcase name="test01" time="0.0" classname="org.prorefactor.core.unittest.ApiTest"/>
  <testcase name="test02" time="0.0" classname="org.prorefactor.core.unittest.ApiTest"/>
  <testcase name="test03" time="0.016" classname="org.prorefactor.core.unittest.ApiTest"/>
  <testcase name="test04" time="0.0" classname="org.prorefactor.core.unittest.ApiTest"/>
  <testcase name="test05" time="0.0" classname="org.prorefactor.core.unittest.ApiTest"/>
  <testcase name="test06" time="0.0" classname="org.prorefactor.core.unittest.ApiTest"/>
  <testcase name="test07" time="0.0" classname="org.prorefactor.core.unittest.ApiTest"/>
  <testcase name="test08" time="0.0" classname="org.prorefactor.core.unittest.ApiTest"/>
  <testcase name="test09" time="0.015" classname="org.prorefactor.core.unittest.ApiTest"/>
  <testcase name="test01" time="0.0" classname="org.prorefactor.core.unittest.BugFixTest"/>
  <testcase name="test02" time="0.016" classname="org.prorefactor.core.unittest.BugFixTest"/>
  <testcase name="test03" time="0.0" classname="org.prorefactor.core.unittest.BugFixTest"/>
  <testcase name="test04" time="0.0" classname="org.prorefactor.core.unittest.BugFixTest"/>
  <testcase name="test05" time="0.0" classname="org.prorefactor.core.unittest.BugFixTest"/>
  <testcase name="test06" time="0.016" classname="org.prorefactor.core.unittest.BugFixTest"/>
  <testcase name="test07" time="0.0" classname="org.prorefactor.core.unittest.BugFixTest"/>
  <testcase name="test08" time="0.0" classname="org.prorefactor.core.unittest.BugFixTest"/>
  <testcase name="test09" time="0.0" classname="org.prorefactor.core.unittest.BugFixTest"/>
  <testcase name="test10" time="0.0" classname="org.prorefactor.core.unittest.BugFixTest"/>
  <testcase name="test11" time="1.438" classname="org.prorefactor.core.unittest.BugFixTest"/>
  <testcase name="test12" time="0.0" classname="org.prorefactor.core.unittest.BugFixTest"/>
  <testcase name="test13" time="0.015" classname="org.prorefactor.core.unittest.BugFixTest"/>
  <testcase name="test14" time="0.0" classname="org.prorefactor.core.unittest.BugFixTest"/>
  <testcase name="test15" time="0.0" classname="org.prorefactor.core.unittest.BugFixTest"/>
  <testcase name="test16" time="0.016" classname="org.prorefactor.core.unittest.BugFixTest"/>
  <testcase name="test17" time="0.0" classname="org.prorefactor.core.unittest.BugFixTest"/>
  <testcase name="test18" time="0.0" classname="org.prorefactor.core.unittest.BugFixTest"/>
  <testcase name="test19" time="0.0" classname="org.prorefactor.core.unittest.BugFixTest"/>
  <testcase name="test20" time="0.016" classname="org.prorefactor.core.unittest.BugFixTest"/>
  <testcase name="test21" time="0.0" classname="org.prorefactor.core.unittest.BugFixTest"/>
  <testcase name="test22" time="0.0" classname="org.prorefactor.core.unittest.BugFixTest"/>
  <testcase name="test23" time="0.0" classname="org.prorefactor.core.unittest.BugFixTest"/>
  <testcase name="test24" time="0.0" classname="org.prorefactor.core.unittest.BugFixTest"/>
  <testcase name="test25" time="0.0" classname="org.prorefactor.core.unittest.BugFixTest"/>
  <testcase name="test26" time="0.015" classname="org.prorefactor.core.unittest.BugFixTest"/>
  <testcase name="test27" time="0.0" classname="org.prorefactor.core.unittest.BugFixTest"/>
  <testcase name="test28" time="0.0" classname="org.prorefactor.core.unittest.BugFixTest"/>
  <testcase name="test29" time="0.0" classname="org.prorefactor.core.unittest.BugFixTest"/>
  <testcase name="test30" time="0.0" classname="org.prorefactor.core.unittest.BugFixTest"/>
  <testcase name="test31" time="0.016" classname="org.prorefactor.core.unittest.BugFixTest"/>
  <testcase name="test32" time="0.0" classname="org.prorefactor.core.unittest.BugFixTest"/>
  <testcase name="test33" time="0.015" classname="org.prorefactor.core.unittest.BugFixTest"/>
  <testcase name="testCache1" time="0.0" classname="org.prorefactor.core.unittest.BugFixTest"/>
  <testcase name="testCache2" time="0.016" classname="org.prorefactor.core.unittest.BugFixTest"/>
  <testcase name="testNoBox" time="0.0" classname="org.prorefactor.core.unittest.BugFixTest"/>
  <testcase name="testSaxWriter" time="0.0" classname="org.prorefactor.core.unittest.BugFixTest"/>
  <testcase name="test01" time="0.016" classname="org.prorefactor.core.unittest.ClassesTest"/>
  <testcase name="test03" time="0.0" classname="org.prorefactor.core.unittest.ClassesTest"/>
  <testcase name="testThisObject" time="0.0" classname="org.prorefactor.core.unittest.ClassesTest"/>
  <testcase name="testAmbiguous" time="0.0" classname="org.prorefactor.core.unittest.LegacyTest"/>
  <testcase name="testAppendProgram" time="0.015" classname="org.prorefactor.core.unittest.LegacyTest"/>
  <testcase name="testBaseDir" time="0.016" classname="org.prorefactor.core.unittest.LegacyTest"/>
  <testcase name="testBubbleProgram01" time="0.0" classname="org.prorefactor.core.unittest.LegacyTest"/>
  <testcase name="testBubbleProgram02" time="0.0" classname="org.prorefactor.core.unittest.LegacyTest"/>
  <testcase name="testBubbleProgram03" time="0.016" classname="org.prorefactor.core.unittest.LegacyTest"/>
  <testcase name="testBubbleProgram04" time="0.0" classname="org.prorefactor.core.unittest.LegacyTest"/>
  <testcase name="testBubbleProgram05" time="0.0" classname="org.prorefactor.core.unittest.LegacyTest"/>
  <testcase name="testExtractMethod" time="0.0" classname="org.prorefactor.core.unittest.LegacyTest"/>
  <testcase name="testNames" time="0.015" classname="org.prorefactor.core.unittest.LegacyTest"/>
  <testcase name="testQualifyFields" time="0.0" classname="org.prorefactor.core.unittest.LegacyTest"/>
  <testcase name="testWrapProcedure" time="0.0" classname="org.prorefactor.core.unittest.LegacyTest"/>
  <testcase name="test01" time="0.0" classname="org.prorefactor.core.unittest.MetricsTest"/>
  <testcase name="test02" time="0.0" classname="org.prorefactor.core.unittest.MetricsTest"/>
  <testcase name="test01" time="0.063" classname="org.prorefactor.core.unittest.NewSyntaxTest"/>
  <testcase name="test02" time="0.0" classname="org.prorefactor.core.unittest.NewSyntaxTest"/>
  <testcase name="test03" time="0.015" classname="org.prorefactor.core.unittest.NewSyntaxTest"/>
  <testcase name="test04" time="0.0" classname="org.prorefactor.core.unittest.NewSyntaxTest"/>
  <testcase name="test05" time="0.0" classname="org.prorefactor.core.unittest.NewSyntaxTest"/>
  <testcase name="test06" time="0.0" classname="org.prorefactor.core.unittest.NewSyntaxTest"/>
  <testcase name="test07" time="0.0" classname="org.prorefactor.core.unittest.NewSyntaxTest"/>
  <testcase name="test08" time="0.0" classname="org.prorefactor.core.unittest.NewSyntaxTest"/>
  <testcase name="test09" time="0.016" classname="org.prorefactor.core.unittest.NewSyntaxTest"/>
  <testcase name="test10" time="0.0" classname="org.prorefactor.core.unittest.NewSyntaxTest"/>
  <testcase name="test11" time="0.0" classname="org.prorefactor.core.unittest.NewSyntaxTest"/>
  <testcase name="test12" time="0.0" classname="org.prorefactor.core.unittest.NewSyntaxTest"/>
  <testcase name="test13" time="0.0" classname="org.prorefactor.core.unittest.NewSyntaxTest"/>
  <testcase name="test14" time="0.015" classname="org.prorefactor.core.unittest.NewSyntaxTest"/>
  <testcase name="test15" time="0.0" classname="org.prorefactor.core.unittest.NewSyntaxTest"/>
  <testcase name="test16" time="0.0" classname="org.prorefactor.core.unittest.NewSyntaxTest"/>
  <testcase name="test17" time="0.016" classname="org.prorefactor.core.unittest.NewSyntaxTest"/>
  <testcase name="test18" time="0.0" classname="org.prorefactor.core.unittest.NewSyntaxTest"/>
  <testcase name="test19" time="0.0" classname="org.prorefactor.core.unittest.NewSyntaxTest"/>
  <testcase name="test20" time="0.0" classname="org.prorefactor.core.unittest.NewSyntaxTest"/>
  <testcase name="test21" time="0.0" classname="org.prorefactor.core.unittest.NewSyntaxTest"/>
  <testcase name="test22" time="0.015" classname="org.prorefactor.core.unittest.NewSyntaxTest"/>
  <testcase name="test23" time="0.0" classname="org.prorefactor.core.unittest.NewSyntaxTest"/>
  <testcase name="test24" time="0.0" classname="org.prorefactor.core.unittest.NewSyntaxTest"/>
  <testcase name="test25" time="0.0" classname="org.prorefactor.core.unittest.NewSyntaxTest"/>
  <testcase name="test26" time="0.0" classname="org.prorefactor.core.unittest.NewSyntaxTest"/>
  <testcase name="test27" time="0.016" classname="org.prorefactor.core.unittest.NewSyntaxTest"/>
  <testcase name="test28" time="0.0" classname="org.prorefactor.core.unittest.NewSyntaxTest"/>
  <testcase name="test29" time="0.0" classname="org.prorefactor.core.unittest.NewSyntaxTest"/>
  <testcase name="test30" time="0.0" classname="org.prorefactor.core.unittest.NewSyntaxTest"/>
  <testcase name="test31" time="0.0" classname="org.prorefactor.core.unittest.NewSyntaxTest"/>
  <testcase name="test32" time="0.0" classname="org.prorefactor.core.unittest.NewSyntaxTest"/>
  <testcase name="test33" time="0.0" classname="org.prorefactor.core.unittest.NewSyntaxTest"/>
  <testcase name="test34" time="0.015" classname="org.prorefactor.core.unittest.NewSyntaxTest"/>
  <testcase name="test35" time="0.0" classname="org.prorefactor.core.unittest.NewSyntaxTest"/>
  <testcase name="test36" time="0.0" classname="org.prorefactor.core.unittest.NewSyntaxTest"/>
  <testcase name="test37" time="0.0" classname="org.prorefactor.core.unittest.NewSyntaxTest"/>
  <testcase name="test38" time="0.0" classname="org.prorefactor.core.unittest.NewSyntaxTest"/>
  <testcase name="test39" time="0.0" classname="org.prorefactor.core.unittest.NewSyntaxTest"/>
  <testcase name="test40" time="0.016" classname="org.prorefactor.core.unittest.NewSyntaxTest"/>
  <testcase name="test41" time="0.0" classname="org.prorefactor.core.unittest.NewSyntaxTest"/>
  <testcase name="test42" time="0.0" classname="org.prorefactor.core.unittest.NewSyntaxTest"/>
  <testcase name="test43" time="0.0" classname="org.prorefactor.core.unittest.NewSyntaxTest"/>
  <testcase name="test44" time="0.0" classname="org.prorefactor.core.unittest.NewSyntaxTest"/>
  <testcase name="test45" time="0.0" classname="org.prorefactor.core.unittest.NewSyntaxTest"/>
  <testcase name="test46" time="0.015" classname="org.prorefactor.core.unittest.NewSyntaxTest"/>
  <testcase name="test47" time="0.0" classname="org.prorefactor.core.unittest.NewSyntaxTest"/>
  <testcase name="test48" time="0.0" classname="org.prorefactor.core.unittest.NewSyntaxTest"/>
  <testcase name="test49" time="0.0" classname="org.prorefactor.core.unittest.NewSyntaxTest"/>
  <testcase name="test50" time="0.0" classname="org.prorefactor.core.unittest.NewSyntaxTest"/>
  <testcase name="test51" time="0.0" classname="org.prorefactor.core.unittest.NewSyntaxTest"/>
  <testcase name="test2BackslashInIncludeWindows" time="0.016" classname="org.prorefactor.core.unittest.OpSysTest"/>
  <testcase name="testBackslashEscape" time="0.016" classname="org.prorefactor.core.unittest.OpSysTest"/>
  <testcase name="testBackslashInIncludeLinux" time="0.0" classname="org.prorefactor.core.unittest.OpSysTest"/>
  <testcase name="testBackslashInIncludeWindows" time="0.015" classname="org.prorefactor.core.unittest.OpSysTest"/>
  <testcase name="testBackslashNoEscape" time="0.0" classname="org.prorefactor.core.unittest.OpSysTest"/>
  <testcase name="testAnd" time="0.0" classname="org.prorefactor.core.unittest.PreprocessorTest"/>
  <testcase name="testDecimal1" time="0.0" classname="org.prorefactor.core.unittest.PreprocessorTest"/>
  <testcase name="testDefined" time="0.0" classname="org.prorefactor.core.unittest.PreprocessorTest"/>
  <testcase name="testDefined2" time="0.0" classname="org.prorefactor.core.unittest.PreprocessorTest"/>
  <testcase name="testDefined3" time="0.0" classname="org.prorefactor.core.unittest.PreprocessorTest"/>
  <testcase name="testEntry1" time="0.0" classname="org.prorefactor.core.unittest.PreprocessorTest"/>
  <testcase name="testEntry2" time="0.0" classname="org.prorefactor.core.unittest.PreprocessorTest"/>
  <testcase name="testEntry3" time="0.0" classname="org.prorefactor.core.unittest.PreprocessorTest"/>
  <testcase name="testExpr1" time="0.0" classname="org.prorefactor.core.unittest.PreprocessorTest"/>
  <testcase name="testExpression1" time="0.0" classname="org.prorefactor.core.unittest.PreprocessorTest"/>
  <testcase name="testExpression2" time="0.0" classname="org.prorefactor.core.unittest.PreprocessorTest"/>
  <testcase name="testExpression3" time="0.0" classname="org.prorefactor.core.unittest.PreprocessorTest"/>
  <testcase name="testFalse" time="0.0" classname="org.prorefactor.core.unittest.PreprocessorTest"/>
  <testcase name="testGT" time="0.0" classname="org.prorefactor.core.unittest.PreprocessorTest"/>
  <testcase name="testGreaterEquals1" time="0.0" classname="org.prorefactor.core.unittest.PreprocessorTest"/>
  <testcase name="testGreaterEquals2" time="0.0" classname="org.prorefactor.core.unittest.PreprocessorTest"/>
  <testcase name="testIndex1" time="0.016" classname="org.prorefactor.core.unittest.PreprocessorTest"/>
  <testcase name="testInt641" time="0.0" classname="org.prorefactor.core.unittest.PreprocessorTest"/>
  <testcase name="testInteger1" time="0.0" classname="org.prorefactor.core.unittest.PreprocessorTest"/>
  <testcase name="testLT" time="0.0" classname="org.prorefactor.core.unittest.PreprocessorTest"/>
  <testcase name="testLeftTrim1" time="0.0" classname="org.prorefactor.core.unittest.PreprocessorTest"/>
  <testcase name="testLength1" time="0.0" classname="org.prorefactor.core.unittest.PreprocessorTest"/>
  <testcase name="testLesserEquals1" time="0.0" classname="org.prorefactor.core.unittest.PreprocessorTest"/>
  <testcase name="testLesserEquals2" time="0.0" classname="org.prorefactor.core.unittest.PreprocessorTest"/>
  <testcase name="testLookup1" time="0.0" classname="org.prorefactor.core.unittest.PreprocessorTest"/>
  <testcase name="testMaximum1" time="0.0" classname="org.prorefactor.core.unittest.PreprocessorTest"/>
  <testcase name="testMinimum1" time="0.0" classname="org.prorefactor.core.unittest.PreprocessorTest"/>
  <testcase name="testNumEntries1" time="0.0" classname="org.prorefactor.core.unittest.PreprocessorTest"/>
  <testcase name="testOr" time="0.0" classname="org.prorefactor.core.unittest.PreprocessorTest"/>
  <testcase name="testRIndex1" time="0.0" classname="org.prorefactor.core.unittest.PreprocessorTest"/>
  <testcase name="testReplace1" time="0.0" classname="org.prorefactor.core.unittest.PreprocessorTest"/>
  <testcase name="testRightTrim1" time="0.0" classname="org.prorefactor.core.unittest.PreprocessorTest"/>
  <testcase name="testSubstring" time="0.0" classname="org.prorefactor.core.unittest.PreprocessorTest"/>
  <testcase name="testSubstring1" time="0.0" classname="org.prorefactor.core.unittest.PreprocessorTest"/>
  <testcase name="testSubstring2" time="0.0" classname="org.prorefactor.core.unittest.PreprocessorTest"/>
  <testcase name="testTrim1" time="0.0" classname="org.prorefactor.core.unittest.PreprocessorTest"/>
  <testcase name="testTrue" time="0.0" classname="org.prorefactor.core.unittest.PreprocessorTest"/>
  <testcase name="testBasicFunctions" time="0.0" classname="org.prorefactor.core.unittest.ProgressStringTest"/>
  <testcase name="test01" time="0.046" classname="org.prorefactor.core.unittest.TP01FramesTest">
    <failure type="java.lang.AssertionError" message="Differences in: src/test/resources/data/tp01tests/frames.expect.txt target\test-temp\tp01tests\frames.out.txt expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Differences in: src/test/resources/data/tp01tests/frames.expect.txt target\test-temp\tp01tests\frames.out.txt expected [true] but found [false]
	at org.prorefactor.core.unittest.TP01FramesTest.test01(TP01FramesTest.java:60)
... Removed 37 stack frames]]>
    </failure>
  </testcase> 
  <testcase name="testCompileFileCalls" time="0.016" classname="org.prorefactor.core.unittest.TP01ProcessActionTest"/>
  <testcase name="testPersistenProc" time="0.0" classname="org.prorefactor.core.unittest.TP01ProcessActionTest"/>
  <testcase name="testCompileFileRoutines" time="0.016" classname="org.prorefactor.core.unittest.TP01SymbolActionTest"/>
  <testcase name="testCompileFileVars" time="0.0" classname="org.prorefactor.core.unittest.TP01SymbolActionTest"/>
  <testcase name="test01" time="0.015" classname="org.prorefactor.core.unittest.TP01Test">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.prorefactor.core.unittest.TP01Test.test01(TP01Test.java:40)
... Removed 38 stack frames]]>
    </failure>
  </testcase> 
  <testcase name="test01" time="0.219" classname="org.prorefactor.core.unittest.TP02Test">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.prorefactor.core.unittest.TP02Test.test01(TP02Test.java:85)
... Removed 38 stack frames]]>
    </failure>
  </testcase> 
  <testcase name="test01" time="0.0" classname="org.prorefactor.core.unittest.TP03Test"/>
  <testcase name="test02" time="0.0" classname="org.prorefactor.core.unittest.TP03Test"/>
</testsuite> 
`
et 

`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite verbose="0" name="Failed suite [Command line suite]">
  <test name="Command line test" preserve-order="false">
    <classes>
      <class name="org.prorefactor.core.unittest.AliasesTest"/>
      <class name="org.prorefactor.core.unittest.ApiTest"/>
      <class name="org.prorefactor.core.unittest.BugFixTest"/>
      <class name="org.prorefactor.core.unittest.ClassesTest"/>
      <class name="org.prorefactor.core.unittest.LegacyTest"/>
      <class name="org.prorefactor.core.unittest.MetricsTest"/>
      <class name="org.prorefactor.core.unittest.NewSyntaxTest"/>
      <class name="org.prorefactor.core.unittest.OpSysTest"/>
      <class name="org.prorefactor.core.unittest.PreprocessorTest"/>
      <class name="org.prorefactor.core.unittest.ProgressStringTest"/>
      <class name="org.prorefactor.core.unittest.TP01FramesTest"/>
      <class name="org.prorefactor.core.unittest.TP01ProcessActionTest"/>
      <class name="org.prorefactor.core.unittest.TP01SymbolActionTest"/>
      <class name="org.prorefactor.core.unittest.TP01Test"/>
      <class name="org.prorefactor.core.unittest.TP02Test"/>
      <class name="org.prorefactor.core.unittest.TP03Test"/>
    </classes>
  </test> 
  <test name="Command line test(failed)">
    <classes>
      <class name="org.prorefactor.core.unittest.ApiTest">
        <methods>
          <include name="setUp"/>
        </methods>
      </class> 
      <class name="org.prorefactor.core.unittest.NewSyntaxTest">
        <methods>
          <include name="setUp"/>
        </methods>
      </class> 
      <class name="org.prorefactor.core.unittest.ClassesTest">
        <methods>
          <include name="setUp"/>
        </methods>
      </class> 
      <class name="org.prorefactor.core.unittest.TP01Test">
        <methods>
          <include name="test01"/>
        </methods>
      </class> 
      <class name="org.prorefactor.core.unittest.AliasesTest">
        <methods>
          <include name="setUp"/>
        </methods>
      </class> 
      <class name="org.prorefactor.core.unittest.TP02Test">
        <methods>
          <include name="test01"/>
          <include name="setUp"/>
        </methods>
      </class> 
      <class name="org.prorefactor.core.unittest.PreprocessorTest">
        <methods>
          <include name="setUp"/>
        </methods>
      </class> 
      <class name="org.prorefactor.core.unittest.TP01ProcessActionTest">
        <methods>
          <include name="setUp"/>
        </methods>
      </class> 
      <class name="org.prorefactor.core.unittest.TP01FramesTest">
        <methods>
          <include name="setUp"/>
          <include name="test01"/>
        </methods>
      </class> 
      <class name="org.prorefactor.core.unittest.TP03Test">
        <methods>
          <include name="setUp"/>
        </methods>
      </class> 
      <class name="org.prorefactor.core.unittest.BugFixTest">
        <methods>
          <include name="setUp"/>
        </methods>
      </class> 
      <class name="org.prorefactor.core.unittest.MetricsTest">
        <methods>
          <include name="setUp"/>
        </methods>
      </class> 
      <class name="org.prorefactor.core.unittest.LegacyTest">
        <methods>
          <include name="setUp"/>
        </methods>
      </class> 
      <class name="org.prorefactor.core.unittest.TP01SymbolActionTest">
        <methods>
          <include name="setUp"/>
        </methods>
      </class> 
    </classes>
  </test> 
</suite> 
`

**Comment by gquerret** [comment]
The OpenEge plugin is successfully built on MacOS X, Windows 10, and Linux. The only requirement is JDK 8 (only tested with Oracle JDK) and Maven 3. Build has to be done with `git clone ... && mvn package`.

PS: English should be the only language here.

**Comment by samixchoumi** [comment]
After some try, the plugin is successfully build.

So the requirement was to use "git clone" command instead of downloading the project manually.

Thanks!
