### ISSUE TITLE
IF THEN ELSE confused with {&_proparse_ prolint-nowarn(avoidnoerror)}

### ISSUE THREAD

**Issue by mikefechner** [Riverside-Software/sonar-openedge#224]
Have added the nowarn annotation here (left before, right after): 
![image](https://cloud.githubusercontent.com/assets/13220627/25496049/da215052-2b7f-11e7-8986-7285e02031d4.png)

But I had to add the `DO END` Block on the `IF THEN ELSE` branches.

SonarLint got confused without:
`C:\Work_LOCAL\SmartComponents4NET\117_64\ABL\Consultingwerk\OERA\DataAccess.cls:1419:9: expecting END, found 'ELSE'	DataAccess.cls`

File compiled fine regardless.

**Comment by gquerret** [comment]
Reproduced

**Comment by gquerret** [comment]
Agree that this is a bug, as the compiler is OK with this code, but that may go in the "Won't fix" section as it will require a bit of work, and I think it will be better to use annotations to suppress warnings.

**Comment by gquerret** [comment]
Note that in this case, this syntax doesn't work:
```
IF TRUE THEN
  @SuppressWarnings.
  MESSAGE "True".
ELSE
  @SuppressWarnings.
  MESSAGE "False".
```

**Comment by mikefechner** [comment]
Is the @SurpressWarnings. a general way of surpressing warnings? 

Are you saying the compiler does not like this - because he treats an annotation as a statement? I would consider that a compiler bug - which they'll probably not fix. But I would log it anyway.

I started a discussion on Communities: https://community.progress.com/community_groups/openedge_development/f/19/t/33467

**Comment by gquerret** [comment]
> Is the @SuppressWarnings. a general way of suppressing warnings? 

Not yet, but that's the kind of enhancement that will come shortly

**Comment by jurjendijkstra-vma** [comment]
I remember from long long ago when I was working on Prolint that the {&_proparse_ ....} directives are only recognized when they are placed just before the beginning of a statement, e.g. on a "statehead" node, and then the _proparse_ directive counts for the entire statement with everything in it.

"IF" is a statehead, "THEN" and "ELSE" are not.
The statement on the ELSE branch is also not a statehead according to Proparse, which is weird, but that explains why it can't have a _proparse_ directive.   Putting DO: END arround your statement makes it a statehead.

I'd guess it would be very difficult to fix that in the proparse logic.

**Comment by mikefechner** [comment]
:-(

**Comment by gquerret** [comment]
Related to #330

**Comment by gquerret** [comment]
Merged in master
