### ISSUE TITLE
Default Buffer rule in DB trigger procedure

### ISSUE THREAD

**Issue by mikefechner** [Riverside-Software/sonar-openedge#23]
![image](https://cloud.githubusercontent.com/assets/13220627/15571585/f0dacff0-233b-11e6-87b0-6b176ceb497a.png)

For the Trigger Table, I don't thing default-buffer usage should be seen as a problem. Or? Especially in a CREATE TRIGGER where the usage of the OLD and NEW buffers makes no real sense.

**Comment by jakejustus** [comment]
Right, will be fixed

**Comment by gquerret** [comment]
Fixed in master
