### ISSUE TITLE
Unknow table name

### ISSUE THREAD

**Issue by samixchoumi** [Riverside-Software/sonar-openedge#238]
Hi,

I was scanning some projects, when i got this error : `Unknown table name: Customer` on SonarQube

So this is the first time i got this issue so i changed my path to the BD like that : `sonar.oe.databases=path/to/the/bd/dump/sp2k.df   `   

And now i get this error : 

> 11:30:30.421 DEBUG: Parsing C:\Users\PATH\TO\THE\BD\dump\sp2k.df with alias sp2k
> 11:30:30.630 INFO: ------------------------------------------------------------------------
> 11:30:30.630 INFO: EXECUTION FAILURE
> 11:30:30.631 INFO: ------------------------------------------------------------------------
> 11:30:30.631 INFO: Total time: 2.823s
> 11:30:30.709 INFO: Final Memory: 45M/244M
> 11:30:30.709 INFO: ------------------------------------------------------------------------
> 11:30:30.710 ERROR: Error during SonarQube Scanner execution

So the parsing cause the error but how i should correct this ?

**Comment by gquerret** [comment]
Could you include the stack trace ? And which version of SQ ? And OE plugin ?
I'd say that given the error, it's because the file can't be found.

**Comment by samixchoumi** [comment]
I'm using 1.9.9  OE plugin and 6.3 SQ, below is the stack trace.
> 13:49:59.786 ERROR: Error during SonarQube Scanner execution
> java.lang.IllegalStateException: Unable to load component class org.sonar.plugins.openedge.foundation.OpenEdgeSettings
>         at org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer.getComponent(ComponentContainer.java:70)
>         at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:632)
>         at org.picocontainer.parameters.BasicComponentParameter$1.resolveInstance(BasicComponentParameter.java:118)
>         at org.picocontainer.parameters.ComponentParameter$1.resolveInstance(ComponentParameter.java:136)
>         at org.picocontainer.injectors.SingleMemberInjector.getParameter(SingleMemberInjector.java:78)
>         at org.picocontainer.injectors.ConstructorInjector$CtorAndAdapters.getParameterArguments(ConstructorInjector.java:309)
>         at org.picocontainer.injectors.ConstructorInjector$1.run(ConstructorInjector.java:335)
>         at org.picocontainer.injectors.AbstractInjector$ThreadLocalCyclicDependencyGuard.observe(AbstractInjector.java:270)
>         at org.picocontainer.injectors.ConstructorInjector.getComponentInstance(ConstructorInjector.java:364)
>         at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.getComponentInstance(AbstractInjectionFactory.java:56)
>         at org.picocontainer.behaviors.AbstractBehavior.getComponentInstance(AbstractBehavior.java:64)
>         at org.picocontainer.behaviors.Stored.getComponentInstance(Stored.java:91)
>         at org.picocontainer.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:606)
>         at org.picocontainer.DefaultPicoContainer.getComponents(DefaultPicoContainer.java:587)
>         at org.sonar.core.platform.ComponentContainer.getComponentsByType(ComponentContainer.java:282)
>         at org.sonar.scanner.bootstrap.ScannerExtensionDictionnary.completeBatchExtensions(ScannerExtensionDictionnary.java:133)
>         at org.sonar.scanner.bootstrap.ScannerExtensionDictionnary.getExtensions(ScannerExtensionDictionnary.java:128)
>         at org.sonar.scanner.bootstrap.ScannerExtensionDictionnary.getFilteredExtensions(ScannerExtensionDictionnary.java:107)
>         at org.sonar.scanner.bootstrap.ScannerExtensionDictionnary.select(ScannerExtensionDictionnary.java:74)
>         at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:45)
>         at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:78)
>         at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:175)
>         at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:143)
>         at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:128)
>         at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:262)
>         at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:257)
>         at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:247)
>         at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:143)
>         at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:128)
>         at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:47)
>         at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:86)
>         at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:143)
>         at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:128)
>         at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:118)
>         at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:117)
>         at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:63)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:498)
>         at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
>         at com.sun.proxy.$Proxy0.execute(Unknown Source)
>         at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
>         at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
>         at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:123)
>         at org.sonarsource.scanner.cli.Main.execute(Main.java:77)
>         at org.sonarsource.scanner.cli.Main.main(Main.java:61)
> Caused by: java.lang.NoSuchMethodError: org.sonar.plugins.openedge.api.objects.DatabaseWrapper.<init>(Lorg/sonar/plugins/openedge/api/eu/rssw/antlr/database/objects/DatabaseDescription;)V
>         at org.sonar.plugins.openedge.foundation.OpenEdgeSettings.readSchema(OpenEdgeSettings.java:364)
>         at org.sonar.plugins.openedge.foundation.OpenEdgeSettings.<init>(OpenEdgeSettings.java:101)
>         at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
>         at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
>         at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
>         at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
>         at org.picocontainer.injectors.AbstractInjector.newInstance(AbstractInjector.java:145)
>         at org.picocontainer.injectors.ConstructorInjector$1.run(ConstructorInjector.java:342)
>         at org.picocontainer.injectors.AbstractInjector$ThreadLocalCyclicDependencyGuard.observe(AbstractInjector.java:270)
>         at org.picocontainer.injectors.ConstructorInjector.getComponentInstance(ConstructorInjector.java:364)
>         at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.getComponentInstance(AbstractInjectionFactory.java:56)
>         at org.picocontainer.behaviors.AbstractBehavior.getComponentInstance(AbstractBehavior.java:64)
>         at org.picocontainer.behaviors.Stored.getComponentInstance(Stored.java:91)
>         at org.picocontainer.DefaultPicoContainer.getInstance(DefaultPicoContainer.java:699)
>         at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:647)
>         at org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer.getComponent(ComponentContainer.java:68)
>         ... 46 more
> 13:49:59.845 DEBUG: Execution getVersion
> 13:49:59.847 DEBUG: Execution stop

The file is here, i've only this file in.

**Comment by samixchoumi** [comment]
Is there any way to connect a BD directly with the properties ==> `sonar.oe.databases`
Because i've the database (.db) and the adresse/port

**Comment by gquerret** [comment]
> Caused by: java.lang.NoSuchMethodError: org.sonar.plugins.openedge.api.objects.DatabaseWrapper.(Lorg/sonar/plugins/openedge/api/eu/rssw/antlr/database/objects/DatabaseDescription;)V

This object only appeared a few days ago in the master branch, the version is not released yet. Update your master branch and rebuild the plugin, or use a version from the [Releases](https://github.com/Riverside-Software/sonar-openedge/releases) page

**Comment by gquerret** [comment]
> Is there any way to connect a BD directly with the properties ==> sonar.oe.databases

No

**Comment by gquerret** [comment]
Use https://github.com/Riverside-Software/pct/wiki/PCTDumpSchema
