### ISSUE TITLE
Proparse error

### ISSUE THREAD

**Issue by samixchoumi** [Riverside-Software/sonar-openedge#239]
As this is told, i've an issue about proparse error but it's the PCT code example (with some requests added to test)
PCTCompile is fine but after scanning, that's what i get : 
![whats-wrong_2](https://cloud.githubusercontent.com/assets/22171928/25889718/2014d148-356b-11e7-8d70-5e1db151eedc.png)

EDIT : I was looking at the terminal and he told me he doesn't found db.df, so i put the path like that : `sonar.oe.databases=db\\db.df` and now i got this error, i'm trying to correct this but i don't know what's wrong between my and your code.

I compare https://github.com/Riverside-Software/sonar-openedge/issues/57 and that :

> 10:42:23.713 DEBUG: Parsing C:\Users\\ws\SonarQube2\test-ant\db\db.df with alias db
> 10:42:23.932 INFO: ------------------------------------------------------------------------
> 10:42:23.938 INFO: EXECUTION FAILURE
> 10:42:23.939 INFO: ------------------------------------------------------------------------
> 10:42:23.940 INFO: Total time: 3.169s
> 10:42:24.018 INFO: Final Memory: 45M/243M
> 10:42:24.018 INFO: ------------------------------------------------------------------------
> 10:42:24.019 ERROR: Error during SonarQube Scanner execution
> java.lang.IllegalStateException: Unable to load component class org.sonar.plugins.openedge.foundation.OpenEdgeSettings
>         at org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer.getComponent(ComponentContainer.java:70)
>         at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:632)
>         at org.picocontainer.parameters.BasicComponentParameter$1.resolveInstance(BasicComponentParameter.java:118)
>         at org.picocontainer.parameters.ComponentParameter$1.resolveInstance(ComponentParameter.java:136)
>         at org.picocontainer.injectors.SingleMemberInjector.getParameter(SingleMemberInjector.java:78)
>         at org.picocontainer.injectors.ConstructorInjector$CtorAndAdapters.getParameterArguments(ConstructorInjector.java:309)
>         at org.picocontainer.injectors.ConstructorInjector$1.run(ConstructorInjector.java:335)
>         at org.picocontainer.injectors.AbstractInjector$ThreadLocalCyclicDependencyGuard.observe(AbstractInjector.java:270)
>         at org.picocontainer.injectors.ConstructorInjector.getComponentInstance(ConstructorInjector.java:364)
>         at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.getComponentInstance(AbstractInjectionFactory.java:56)
>         at org.picocontainer.behaviors.AbstractBehavior.getComponentInstance(AbstractBehavior.java:64)
>         at org.picocontainer.behaviors.Stored.getComponentInstance(Stored.java:91)
>         at org.picocontainer.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:606)
>         at org.picocontainer.DefaultPicoContainer.getComponents(DefaultPicoContainer.java:587)
>         at org.sonar.core.platform.ComponentContainer.getComponentsByType(ComponentContainer.java:282)
>         at org.sonar.scanner.bootstrap.ScannerExtensionDictionnary.completeBatchExtensions(ScannerExtensionDictionnary.java:133)
>         at org.sonar.scanner.bootstrap.ScannerExtensionDictionnary.getExtensions(ScannerExtensionDictionnary.java:128)
>         at org.sonar.scanner.bootstrap.ScannerExtensionDictionnary.getFilteredExtensions(ScannerExtensionDictionnary.java:107)
>         at org.sonar.scanner.bootstrap.ScannerExtensionDictionnary.select(ScannerExtensionDictionnary.java:74)
>         at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:45)
>         at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:78)
>         at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:175)
>         at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:143)
>         at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:128)
>         at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:262)
>         at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:257)
>         at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:247)
>         at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:143)
>         at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:128)
>         at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:47)
>         at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:86)
>         at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:143)
>         at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:128)
>         at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:118)
>         at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:117)
>         at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:63)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:498)
>         at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
>         at com.sun.proxy.$Proxy0.execute(Unknown Source)
>         at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
>         at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
>         at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:123)
>         at org.sonarsource.scanner.cli.Main.execute(Main.java:77)
>         at org.sonarsource.scanner.cli.Main.main(Main.java:61)
> Caused by: java.lang.NoSuchMethodError: org.sonar.plugins.openedge.api.objects.DatabaseWrapper.<init>(Lorg/sonar/plugins/openedge/api/eu/rssw/antlr/database/objects/DatabaseDescription;)V
>         at org.sonar.plugins.openedge.foundation.OpenEdgeSettings.readSchema(OpenEdgeSettings.java:367)
>         at org.sonar.plugins.openedge.foundation.OpenEdgeSettings.<init>(OpenEdgeSettings.java:104)
>         at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
>         at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
>         at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
>         at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
>         at org.picocontainer.injectors.AbstractInjector.newInstance(AbstractInjector.java:145)
>         at org.picocontainer.injectors.ConstructorInjector$1.run(ConstructorInjector.java:342)
>         at org.picocontainer.injectors.AbstractInjector$ThreadLocalCyclicDependencyGuard.observe(AbstractInjector.java:270)
>         at org.picocontainer.injectors.ConstructorInjector.getComponentInstance(ConstructorInjector.java:364)
>         at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.getComponentInstance(AbstractInjectionFactory.java:56)
>         at org.picocontainer.behaviors.AbstractBehavior.getComponentInstance(AbstractBehavior.java:64)
>         at org.picocontainer.behaviors.Stored.getComponentInstance(Stored.java:91)
>         at org.picocontainer.DefaultPicoContainer.getInstance(DefaultPicoContainer.java:699)
>         at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:647)
>         at org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer.getComponent(ComponentContainer.java:68)
>         ... 46 more
> 10:42:24.074 DEBUG: Execution getVersion
> 10:42:24.079 DEBUG: Execution stop
>

**Comment by gquerret** [comment]
The point is:

> Caused by: java.lang.NoSuchMethodError: org.sonar.plugins.openedge.api.objects.DatabaseWrapper.<init>(Lorg/sonar/plugins/openedge/api/eu/rssw/antlr/database/objects/DatabaseDescription;)V

This is something coming from the master branch, and not yet released. Please don't use the master branch unless you know exactly what you're doing.
