### ISSUE TITLE
Transaction span in DB trigger procedure

### ISSUE THREAD

**Issue by mikefechner** [Riverside-Software/sonar-openedge#24]
![image](https://cloud.githubusercontent.com/assets/13220627/15571625/2f1948f0-233c-11e6-8079-aad8599ea8b9.png)

A DB trigger is always executed within the transaction that does the actual DB change. So I believe it's ok - if not even required - that a trigger procedure is single large transaction block.

**Comment by gquerret** [comment]
Fixed in master
