### ISSUE TITLE
Only 4 rules with 2.0.0

### ISSUE THREAD

**Issue by movedoa** [Riverside-Software/sonar-openedge#249]
I updated to SonarQube 6.3.1 and installed the 2.0 plugins, i also updated the licence plugin to 1.0.3 but i only see 4 rules now.

![grafik](https://cloud.githubusercontent.com/assets/13309951/26239238/7f07cfd0-3c7c-11e7-9465-b01028b2c0f4.png)

**Comment by gquerret** [comment]
There was a similar issue on the SonarQube mailings lists a few days ago. Did you follow the instructions for the SQ upgrade, and especially the initial install on a fresh database ?

**Comment by movedoa** [comment]
I thougth so, but maybe i missed something, i will try again and report back if the issue persists.

**Comment by gquerret** [comment]
Did you keep a backup of the database before migration ?

**Comment by gquerret** [comment]
Message I was talking about: https://groups.google.com/forum/#!topic/sonarqube/MEQg7DKWSsc

**Comment by movedoa** [comment]
Aes i had a backup.
I applied the update again and now everything works, don't know what the problem was exactly, i must have missed something
