### ISSUE TITLE
Property for include ?

### ISSUE THREAD

**Issue by samixchoumi** [Riverside-Software/sonar-openedge#251]
Hi, 

Here is the list of properties about sonar-openedge plugin (https://github.com/Riverside-Software/sonar-openedge/wiki/Property-list).
I don't see any properties to define the path for include.
So i get this error about include but i don't find how to correct it.
```
C:\User\workspace\BUILD_46.06\temp\src\csc.p: Could not find include file: stparam.sha' 
- Please report this issue.
```

**Comment by gquerret** [comment]
You probably didn't spend a long time, it's the first one in the list.

* `sonar.oe.propath`: comma-separated list of PL or directories
