### ISSUE TITLE
XML XREF filter only works for 0x01-0x04

### ISSUE THREAD

**Issue by movedoa** [Riverside-Software/sonar-openedge#260]
I have set the following properties in my buildscript:
```
<property name="sonar.oe.xref.filter" value="true"/>
<property name="sonar.oe.xref.filter.bytes" value="1,2,3,4,5,6"/>
```

But in the build output i only get this:
[sonar:sonar] XML XREF filter activated [0x01,0x02,0x03,0x04]

**Comment by gquerret** [comment]
Documentation is incorrect, the correct names are `sonar.oe.filter.invalidxref` and `sonar.oe.filter.invalidxref.bytes`.
The [wiki page](https://github.com/Riverside-Software/sonar-openedge/wiki/Property-list) has been updated.
