### ISSUE TITLE
Abbreviated table or fields names no longer recognized

### ISSUE THREAD

**Issue by gquerret** [Riverside-Software/sonar-openedge#264]
On behalf of M.
Leading to errors `Failed to find LIKE datatype at src\xxx.p line yyy`

**Comment by maelstraggiotti** [comment]
I confirm the same issue here, with an unabbreviated table and field name.

`Failed to find LIKE datatype` encountered inside a DEFINE TEMP-TABLE into a .i include file.

**Comment by gquerret** [comment]
Fixed in master ( dd408c84b1fb6d3a68f98162c143d5051fc84c56 )
