### ISSUE TITLE
CREATE COM object statement is unrecognized

### ISSUE THREAD

**Issue by maelstraggiotti** [Riverside-Software/sonar-openedge#268]
The [CREATE ](https://documentation.progress.com/output/ua/OpenEdge_latest/index.html#page/dvref%2Fcreate-automation-object-statement.html) statement used to instantiate a COM object seems unrecognized.

The exact statement is `CREATE VALUE("Excel.Application") hComHandle CONNECT NO-ERROR.`

**Comment by gquerret** [comment]
Reproduced, the syntax `CREATE "Excel.Application" hComHandle CONNECT NO-ERROR` works, but not with the `VALUE` keyword.
Will be fixed in next release.

**Comment by gquerret** [comment]
Fixed in master
