### ISSUE TITLE
COPY-LOB with source codepage unrecognized

### ISSUE THREAD

**Issue by maelstraggiotti** [Riverside-Software/sonar-openedge#269]
The statement : 
`    COPY-LOB FROM FILE xxx TO yyy CONVERT TARGET CODEPAGE "ISO8859-1" SOURCE CODEPAGE "ISO8859-1".`
raises an error : `unexpected token: SOURCE`

**Comment by gquerret** [comment]
Reproduced. Current grammar implementation is incorrectly looking for `SOURCE` attribute first. Will be fixed in next release.

**Comment by gquerret** [comment]
Fixed in master
