### ISSUE TITLE
.df directory ?

### ISSUE THREAD

**Issue by samixchoumi** [Riverside-Software/sonar-openedge#272]
Anyone know how to declare just the directory where are the .df file ? Because for the moment i must declare all file, one by one, and it's not very optimal for me and when i try to just declare the directory, that's not working.
I'm using Sonar for Ant

**Comment by gquerret** [comment]
The property expects file names, not a directory. You can however work with Ant filesets and pathconvert to create the value of `sonar.oe.databases`. But do you really have so many databases that it's too difficult to declare them by hand ?

**Comment by samixchoumi** [comment]
I'm trying to create one block, that could be used on every project, but the databases are differents for every project, so it would be more usefull to just put the directory and then it will find .df files.
For the moment i will look at Ant filesets and pathconvert.
