### ISSUE TITLE
 Runtime exception was caught 'Lexical cast to number from:  failed.'

### ISSUE THREAD

**Issue by maelstraggiotti** [Riverside-Software/sonar-openedge#278]
When running an analysis on our codebase, we encounter the following message on few files : 
` Runtime exception was caught 'Lexical cast to number from:  failed.' - Please report this issue : `

It appears several times, as shown in [the attached file](https://github.com/Riverside-Software/sonar-openedge/files/1068252/sonar.txt).

Please tell me if you need separate issues for each messages, and how I can find some more detail.

**Comment by gquerret** [comment]
The problems with include files can be fixed by just changing the propath, and given the file names, I think that using `sonar.oe.dlc.propath` would be enough.
Regarding the other issues, that's a preprocessor issue. There's a tool to help debugging those issues, but that's not publicly available yet. How many of those issues are found in your codebase ?

**Comment by maelstraggiotti** [comment]
I excluded the file which contained the invalid include reference, as I already had the DLC in my Propath. Now, I have these issues : 
```
3x - Runtime exception was caught 'Lexical cast to number from:  failed.' - Please report this issue : 
1x - Runtime exception was caught 'java.io.IOException: src/adm2/smrtprop.i: Could not find include file: get' - 
```
I would be open to exclude the concerned file but none of them are not mentionned. I have no direct reference to smrtprop.i in our codebase, for instance.

**Comment by gquerret** [comment]
You can use the verbose mode in order to see the file names (`ant -v` when using Ant, or add `-X` with command line scanner).
If you're using ADM2 code, then smrtprop.i is used everywhere, as well as `get`.

**Comment by maelstraggiotti** [comment]
The lexical cast to number is logical : 
```
&IF INTEGER("{&TOKEN}") <= 1 &THEN
...
&ENDIF
```
where token is undefined.

I fixed our code. As it does not happen to cause a compilation error, shouldn't it be reported as bug in sonar ?

**Comment by gquerret** [comment]
Fixed in PR-282

**Comment by gquerret** [comment]
Fixed in master
