### ISSUE TITLE
[Request]  String attribute rule should have option to catch empty strings

### ISSUE THREAD

**Issue by movedoa** [Riverside-Software/sonar-openedge#291]
At the moment the rule ignores empty strings without string attributes ("" or '')
It would be nice to have the option to disable this.
It happend a few times already that someone added a string and then forgot to add the string attribute.

**Comment by gquerret** [comment]
Makes sense.
I assume that strings with only spaces or tabs would fit in this case too ?

**Comment by movedoa** [comment]
Those get currently marked.
Afaik this is correct since you would have spaces and tabs in the translation manager if you forget :U, so imho those should not be optional.

**Comment by gquerret** [comment]
Add in PR-74: attribute IgnoreEmptyStrings (boolean), defaults to true

**Comment by gquerret** [comment]
Merged in master
