### ISSUE TITLE
 Abbreviated keywords rule does not work on ASC in Temp-Table index

### ISSUE THREAD

**Issue by movedoa** [Riverside-Software/sonar-openedge#294]
![grafik](https://user-images.githubusercontent.com/13309951/27472777-f1e26af6-57fc-11e7-94d0-e99a9cdfa8c4.png)

I guess it thinks this is the ASC function

Btw. this is a realy low priorty bug since i have ASCENDING and DESCENDING exluded anyway so no rush to fix this ;-) (at least for me)

**Comment by gquerret** [comment]
The beauty of ABL... Yes, the fact that ASC can either be a function or a keyword is a pain for the parser.
This case is unlikely to be fixed in a near future. Even the strict mode compiler doesn't catch the issue.

**Comment by gquerret** [comment]
Fixed as part of another development, so just a nice side effect.
