### ISSUE TITLE
NO-ERROR in statement violation is always shown at the beginning of the file

### ISSUE THREAD

**Issue by movedoa** [Riverside-Software/sonar-openedge#297]
In this case it happened in a class, i don't know it this is exclusive to classes.

![grafik](https://user-images.githubusercontent.com/13309951/27596353-acc20c18-5b5f-11e7-9adb-12f006e3da5e.png)

**Comment by gquerret** [comment]
It's a case which has been submitted offline, and which didn't go to the bug tracker for an unknown reason.
A test case was even provided.

**Comment by gquerret** [comment]
By digging into the test case, it was possible to reproduce for any assignment without the `ASSIGN` keyword (and of course with `NO-ERROR`)

**Comment by gquerret** [comment]
Fixed in master, issue now reported directly on the NO-ERROR keyword
