### ISSUE TITLE
Proparse error: CREATE QUERY THIS-OBJECT:cQuery

### ISSUE THREAD

**Issue by movedoa** [Riverside-Software/sonar-openedge#3]
The following code throws the proparse error "unexpected token: THIS-OBJECT"

`CREATE QUERY THIS-OBJECT:cQuery.`
(cQuery is a privare character variable in a class)

A similar error occures when creating the query with a character from a static class like this:
`CREATE QUERY File.QueryClass:cQuery.`
The error i get with this is: "unexpected token: :"

**Comment by jakejustus** [comment]
Already been reported in the internal bug tracker ; will be fixed in a future release (planning TBD)

**Comment by jakejustus** [comment]
Fixed in 1.9.1
