### ISSUE TITLE
Coverage too low when ABLUnit executes t*.p instead a single test.p

### ISSUE THREAD

**Issue by jurjendijkstra** [Riverside-Software/sonar-openedge#302]
Hi,
We have an includefile (named "waardeexpressie.i") with complicated logic in it, we are interested to see the code coverage of this includefile. We are disapointed that the code coverage appears very very low. 
This is measured with PCT task ABLUnit with fileset includes "t*.p". This wildcard "t*.p" resolves to a bunch of testfiles, many of which (but not all of them) indirectly run code in our waardeexpressie.i, so the coverage should be good. But it is very low.

Now when I run PCT task ABLUnit with fileset includes "twaardeexpressie.p", i.e. just a single testfile instead of wildcard "t*.p", then the coverage looks good and realistic in sonarqube.

One would think that the more unittestprocedures we have, the higher coverage we get, but that does not seem to be the case.

Any suggestions what we can do?

**Comment by jurjendijkstra-vma** [comment]
FYI: Now I have also tried to run the Ant script inside-out: for each testfile in "t*.p" run ABLUnit  for that single testfile. That yields as many profiler output files as there are testfiles.
But unfortunately it did not help: the displayed coverage of this waardeexpressie.i file is still bad.

**Comment by gquerret** [comment]
Code coverage is the ratio between the number of executed lines and the number of executable lines. The number of tests has nothing to do with code coverage. The number of executable lines is read from the rcode, and dispatched in include files. So if 95% of your codebase is not tested (for whatever reason), then code coverage will never exceed 5%.
You can reduce the scope of code coverage by using the property `sonar.coverage.exclusions`, and exclude sets of directories

**Comment by gquerret** [comment]
About your second comment, you can drill down into the code of waardeexpressie.i, and see which lines have been executed or not. Does the result seem OK ? Or not ?

**Comment by jurjendijkstra-vma** [comment]
When I look at the code of waardeexpressie.i I see the vertical red lines (tooltip "Not covered by tests.") even on blocks and statements of which I am sure that they should have a green line. 
We have even added a message statement, seen the message during ABLUnit execution, but still the blocks are marked with the red line.  The only way to render the blocks green was to run only one specific unittest procedure; other unittests seem to reset the covered status to false. It is strange.

**Comment by gquerret** [comment]
Could you just confirm that if you run one specific unit procedure, you have lines in green, and that if you add a second procedure, then lines are marked as red ?
I'd like to verify where the issue comes from, either from profiler output itself, from the aggregation of profiler output, or from the sonar sensor.

**Comment by gquerret** [comment]
Fixed offline
