### ISSUE TITLE
Unexpected token: ::

### ISSUE THREAD

**Issue by jurjendijkstra** [Riverside-Software/sonar-openedge#304]
Unexpected token: `::` from this ABL statement:
```
super:fillEntityInfo(self, dataset dsTables::ttVersionEntityInfo).
```
at `org.prorefactor.proparse.ProParser.parameter_dataset_options(ProParser.java:19104)`

**Comment by jurjendijkstra-vma** [comment]
sorry, I meant **un**expected token, instead expected :-)

**Comment by gquerret** [comment]
Could you include the signature of fillEntityInfo method from the super class ?

**Comment by jurjendijkstra** [comment]
Sure, but the unexpected token is the double colon in dsTables::ttVersionEntityInfo, I don't think method fillEntityInfo has much to do with it.

fillEntityInfo in the super class goes like this:


    method protected void fillEntityInfo (input phBuffer as handle, input phEntityInfo as handle):

        if not valid-handle(phEntityInfo) then
            return.

        phEntityInfo:buffer-create().    

        assign phEntityInfo::Id = guid
               phEntityInfo::EntityName = GetEntityName(phBuffer)
               phEntityInfo::IdEntity = phBuffer::Id
               phEntityInfo::IdSmState = getIdCurrentState(phBuffer)
               phEntityInfo::CanUse = CanUse(phBuffer)
               phEntityInfo::CanUpdate = CanUpdate(phBuffer)
               phEntityInfo::CanDelete = CanDelete(phBuffer).

        phEntityInfo:buffer-release().

    end method.

**Comment by gquerret** [comment]
@jurjendijkstra Right, this has been reproduced without the need for the method signature !

**Comment by gquerret** [comment]
Fixed in master
