### ISSUE TITLE
org.prorefactor.proparse.antlr4.PreprocessorParser can not be resolved

### ISSUE THREAD

**Issue by Razack0684** [Riverside-Software/sonar-openedge#308]
I created build from sonar-OE-plugin2.0.0 and deployed it in sonarqube 6.3. However when I analyze the OE project, I get below compilation error.
```
Error during SonarQube Scanner execution
java.lang.Error: Unresolved compilation problems:
        The import org.prorefactor.proparse.antlr4.PreprocessorParser cannot be resolved
        The import org.prorefactor.proparse.antlr4.PreprocessorParser cannot be resolved
        The import org.prorefactor.proparse.antlr4.PreprocessorParser cannot be resolved.
```

I also don't fine PreprocessorParser package in the codebase.

**Comment by gquerret** [comment]
I strongly advise you to download and use 2.0.2 from the [release page](https://github.com/Riverside-Software/sonar-openedge/releases/tag/V2.0.2)
