### ISSUE TITLE
unexpected token: abstract

### ISSUE THREAD

**Issue by jurjendijkstra** [Riverside-Software/sonar-openedge#309]
In our legacy code there is a temp-table that has a field with fieldname "abstract", and proparse does not expect that.

I'd say priority is low or zero because we can change the fieldname and it is not wise to use a keyword for a fieldname. 

```
DEFINE TEMP-TABLE tt_subnodes NO-UNDO
    FIELD volgnr        AS INTEGER
    FIELD uuid          AS CHARACTER
    FIELD versie        AS INTEGER
    FIELD bedrstructuur AS CHARACTER
    FIELD class_id      AS CHARACTER
    FIELD hasChild      AS LOGICAL
    FIELD abstract      AS LOGICAL
    FIELD MutexStatus   AS INTEGER
    FIELD IsNetwerk     AS INTEGER
    FIELD InUse         AS INTEGER 
    FIELD omschrijving  AS CHARACTER.

```

**Comment by jurjendijkstra** [comment]
I have just edited the legacy code so the proparse error is gone.  So this issue is only FYI.

**Comment by gquerret** [comment]
Had a quick look, would be too long and add too much complexity for the outcome.
