### ISSUE TITLE
Unexpected token caused by &_proparse_ prolint-nowarn

### ISSUE THREAD

**Issue by cverbiest** [Riverside-Software/sonar-openedge#313]
The presence of {&_proparse_ prolint-nowarn(nowhere,wholeindex)} causes an

Unexpected token menuloop.

```
    menuloop:
    {&_proparse_ prolint-nowarn(nowhere,wholeindex)}
    for each MENU no-lock:
    end.
```

this construct compiles and works with prolint

**Comment by gquerret** [comment]
Reproduced. Will have a look, but likely to be a `wontfix`

**Comment by gquerret** [comment]
Will be handled in #330
