### ISSUE TITLE
Errors should be SERIALIZABLE

### ISSUE THREAD

**Issue by mikefechner** [Riverside-Software/sonar-openedge#319]
Test super-classes, class must directly or indirectly inherit from Progress.Lang.AppServer

CLASS Statement should have SERIALIZABLE flag.

Need to be able to escape from the rule using Annotation or Scoped-Define, as a few errors cannot be SERIALIZABLE

**Comment by gquerret** [comment]
Why should errors be serializable ? What's the impact of a non-serializable error ?
And I don't see the link between errors and Progress.Lang.AppServer. Is that because they have to be transferred (and thus serialized) from server side to client side ?

**Comment by mikefechner** [comment]
Pardon. Errors must inherit from ProgresSmEant.AppError 

If they don't, they cannot be thrown from the AppServer to the client

**Comment by gquerret** [comment]
PR opened
⚠️ Don't test this version for now as there are currently breaking API changes in the master branch

**Comment by gquerret** [comment]
@mikefechner Make sure you update your private rules if you try the master branch

**Comment by mikefechner** [comment]
@gquerret So this is safe to use now?

**Comment by mikefechner** [comment]
> Need to be able to escape from the rule using Annotation or Scoped-Define, as a few errors cannot be SERIALIZABLE

Has this been implemented as well? If so, that's missing in the rule-documentation.

**Comment by gquerret** [comment]
Nope, not yet

Le 17 août 2017 11:56 AM, "Mike Fechner" <notifications@github.com> a
écrit :

**Comment by mikefechner** [comment]
This is working nicely - but we definitively need to be able to escape from the rule using an annotation or preprocessor.

**Comment by gquerret** [comment]
@mikefechner You can use `{&_proparse_ prolint-nowarn(serializableerror)}`
Available in the PR

**Comment by mikefechner** [comment]
The version on the master is working nice and pretty for us! Consider it tested.

**Comment by gquerret** [comment]
Merged in master

**Comment by mikefechner** [comment]
Merci!
