### ISSUE TITLE
Missing Suppress issue for "No error handling directive"

### ISSUE THREAD

**Issue by bmtheo** [Riverside-Software/sonar-openedge#338]
Hello,

It seems like it's missing the Suppress issue tag for the "No error handling directive" in the Rule description view.

![2017-08-24_13-25-52](https://user-images.githubusercontent.com/31310846/29664449-e5255cfc-88cf-11e7-9c8c-4c3a9f68db01.png)

Thanks =)

**Comment by gquerret** [comment]
That's not only in the description, but in the rule itself!
Will be added in the next release

**Comment by bmtheo** [comment]
Ok great thanks !

**Comment by gquerret** [comment]
Fixed in master

**Comment by gquerret** [comment]
@bmtheo Could you contact me at g.querret@riverside-software.fr ? Thanks
