### ISSUE TITLE
Inherited property cause incorrect usage of default buffer detection

### ISSUE THREAD

**Issue by maelstraggiotti** [Riverside-Software/sonar-openedge#342]
Given the following class hierarchy, using parent's property Name triggers Default Buffer Usage for the obscure SYSCHKCONSTR_NAME_MAP buffer.
```
CLASS test.Parent: 
    DEFINE PUBLIC PROPERTY NAME AS CHARACTER NO-UNDO
    GET.
    SET.
END CLASS.
```
```
CLASS test.Child INHERITS test.Parent: 
    METHOD PUBLIC VOID Test():
        MESSAGE NAME. /* Usage of default buffer for SYSCHKCONSTR_NAME_MAP */
    END METHOD.
END CLASS.
```

Thanks

**Comment by maelstraggiotti** [comment]
Another case encountered, but this time with one of our database buffer.

**Comment by gquerret** [comment]
Reproduced.

**Comment by gquerret** [comment]
@maelstraggiotti Just to be sure, that's not a regression, the issue was already there before 2.1.0 ?

**Comment by maelstraggiotti** [comment]
Not sure, but the issue has been created just before 2.1.0 release, but I was then using a snapshot version. Anyway, the code was already like this way before then.

**Comment by gquerret** [comment]
I'd say it's in fact a regression. The property has to be found from the parent TypeInfo object (read from rcode). I want to double-check that the behavior is correct before merging in master.

**Comment by gquerret** [comment]
Fixed in master
