### ISSUE TITLE
{&_proparse_ prolint-nowarn(varusage)} is not working for INPUT PARAMETER

### ISSUE THREAD

**Issue by bmtheo** [Riverside-Software/sonar-openedge#345]
Hello,

According to the doc to suppress the warning on the var usage for INPUT PARAMETER we should use : "{&_proparse_ prolint-nowarn(varusage)}" 

It is apparently not working correctly

![sonar lint unused variables 1](https://user-images.githubusercontent.com/31310846/29777876-ce638ffc-8c0d-11e7-8072-42ec2c32d5c9.png)
![sonar lint unused variables 2](https://user-images.githubusercontent.com/31310846/29777877-ce658424-8c0d-11e7-9756-11315203ef5b.png)
![sonar lint unused variables 3](https://user-images.githubusercontent.com/31310846/29777878-ce666ca4-8c0d-11e7-9acd-7d0d86c514f4.png)

I tried with other values like these : 
"{&_proparse_ prolint-nowarn(paramusage)}" 
"{&_proparse_ prolint-nowarn(inputsage)}" 
"{&_proparse_ prolint-nowarn(parametersage)}" 

None of them worked out 

EDIT : 
It is not the same as the [Issue#132](https://github.com/Riverside-Software/sonar-openedge/issues/132) because it does work on "normal" variables (DEFINE VARIABLE ...)

**Comment by gquerret** [comment]
Fixed in master
