### ISSUE TITLE
scanner: missing space between condition and &then throws runtime exception

### ISSUE THREAD

**Issue by stefandrissen** [Riverside-Software/sonar-openedge#355]
```
&SCOPED-DEFINE SOMETHING TRUE

&IF {&SOMETHING}&THEN
   MESSAGE 1.
&ENDIF
```

Note the (accidentally) missing space before &THEN - the Progress compiler accepts this just fine, but the lexer does not:

```
ERROR: Runtime exception was caught - Please report this issue :
java.lang.IllegalArgumentException: Line 7 - Unexpected end of input after &IF or &ELSEIF
        at org.prorefactor.proparse.antlr4.PostLexer.throwMessage(PostLexer.java:267)
```

**Comment by gquerret** [comment]
My point of view is that this shouldn't be accepted by the compiler, and that the OE code should be fixed, not the parser.
A simple search and replace will let you add the missing space.
