### ISSUE TITLE
scanner: unexpected token: : when using menu-item mi:sensitive

### ISSUE THREAD

**Issue by stefandrissen** [Riverside-Software/sonar-openedge#356]
```
define sub-menu sm
   menu-item mi
   .

define menu mb menubar
   sub-menu sm
   .

menu-item mi:sensitive in menu sm = false.
``` 

```
ERROR: Error during code parsing for ui/version.p
org.prorefactor.refactor.RefactorException: C:\tfs\ef72\4\work\ui\version.p:9:13: unexpected token: :
        at org.prorefactor.treeparser.ParseUnit.parse(ParseUnit.java:154)
        at org.prorefactor.treeparser.ParseUnit.treeParser01(ParseUnit.java:181)
```

**Comment by gquerret** [comment]
The compiler accepts the following syntax:
```
define menu xxx sub-menu sm1 sub-menu sm2 sub-menu sm3.
/* Here with 'period' after each sub-menu */
define menu xxx sub-menu sm1. sub-menu sm2. sub-menu sm3.
```

The parser has to detect if the period represents the end of statement or just a separator between the sub-menu. And [this is done](https://github.com/Riverside-Software/sonar-openedge/blob/9395d556cc0b937173679cd65cf41ba0490186c9/proparse/src/main/antlr/proparse.g#L2135) by having a look at token after the period. If the token is sub-menu, menu-item, rule or skip then it's considered a separator.

This heuristic is wrong in this case, but that will be considered an unfortunated side effect. Unless this prevents parsing a lot of files, that will be a won't fix.

**Comment by stefandrissen** [comment]
OK - worked around by adding a block around it:
````
define sub-menu sm
   menu-item mi
   .

define menu mb menubar
   sub-menu sm
   .
do:
   menu-item mi:sensitive in menu sm = false.
end.
````
