### ISSUE TITLE
NO-ERROR option in 'DELETE' statement

### ISSUE THREAD

**Issue by stefandrissen** [Riverside-Software/sonar-openedge#364]
This rule is triggered for DELETE OBJECT while DELETE OBJECT is often used in FINALLY blocks for clean up where the objects do not need to be valid. The omission of a NO-ERROR even wipes out the actual reason for the failure - since it is replaced with an invalid handle error.

These could be replaced with IF VALID-HANDLE( h ) THEN DELETE OBJECT h instead of DELETE OBJECT h - but that's just extra noise.

Note: I have added 'DELETE OBJECT' to the exclusion parameter - but not sure if these two keywords classify as a keyword.

**Comment by movedoa** [comment]
DELETE OBJECT with NO-ERROR breaks code that relies on ERROR-STATUS.
If implemented than this can only be optional.

**Comment by gquerret** [comment]
> Note: I have added 'DELETE OBJECT' to the exclusion parameter - but not sure if these two keywords classify as a keyword.

You'd only to specify `DELETE` in the exclusion parameter

**Comment by stefandrissen** [comment]
Wouldn't that also result in ``DELETE customer NO-ERROR`` from no longer triggering the rule?

**Comment by gquerret** [comment]
Yes, that's the side effect, wanted to add that  in my comment, but was distracted...
You can also use `{&_proparse_ prolint-nowarn(avoidnoerror)}`

**Comment by gquerret** [comment]
More specifically about the exclusion: while the information that it's a DELETE OBJECT statement (and not a DELETE <record> statement), there's currently no way to specify it in the exclusion pattern.

**Comment by gquerret** [comment]
Check if adding ^STATE2 could be used for exclusion keywords.

**Comment by gquerret** [comment]
Exclusion list now support additional syntax. Still a comma-separated list, but each entry can be:
* either a single keyword (such as `FIND`)
* or keyword^modifier (such as `DELETE^OBJECT`)

Only a limited number of statement keywords have this additional modifier information:
* `CLOSE` (`QUERY`, `STORED-PROCEDURE`)
* `CREATE` (`ALIAS`, `BROWSE`, `BUFFER`, `DATABASE`, ...)
* `DDE`
* `DEFINE`
* `DELETE`
* `DISABLE`
* `INPUT`
* `OPEN`
* `OUTPUT`
* `PUT`
* `RELEASE`
* `RUN`
* `SYSTEM-DIALOG`
