### ISSUE TITLE
WHOLE-INDEX search explanation missing override

### ISSUE THREAD

**Issue by stefandrissen** [Riverside-Software/sonar-openedge#370]
When a whole index search is triggered, the help only shows:

> WHOLE-INDEX means that the selection criteria specified to search the table does not offer opportunities to use indexes that allow optimized key references (bracketed high and low values). Instead, the AVM must search the entire table using available indexes (often only the primary index) to satisfy the query, hence a WHOLE-INDEX search. Information is read from the XREF output during compilation.

I presume `{&_proparse_ prolint-nowarn(wholeindex)}` will override it as mentioned in http://www.oehive.org/prolint/rules/wholeindex

**Comment by gquerret** [comment]
This rule was in the first set, when XREF rules had no access to the AST, and thus couldn't be aware of `prolint-nowarn` directives. XREF rules now have access to the AST, so the exception can be implemented.

**Comment by maelstraggiotti** [comment]
Hi Gilles,
Any update on this enhancement availability ?

**Comment by gquerret** [comment]
Let me try to include that for the end of October release

**Comment by stefandrissen** [comment]
What happened to this? The sonarqube help text now shows how to suppress the issue:

![image](https://user-images.githubusercontent.com/5297464/79918106-142ad400-842c-11ea-88ad-1583a2b21253.png)

But suppression has not yet been implemented?

![image](https://user-images.githubusercontent.com/5297464/79918069-01180400-842c-11ea-938a-2cf666d5a9b3.png)

**Comment by gquerret** [comment]
Preprocessor statement has to be set at the statement level (so before the IF keyword).

**Comment by stefandrissen** [comment]
Thanks, I should have noticed that the suppression did have an effect on other changes I made. The combination of this change not working and this issue still being opened tricked me.
