### ISSUE TITLE
Sonar scanner The import org.prorefactor.proparse.antlr4.PreprocessorParser cannot be resolved

### ISSUE THREAD

**Issue by Razack0684** [Riverside-Software/sonar-openedge#379]
I downloaded, sonar openedge  plugin , created jar out of it and deployed to  sonar. When  I try to scan the OE project I get the error.
The import org.prorefactor.proparse.antlr4.PreprocessorParser cannot be resolved. 

Looking at the source, I don't fine PreprocessorParser package. From office network, I can't download jar file directly.

**Comment by gquerret** [comment]
Same problem was reported in #308 
You incorrectly built the JAR file, use the standard Maven target or, even better, use a JAR file from the [releases page](https://github.com/Riverside-Software/sonar-openedge/releases)
