### ISSUE TITLE
Deprecated table / field / index used 

### ISSUE THREAD

**Issue by cverbiest** [Riverside-Software/sonar-openedge#381]
A rule to detect that Deprecated/legacy tables, fields, indexes are being used.

The configuration for this rule could be done through the df file for the schema. The rule would check for the string "DEPRECATED:" at the start of the description of the table/field/index .

If code uses any of those db schema item a violation would be detected.

The actual way of configuring this rule is only an idea, any other config that could be done by supplying a list of tables/fields/indexes would work for me.

If it's unpractical to do tables  fields and indexes in one rule, the deprecated field is what I'd give priority

**Comment by gquerret** [comment]
Not really in favor of using the description of the field to configure the list.

**Comment by cverbiest** [comment]
The actual way to configure this rule does not matter too much to me.

I did see some advantages in using the description
* the configuration is done in the database schema
* it also appears in a database report
* there is no need to configure within sonar

**Comment by gquerret** [comment]
Added as a rule template, as that will allow custom description of **why** a field / index / table shouldn't be used, and what should be used instead.

![image](https://user-images.githubusercontent.com/6498723/81079900-71c12500-8ef0-11ea-96c1-5d23255ad428.png)

**Comment by cverbiest** [comment]
I there a way to mass create such rules ?
e.g. we have a field DEL-LOG that should not be used in any table. 800+ tables contain this field
or could we use a wilcard for the table name
What would be the performance impact if I create a few thousand of those rules ?

**Comment by gquerret** [comment]
One rule can be used on multiple fields, so you won't have to create thousands of rules.

**Comment by cverbiest** [comment]
@gquerret Great, looking forward to use it.

**Comment by gquerret** [comment]
Regarding the way to suppress issue, I'd be in favor of a standard declaration `{&_proparse_ prolint-nowarn(tableusage)}`, but it could be possible to specify the declaration per rule (i.e. tableusage-myrule). Thoughts ?

**Comment by gquerret** [comment]
I've added a way to specify the field name without the table name, so for the first two entries you could use 'del-log' and 'txt-id'. How much would that represent for the third list ?

The UI will let you use long list, it's just a text box.
![image](https://user-images.githubusercontent.com/6498723/81153168-f197cf80-8f82-11ea-9d00-ff68b699f43a.png)

Performance is not a problem, even with long list.

**Comment by gquerret** [comment]
Will close when merged in master...

**Comment by cverbiest** [comment]
`I'd be in favor of a standard declaration {&_proparse_ prolint-nowarn(tableusage)}`

A standard declaration is fine, I can think of some use cases for specific declarations but then I'd like to be able to control it, e.g.

rule del-log & rule txt-id would use the same {&_proparse_ prolint-nowarn(tableusage-legacy)}
some rules for fields that should only be access by framework code would be  {&_proparse_ prolint-nowarn(tableusage-framework)}

I would not want our developers to have to edit sources because of intentional use of a field that used to be flagged by one rule that is now flagged by another rule.

`I've added a way to specify the field name without the table name, so for the first two entries you could use 'del-log' and 'txt-id'. `

That will make a huge difference

`How much would that represent for the third list ?`

In our metaschema we have an indication "Legacy field", I used that to construct the list.
I will probably start with a single rule for the third list but split it into smaller groups, probably with more specific explanation for those smaller lists.

If I can save the long rule, and it does not increase our lint time dramatically I think this will be vary usefull to us.

I'll stop my comment here, because the longer I type the more ideas I get for extras that could be useful.  I'll quickly list them but just ignore them, or add a comment that I should create separate issues for those.

- a syntax to allow for all usage of a table, instead of listing all fields of the table.

- an option to only flag certain CRUD operations. e.g. allow read but report update

**Comment by gquerret** [comment]
Merged in develop

**Comment by gquerret** [comment]
> I'll quickly list them but just ignore them, or add a comment that I should create separate issues for those.

Please create separate issues !

**Comment by gquerret** [comment]
> A standard declaration is fine, I can think of some use cases for specific declarations but then I'd like to be able to control it, e.g.

The rule template gives control over the no-sonar keyword
