### ISSUE TITLE
FP: Unused variable when only used in browse definition

### ISSUE THREAD

**Issue by cverbiest** [Riverside-Software/sonar-openedge#383]
The variable WZB-TIJD is only used in `string(L_LOGHEAD.CRE-TIME, "hh:mm:ss") @ WZB-TIJD `. The variable is needed to have a name on the column widget, otherwise that column would have name = ?.

Reported violation : Unused variable `WZB-TIJD	tabinf-u.w`

```
DEFINE BROWSE browseLOGHEAD
&ANALYZE-SUSPEND _UIB-CODE-BLOCK _DISPLAY-FIELDS browseLOGHEAD W-Win _STRUCTURED
  QUERY browseLOGHEAD NO-LOCK DISPLAY
      L_LOGHEAD.CRE-DAT FORMAT "99/99/99":U
      string(L_LOGHEAD.CRE-TIME, "hh:mm:ss") @ WZB-TIJD COLUMN-LABEL "time" FORMAT "x(8)":U
      L_LOGHEAD.LOG-ACTION FORMAT "X":U
      L_LOGHEAD.CRE-WHO FORMAT "x(12)":U
      L_LOGHEAD.LOG-CONTEXT FORMAT "x(12)":U WIDTH 13
      L_LOGHEAD.PRG-NAAM FORMAT "X(256)":U WIDTH 41.57
  ENABLE
      L_LOGHEAD.CRE-DAT
/* _UIB-CODE-BLOCK-END */
&ANALYZE-RESUME
    WITH NO-ROW-MARKERS SEPARATORS SIZE 80.72 BY 13.12
         FIT-LAST-COLUMN.
```

**Comment by gquerret** [comment]
Do you mean it's a limitation from the AppBuilder ? Because using `DISPLAY
    STRING(tt.fld1, "hh:mm:ss") COLUMN-LABEL "zzz" FORMAT "x(8)":U` works correctly.

**Comment by cverbiest** [comment]
It's a limitation of the browse, not the appbuilder.

For a variable or expression displayed without @  the column is added but it has NAME = ? .
When walking the widget-tree of the browser it's not possible to identify those columns.

If `myvariable @ myvariable` is used the column widget name will be "myvariable".

**Comment by gquerret** [comment]
Existing option `skipVarInFrames` has to be checked to skip those variables.
