### ISSUE TITLE
Unused buffer

### ISSUE THREAD

**Issue by movedoa** [Riverside-Software/sonar-openedge#395]
![grafik](https://user-images.githubusercontent.com/13309951/30971702-fa08e4cc-a468-11e7-9d64-5700e6d5a17d.png)

**Comment by movedoa** [comment]
![grafik](https://user-images.githubusercontent.com/13309951/30973505-9314210a-a46d-11e7-8034-9e58b5b012a5.png)

I found another case. Should i create a new bug for this?

**Comment by gquerret** [comment]
Fixed in develop branch
