### ISSUE TITLE
REPLACE PUBLIC VARIABLE false positive

### ISSUE THREAD

**Issue by hdaum** [Riverside-Software/sonar-openedge#40]
If my class has a property defined like

`DEFINE PUBLIC PROPERTY myProperty AS INTEGER NO-UNDO GET. PRIVATE SET.`

it is causing the following code smell to be report `Replace public variable myProperty by property`.

**Comment by gquerret** [comment]
Reproduced

**Comment by gquerret** [comment]
Fixed
