### ISSUE TITLE
Shared lock record access

### ISSUE THREAD

**Issue by movedoa** [Riverside-Software/sonar-openedge#414]
![grafik](https://user-images.githubusercontent.com/13309951/31385920-4690f61c-adc5-11e7-9a3a-b762308cc27a.png)

"LOCKing for PRESELECTed records must be specified on the header statement for the PRESELECT block, and cannot be changed by subordinate FIND NEXT, PREV,etc.

**Comment by gquerret** [comment]
Fixed in develop
