### ISSUE TITLE
Keyword casing

### ISSUE THREAD

**Issue by movedoa** [Riverside-Software/sonar-openedge#420]
The DevStudio has a warning for lower case keywords.
But it looks like this is a feature of the DevStudio and not the compiler so the Compiler Warning rule does not catch this.

I guess a generic keyword casing rule would be nice since some people use lower case keywords for some reason ;-)

**Comment by gquerret** [comment]
> I guess a generic keyword casing rule would be nice since some people use lower case keywords for some reason ;-)

Flame war started !

**Comment by gquerret** [comment]
Two rules added. None of those rules are activated by default due to the very high number of issues which could be raised.
