### ISSUE TITLE
false positive Unused buffer (when a before-table is defined)

### ISSUE THREAD

**Issue by jurjendijkstra** [Riverside-Software/sonar-openedge#429]
Unused buffer btExCheck, from statement:

define temp-table ttExCheck no-undo before-table btExCheck
   field ......

I admit that btExCheck is not used specifically in the sourcecode, but this temp-table is part of a dataset and the before-image functionality of the dataset is actually used.
So, I think it would be nice if the "unused buffer" rule could make an exception for before-tables?

**Comment by gquerret** [comment]
Already reported in #395
But as that was a comment of another (quite) related issue, we'll keep this issue for further reference.

**Comment by gquerret** [comment]
Fixed in master
