### ISSUE TITLE
"UNDO, THROW e." creates false positive in constructor

### ISSUE THREAD

**Issue by movedoa** [Riverside-Software/sonar-openedge#43]
It will be marked as "Usage of default buffer" with some random(i guess the first in the db) table name

![error](https://cloud.githubusercontent.com/assets/13309951/17432089/9fb2e21c-5afd-11e6-8bd2-8a46069fce5f.PNG)

**Comment by gquerret** [comment]
Found another issue in the parser while creating the test case. I *guess* both issues are related, but I'm not sure at this stage.

**Comment by gquerret** [comment]
About previous comment : issues were not related.
`CATCH` statement define an inline variable in proparse.g, but not in TreeParser01.g, so the tree parser think that the variable is something abbreviated (not sure about that, didn't go so far, but at least it doesn't know the variable and tries to go to table names).
Fix is to correctly declare an action in catch statement, and have the variable limited to the scope of the catch block.

**Comment by gquerret** [comment]
Fix included in master
