### ISSUE TITLE
new property for include file suffixes (extending sonar.oe.file.suffixes)

### ISSUE THREAD

**Issue by mimo74** [Riverside-Software/sonar-openedge#431]
Default behavior is to scan files with the extensions: p, i, w and cls. If a file has a .i extension, only metrics are checked, otherwise it is considered to be a procedure and the full check is executed.
For customization of extensions with `sonar.oe.file.suffixes` it would be better to be able to configure include files suffixes in a seperate suffixes property so one can exclude additional include files types from the full scan. At the moment everything added there is considered to be a full procedure.

**Comment by gquerret** [comment]
Property `sonar.oe.include.suffixes` added, available in master
