### ISSUE TITLE
SonarLint On-The-Fly fails with version 2.1.3?

### ISSUE THREAD

**Issue by jurjendijkstra** [Riverside-Software/sonar-openedge#433]
Hi Gilles, I have just installed the 2.1.3 files (and fresh license) into the sonarqube instance and now the SonarLint in Eclipse fails. 
There are several error messages in the SonarLint Console (in Eclipse). 

SonarLint for Eclipse is version 3.0.999.  Should it get an upgrade?

**Comment by gquerret** [comment]
Could you attach the messages ?

**Comment by gquerret** [comment]
And did you update the project bindings ?

**Comment by jurjendijkstra** [comment]
Sure I have updated the project bindings several times and restarted Eclipse several times, I have even rebooted my PC. 

And suddenly, after the lunchbreak, it works again. 
I guess the system was just hungry.

Sorry for the false alarm.
