### ISSUE TITLE
proparse error "Type option of SUBSTRING function is not yet supported"

### ISSUE THREAD

**Issue by jurjendijkstra** [Riverside-Software/sonar-openedge#434]
Since update 2.1.3 we get new issues from the proparse.error rule.
The issue caption is "Type option of SUBSTRING function is not yet supported".

The source-code that causes this is:
```
&IF substring('{&and_calculatietype}', 24, 1, 'character':U) = '4':U &THEN
```

**Comment by gquerret** [comment]
Some preprocessor expressions were not correctly evaluated previously, and it seems there's still work to be done... How many errors of this kind did you get ?

**Comment by jurjendijkstra** [comment]
We got only 2 of these errors so it it absolutely no problem, I can simply remove that 'character' option in a minute. I just figured you might be interested to know about the new proparse error.

**Comment by gquerret** [comment]
I'm interested in this issue, don't change your code. I'll have a look next week.

**Comment by gquerret** [comment]
Fixed in master
