### ISSUE TITLE
FPs with TEMP-TABLE and "FOR statement using TABLE-SCAN and WHERE options" rule

### ISSUE THREAD

**Issue by movedoa** [Riverside-Software/sonar-openedge#435]
Seems the rule doesnt work correctly with TEMP-TABLEs

![grafik](https://user-images.githubusercontent.com/13309951/32166776-2b311dd2-bd67-11e7-9437-814923176f3e.png)

**Comment by gquerret** [comment]
Will try to reproduce ASAP.

**Comment by gquerret** [comment]
Fixed in master
