### ISSUE TITLE
Use uppercase keyword

### ISSUE THREAD

**Issue by movedoa** [Riverside-Software/sonar-openedge#436]
![grafik](https://user-images.githubusercontent.com/13309951/32166899-94ff5b16-bd67-11e7-9b5b-8f55c249c32d.png)
--------------------------
![grafik](https://user-images.githubusercontent.com/13309951/32166912-9c646f04-bd67-11e7-82c7-cd724ade728f.png)
--------------------------
![grafik](https://user-images.githubusercontent.com/13309951/32166935-aaa36fe8-bd67-11e7-95f9-6594a7505f0b.png)
--------------------------

There are many more cases, but i guess this is the same bug every time.

**Comment by gquerret** [comment]
Oops, I more or less knew this version was released too early, but the rule hasn't been correctly tested...

**Comment by gquerret** [comment]
Fixed in master
