### ISSUE TITLE
proparse error

### ISSUE THREAD

**Issue by WayneHanson** [Riverside-Software/sonar-openedge#438]
We are getting a proparse error on a new program. I have attached the error and program.

Is there anything in the program that could be causing this?

![message](https://user-images.githubusercontent.com/6498723/32430520-ef53942a-c2cf-11e7-9792-9f17e4cafc43.png)

[essSalesProgSearch.zip](https://github.com/Riverside-Software/sonar-openedge/files/1440904/essSalesProgSearch.zip)

**Comment by gquerret** [comment]
Looks like your file has an invalid character at line 328 position 9, probably not matching the codepage.
The file in the ZIP file seems correct however. Are you it's the right one ? From the right branch ?

**Comment by gquerret** [comment]
Were you able to have a look at the code ?

**Comment by gquerret** [comment]
Fixed by customer
