### ISSUE TITLE
new shared variable - unable to override warning

### ISSUE THREAD

**Issue by stefandrissen** [Riverside-Software/sonar-openedge#447]
There is no help text for the warning, but a scan of the sources in this repository led to 

https://github.com/Riverside-Software/sonar-openedge/blob/4c323097018d7fc0ce13661758de07cf3471214e/proparse/src/test/resources/data/nowarn.p

So I tried:
````
{&_proparse_ prolint-nowarn(shared)}
DEFINE NEW GLOBAL SHARED VARIABLE gs AS INT64 NO-UNDO.
````

But the warning is still generated.

**Comment by gquerret** [comment]
I confirm there's no way no override warning as of today. The test case is specific to proparse, and not to the Sonar rule. That will be fixed in next release.

**Comment by gquerret** [comment]
Fixed in master
