### ISSUE TITLE
linemarkers in Eclipse

### ISSUE THREAD

**Issue by jurjendijkstra** [Riverside-Software/sonar-openedge#449]
Hi Gilles,
Just a question.... during the SonarLint demo in Prague I noticed that your code-editor in Eclipse showed beautifull little linemarkers for SonarLint issues, with a tooltip showing the warning text.

While in our own workspace the code-editor only underlines the lines that have a warning. The underlining is waved, blue. And there are no tooltips, so we have to work with the "SonarLint on the fly" view to figure out what the warnings are.
We are using OpenEdge 11.7 with its own default Eclipse.

Did you use a different editor, or perhaps some configurations to enable the line markers with tooltips?

Thanks,
Jurjen

**Comment by gquerret** [comment]
You just have to open the preferences, section General > Editors > Text editors > Annotations, and modify the properties of SonarLint annotations. Enjoy !

<img width="738" alt="pdsoe" src="https://user-images.githubusercontent.com/6498723/33326970-b08dfc56-d456-11e7-83a1-5c33f2023a6e.png">

**Comment by jurjendijkstra** [comment]
Excellent, thanks!!
Good one for the Wiki ;-)
