### ISSUE TITLE
GUID function causing "Default Buffer Usage" error

### ISSUE THREAD

**Issue by daumheath** [Riverside-Software/sonar-openedge#45]
The following code is causing a Default Buffer Usage error.
`REPLACE(GUID, "-", "")`

**Comment by gquerret** [comment]
Do you have a table or field name starting with GUID ?

**Comment by hdaum** [comment]
yes, there is a field named GUID.

**Comment by gquerret** [comment]
Reproduced. The parser is using first the field name instead of the GUID statement, thus reporting the issue.

**Comment by movedoa** [comment]
This bug creates hundets of false positives in my code, will this be fixed in the near future?

**Comment by gquerret** [comment]
Fix won't be included in next version (end of this week), but we can raise the priority for the next version.

**Comment by movedoa** [comment]
Would be very nice, thx

**Comment by gquerret** [comment]
Does that affect other keywords too ?

**Comment by gquerret** [comment]
Finally fixed in master!
