### ISSUE TITLE
Proparse error on prefixed virtual table reference

### ISSUE THREAD

**Issue by maelstraggiotti** [Riverside-Software/sonar-openedge#450]
Hi,

Referencing a virtual table, such as _lock, using the database name prefix raises an "Unknown table name" issue. 
```
FIND _lock.         /* OK */
FIND MyDb._lock.    /* KO */
```
Thanks

**Comment by stefandrissen** [comment]
Both work fine for me (using SonarQube Ant Task version 2.5)

If I remove the df file for the database from the sonar.oe.databases property then I (correctly) get:

````
[sonar:sonar] Error during code parsing for internal/sonar/test-coverage.p
[sonar:sonar] antlr.SemanticException: C:\tfs\ef72\4\work\other\internal\sonar\test-coverage.p:4: Unknown table name: exactcs._lock
````

**Comment by gquerret** [comment]
I can't reproduce too, both in SonarLint and with the Ant task.
What is the version you're using, and the `sonar.oe.databases` and `sonar.oe.aliases` values ?

**Comment by maelstraggiotti** [comment]
Sorry, I forgot to specify that it occurs in SonarLint, using 2.1.3 (and still SonarLint 3.0.999).

Actually, I also have an issue with non virtual tables . 
```
FIND _lock.         /* OK */
FIND Che.           /* OK */
FIND mydb.Che.*/    /* KO */
FIND mydb._lock.    /* KO */
```
where ```sonar.oe.aliases=mydb``` 
the DF contains "che" table.

**Comment by gquerret** [comment]
And what's the value of `sonar.oe.databases` ?

**Comment by maelstraggiotti** [comment]
It points to the full DF of our database.

**Comment by gquerret** [comment]
If you have `sonar.oe.databases=path/to/dbname.df` then you need to specify `sonar.oe.aliases=dbname,mydb` (and not just `mydb`)

**Comment by maelstraggiotti** [comment]
Ok, I found the problem. The DF file name didn't reflect the database name (was dbname_schema.df). SonarLint seems sensitive to that; it doesn't cause problems with the PCT analysis.

**Comment by gquerret** [comment]
By PCT analysis, you mean SonarQube scanner ? Or something else in the build process ?

**Comment by maelstraggiotti** [comment]
Yes, I meant Ant-task SQ scanner, PCT has nothing to do with that.

**Comment by gquerret** [comment]
Then you should have the same problem, DB name is based on the DF file name, and same code is being executed in SonarLint and SonarScanner. There's probably a small difference in the config.

**Comment by maelstraggiotti** [comment]
Indeed. For the record, ANT uses the "dbname_schema.df:MyDb" syntax to specify the database name.
