### ISSUE TITLE
wish: warning when selected index changes

### ISSUE THREAD

**Issue by jurjendijkstra** [Riverside-Software/sonar-openedge#464]
I have this wish and I doubt if it is even possible. Perhaps you or anyone else has an idea....

There is a FOR EACH statement in our sourcefile and Progress selects an index at compile-time. The compiler selects index idx1 and that's cool, the program performs pretty good and the table hit ratio at runtime is reasonably high.

Then there is an OpenEdge upgrade (from 11.6 to 11.7). After a while customers complain that  performance has decreased and we don't know why. With a lot of searching and with some luck we notice that this same FOR EACH now uses index idx2 (apparently the index selection algoritms in 11.7 are different). Index idx2 is a bad choice in this particular case, it scans millions of records before it finds the 5 records that really matter. We did not notice in our tests because we don't have millions of records.
Man, that was annoying.

I do not think that Sonar can judge if OpenEdge has selected the best index, but it would be so cool if it could.
But what I would like very much is an alert, warning me that OpenEdge now selected a different index than before. 

As I said I doubt if it is even possible. I do not think that there is a Progress compiler switch that would use the older index selection algorithms too, to compare the different outcome.

What we might try, theoretically, is to compile (with xref) the sources with version 11.6 and also with 11.7 and compare the xrefs. And then feed the differences to a (new) rule so that they show up in SonarQube.

Well, thank you for reading this so far. 
Have a nice weekend,
Jurjen.

**Comment by gquerret** [comment]
For now, Sonar can't report if the index is being used, there are too many parameters here.
Given the architecture of SonarQube and the way files are analyzed, it would mean compiling twice and comparing XML XREF. Not something impossible, but that will be cumbersome, and will take time.

Issue #100 is already about matching indexes from XREF to the source code. This has not yet been implemented however.

**Comment by gquerret** [comment]
And do you have an example of how this behavior can occur ? Or a KB article ?

**Comment by jurjendijkstra** [comment]
In the following example, 11.7 selects index key2 but 11.6 selects index key1.
Key1 is a good choice but key2 is bad.

code snippet
```
define variable lSearchByGroupas logical no-undo.
define variable cDoelGroep as character no-undo.
define buffer buf_telnr for mtc_telnr.

  for each buf_telnr
     where buf_telnr.bedr     = mtc_telnr.bedr
       and buf_telnr.rel      = mtc_telnr.rel
       and buf_telnr.persoon  = mtc_telnr.persoon
       and buf_telnr.tel_type = mtc_telnr.tel_type
       and (lSearchByGroup = false or (lSearchByGroup and buf_telnr.doelgroepen contains cDoelGroep))
     no-lock:
     ....
  end.
```
Quick Index Report for table mtc_telnr :

```
Flags Index Name              St Area Cnt Field Name
----- ----------------------- ------- --- ----------------------
      createdOn               7         1 + createdOn

p     key1                    7         4 + bedr
                                          + rel
                                          + persoon
                                          - tel_hoofd

w     key2                    7         1 + doelgroepen

u     KeyIdNr                 7         1 + IdNr

      lastChange              7         1 + lastChange

```

**Comment by stefandrissen** [comment]
If https://knowledgebase.progress.com/articles/Article/21099 can be believed - shouldn't both indexes be used in this case? Or is the logical variable throwing a spanner in the index selection?

**Comment by jurjendijkstra** [comment]
Thanks Stefan.
IF the kb can be believed, that's a big IF. Paul Koufalis and Peter Judge did a presentation together in Prague saying that these algorithms get tweaked and updated between Progress versions and they do it mostly undocumented. They presented some cases where the algorithms selected indexes that a human would not expect.

Anyway my concern here is not primarily that the wrong index is selected, but that a different index is selected than in the previous version. My assumption (optimistic, indeed) is that when a programmer creates new sourcecode he truly inspects the indexes and knows that the best ones are selected. It is a bummer when after an OpenEdge upgrade suddenly different indexes are selected. 

I have given it some thought and now see that it is not a question for SonarQube. Instead when we do an OpenEdge upgrade we should simply test that moment: compile xref the entire codebase with the old OpenEdge version, then compile xref that same codebase with the new OpenEdge version, filecompare both xrefs and look for interesting changes. 
That does not have to be done continuously or nightly, the way we use SonarQube. Only sporadically when we update OpenEdge.

**Comment by gquerret** [comment]
I thought about it during the week-end, and didn't find a way to display this kind of information correctly in SQ, it's not the right tool for that. However, it would be quite easy to generate this kind of report in Jenkins when you create new releases, so that you'd be able to compare what's happening between each of your releases, and between OE releases.
