### ISSUE TITLE
TABLE-SCAN and WHERE - nested query

### ISSUE THREAD

**Issue by movedoa** [Riverside-Software/sonar-openedge#465]
![grafik](https://user-images.githubusercontent.com/13309951/34098949-4d01a70e-e3de-11e7-850f-e38c5acfc0d5.png)

I am not 100% sure if this is an error.
But my guess is that each query counts seperate for the engine so this should be correct?
Maybe someone with a deep understanding of the db has an answer if this is correct or not.

**Comment by gquerret** [comment]
I'd say that each query should probably be treated separately. Will also ask DB experts.

**Comment by movedoa** [comment]
I asked around and it seems we are correct, the queries are seperate

**Comment by gquerret** [comment]
Fixed in upcoming 2.1.5
