### ISSUE TITLE
Preprocessor in include - proparse error

### ISSUE THREAD

**Issue by movedoa** [Riverside-Software/sonar-openedge#466]
All these issues are new with 2.1.4
I guess this is all the same bug

![grafik](https://user-images.githubusercontent.com/13309951/34100950-6b2d3710-e3e4-11e7-98a1-e284868d8205.png)

----------------------------------

![grafik](https://user-images.githubusercontent.com/13309951/34101006-9a99afc4-e3e4-11e7-862a-d64278b0dde3.png)

----------------------------------

![grafik](https://user-images.githubusercontent.com/13309951/34101032-a826a4d0-e3e4-11e7-86ee-8a9abfee4cb5.png)

**Comment by gquerret** [comment]
I think that may come from the new `sonar.oe.include.suffixes` (see [wiki](https://github.com/Riverside-Software/sonar-openedge/wiki/Property-list)). Would you mind testing with `sonar.oe.include.suffixes=i,I` ? The list is case sensitive, and it shouldn't.

**Comment by movedoa** [comment]
That fixed the issue

**Comment by gquerret** [comment]
That's a temporary workaround, I've created #468 to fix the problem
