### ISSUE TITLE
unexpected token: THIS-OBJECT with CREATE SOCKET

### ISSUE THREAD

**Issue by movedoa** [Riverside-Software/sonar-openedge#47]
The following code creates the error:
(I have this line in a constructor of a class.)

CREATE SOCKET THIS-OBJECT:hHandle.

**Comment by gquerret** [comment]
Fixed in branch Issue47, merged in master soon

**Comment by gquerret** [comment]
Merged in master
Yes, there may still be other CREATE xxx issues with THIS-OBJECT...
