### ISSUE TITLE
Track comments matching a regular expression

### ISSUE THREAD

**Issue by mimo74** [Riverside-Software/sonar-openedge#471]
a rule template just like the one available for java:

```
Track comments matching a regular expression
This rule template can be used to create rules which will be triggered when a comment matches a given regular expression.

For example, one can create a rule with the regular expression .*REVIEW.* to match all comment containing "REVIEW".

Note that, in order to match REVIEW regardless of the case, the (?i) modifier should be prepended to the expression, as in (?i).*REVIEW.*.
```

that would help us track down unwanted / questionable comments in the source code

**Comment by gquerret** [comment]
@mimo74 Which rule ID is it ?

Currently, there's a TODO rule available for OpenEdge, agree it could be extended for more keywords. This however can easily be time-consuming, something to be careful during development.

**Comment by gquerret** [comment]
Found it, `squid:S124`

**Comment by gquerret** [comment]
Merged in develop
