### ISSUE TITLE
UseIndex should not flag Find first/last statements

### ISSUE THREAD

**Issue by cverbiest** [Riverside-Software/sonar-openedge#476]
This may cause some debate, so it's probably best configurable, e.g. by adding an exclude first/last option on the rule. 

A find first / last needs a use-index to indicate in which order the first or last record must be taken.

USE-INDEX keyword (rssw-oe-main:eu.rssw.antlr.proparse.checks.UseIndex) now flags the code below.
Without the use-index the effect of the code may change if somebody defines extra indexes on Order

    FIND LAST Order
        WHERE Order.CustNum = Customer.CustNum
        USE-INDEX CustOrder
        NO-LOCK NO-ERROR.

**Comment by gquerret** [comment]
Included in upcoming 2.1.5 (new parameter controls the behavior)
