### ISSUE TITLE
Detect nesting of DO i = ... loops with same counter variable

### ISSUE THREAD

**Issue by mikefechner** [Riverside-Software/sonar-openedge#477]
Implement a rule to detect this as a bug:

```
DO i = 1 TO 10:
   DO i = 1 TO 20:
   END.
END.
```

Criteria is nesting and the use of the same loop counter variable (i in that sample).

**Comment by mikefechner** [comment]
Indeed @gquerret , the rule we spoke about on the phone this afternoon is already in the backlog. To my defense not only since a few weeks....

**Comment by gquerret** [comment]
Rule added in develop branch, will be part of next release
