### ISSUE TITLE
Use SEARCH instead of FILE-INFO:FILE-NAME/FILE-INFO:FULL-PATHNAME

### ISSUE THREAD

**Issue by movedoa** [Riverside-Software/sonar-openedge#480]
If FILE-INFO:FILE-NAME is only used only for FULL-PATHNAME than SEARCH should be used
SEARCH is ~60% faster in my benchmarks.

If other attributes of FILE-INFO  (FILE-TYPE,FILE-CREATE-TIME...) are used, it is still valid and should not be marked as an issue.

**Comment by gquerret** [comment]
I'm not sure that will always work. FILE-INFO:FILE-NAME will try to find either an absolute file (no problem here) or a relative path, relative to the current work directory. But SEARCH will only look for files in the PROPATH, so if `.` is not present there, that will lead to a different result.

**Comment by movedoa** [comment]
Fair enough, didn't think about that.
