### ISSUE TITLE
Unable to lex file with multiline VIEW-AS/DESCRIPTION and a blank like

### ISSUE THREAD

**Issue by braun1928** [Riverside-Software/sonar-openedge#497]
I'm trying to run on our existing codebase, and I got this error right in the beggining:

08:59:49.479 DEBUG: DF syntax highlight on dump/movfis.df
08:59:49.582 DEBUG: 'dump/movfis.df' generated metadata  with charset 'IBM850'
08:59:49.586 ERROR: Unable to lex file dump/movfis.df
java.lang.IllegalArgumentException: 21 is not a valid line offset for pointer. File dump/movfis.df has 1 character(s) at line 2959
        at org.sonar.api.internal.google.common.base.Preconditions.checkArgument(Preconditions.java:145)

Line 2959 is the empty one right before the include:

ADD FIELD "idi-orig-proces" OF "dwf-apurac-impto-arrecadac" AS integer 
  FORMAT ">9"
  INITIAL "1"
  LABEL "Origem Processo"
  POSITION 13
  MAX-WIDTH 4
  VIEW-AS "view-as radio-set horizontal radio-buttons

{fiinc/i01fi257.i 2}"

Same thing has happened with other .df files, most of them comes from our ERP vendor. Running plugin version 2.1.5.

**Comment by stefandrissen** [comment]
Look at the line breaks - if they are mixed (ie CRLF and LF) the lexer does not like them (we had this with our source code which had gone through some automated updates that didn't care about CRLF and only inserted LF)

**Comment by braun1928** [comment]
Awesome! That was it! Never thought data admin would do such a thing when dumping.
Thanks!
