### ISSUE TITLE
XREFSensor fails with Fatal Error with non printable character in code

### ISSUE THREAD

**Issue by movedoa** [Riverside-Software/sonar-openedge#5]
The xref import fails when there is a non printable character in a string.
For example:

`cTest = '~002&1':U:U.`

It seems that the output from pct (or the openedge compiler i guess) is not properly escaped.

This is the line from the xref that produces the error:
`<Reference Reference-type="STRING" Object-identifier="&amp;1">`

**Comment by jakejustus** [comment]
To be reported to Progress tech support, the XML-XREF option doesn't generate a valid XML file in this case, so it's impossible to parse it.
