### ISSUE TITLE
Variable used but not assigned a value

### ISSUE THREAD

**Issue by stefandrissen** [Riverside-Software/sonar-openedge#507]
Today I found the result of an incomplete refactor. Similar to the rule 'variable assigned but never used', there could be 'used but never assigned'

```
define variable cc as character no-undo.

if lookup( "abc":u, cc ) > 0 then 
   return true.
```

**Comment by gquerret** [comment]
Yes, interesting rule !

**Comment by gquerret** [comment]
Rule merged in develop
