### ISSUE TITLE
Rule: string ( longchar )

### ISSUE THREAD

**Issue by stefandrissen** [Riverside-Software/sonar-openedge#508]
Since a longchar theoretically does not fit in a string, this is waiting for a run-time 'Attempt to exceed maximum size of a CHARACTER variable. (9324)'

````
DEFINE VARIABLE lcc AS LONGCHAR NO-UNDO.

RUN bar ( STRING( lcc ) ).

PROCEDURE bar PRIVATE:
   DEFINE INPUT PARAMETER i_c AS CHARACTER NO-UNDO.

   MESSAGE i_c VIEW-AS ALERT-BOX.

END PROCEDURE.
````

An override preprocessor should also be made available to explicitly mark "innocent" users as safe.

**Comment by gquerret** [comment]
Included in VariableOverflow rule, see #838
