### ISSUE TITLE
sonarqube does not scan all issues in one scan and showing old issue in leak period 

### ISSUE THREAD

**Issue by sangeetapremani** [Riverside-Software/sonar-openedge#519]
The image is showing there are 7 new issues from May 18, 2018  to May 21, 2018 . 
When we open a issue it shows created 3 days ago while the check in date is 2 years back i.e 02/24/2016

This is happening in Sonarqube 6.7.X version.

![sonar3](https://user-images.githubusercontent.com/39480347/40296874-9feff92a-5cfb-11e8-9569-9aae04eb21d4.JPG)
![sonar1](https://user-images.githubusercontent.com/39480347/40296883-a36fd5ac-5cfb-11e8-9d27-7f4e30d09584.JPG)

**Comment by gquerret** [comment]
How does this issue relate to the OpenEdge plugin ?
