### ISSUE TITLE
OpenEdgeDBSensor does not use sonar.oe.databases property

### ISSUE THREAD

**Issue by movedoa** [Riverside-Software/sonar-openedge#523]
It seems the OpenEdgeDBSensor imports all df files that it can find in the source directory.
But imho it should only import the full dfs that I set in sonar.oe.databases.
Is this a bug or expected behaviour?

**Comment by gquerret** [comment]
It is the expected behavior, as a file has to be present in sonar.sources property to be visible in SQ.

**Comment by movedoa** [comment]
Ok thx, i can work around that
