### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by silvasmarcus** [Riverside-Software/sonar-openedge#524]
Hi,

We are looking to use the sonar-openedge plugin for sonarqube.

The installation of the plugin we have already done.

I also installed the sonar-scanner and am sending the properties attached.

Some doubts:

1) Is it mandatory to use PCT? Or we can use the standard OpenEdge compile and put the compiled files (eg r-code) propertie sonar.oe.binaries

19:02:00.167 DEBUG: Listing file for 'change/acesso.p' not found or contains space character - Was looking for '/Users/anderson/Softvaro/sonar/hdi/compile/.pct/acesso.p'

2) It is mandatory to set the properties sonar.oe.dlc and sonar.oe.propath.dlc

3) Is it mandatory to inform the DF files or is there a way to connect to the database?

4) What is the sonar.oe.proparse.debug property for?

**Comment by gquerret** [comment]
> Is it mandatory to use PCT? Or we can use the standard OpenEdge compile and put the compiled files (eg r-code) propertie sonar.oe.binaries

You don't have to use PCT, but that's highly recommended as some rules require files generated by PCT, such as all compiler warnings rules, or XREF and listing based rules. 

> It is mandatory to set the properties sonar.oe.dlc and sonar.oe.propath.dlc

Not mandatory, but if you rely for example on adecomm/ include files, they'd have to be present in sonar.oe.propath if you don't use sonar.oe.dlc. Those sonar.oe.dlc.* properties will just inject $DLC/gui and $DLC/tty in your propath.

> Is it mandatory to inform the DF files or is there a way to connect to the database?

OpenEdge analysis can't connect to databases, and has to rely on DF files to read the schema. They can be generated by PCTDumpSchema.

> What is the sonar.oe.proparse.debug property for?

That will generate a text version of the AST. Useful for debug...

**Comment by silvasmarcus** [comment]
Through the compiler I use today, I'm generating XREF XML, dbg file and lst file. Which scanner property should I report these files to?

Does not this eliminate the need to use PCT?

Does the PCT need the OpenEdge binaries?

**Comment by gquerret** [comment]
There are currently no properties to specify the location of XREF XML, naming conventions are "hardcoded" in the OpenEdge plugin.  

Yes, PCT requires the OpenEdge binaries, it's a wrapper for OpenEdge related tasks (and included in OpenEdge since 11.7.3).

**Comment by gquerret** [comment]
You'd have to follow the naming conventions used by PCT:

- Warning file name: https://github.com/Riverside-Software/sonar-openedge/blob/develop/openedge-plugin/src/main/java/org/sonar/plugins/openedge/foundation/OpenEdgeSettings.java#L393

- XREF file name: https://github.com/Riverside-Software/sonar-openedge/blob/develop/openedge-plugin/src/main/java/org/sonar/plugins/openedge/foundation/OpenEdgeSettings.java#L400

- Listing file name: https://github.com/Riverside-Software/sonar-openedge/blob/develop/openedge-plugin/src/main/java/org/sonar/plugins/openedge/foundation/OpenEdgeSettings.java#L407

- Warnings file format: https://github.com/Riverside-Software/pct/blob/master/src/progress/pct/compile.p#L394

- XREF have to be in XML format

**Comment by silvasmarcus** [comment]
Thank you gquerret.

Why does the scanner look for the apcvat.p file in ".pct / apcvat.p"?

Should not you just look at the sonar.sources property?

Another question, if it does not have the compiled files, what rules will not be possible to be used from the plugin?

Log:
23: 53: 31.979 DEBUG: Parsing change / apcvat.p
23: 53: 31.979 DEBUG: Listing file for 'change / apcvat.p' not found or contains space character - Was looking for '/Users/anderson/Softvaro/sonar/hdi/compile/.pct/apcvat.p'

**Comment by silvasmarcus** [comment]
Can webspeed htmls files also be scanned?

**Comment by gquerret** [comment]
> Why does the scanner look for the apcvat.p file in ".pct / apcvat.p"?
> Should not you just look at the sonar.sources property?

Listing files use this naming convention

> Another question, if it does not have the compiled files, what rules will not be possible to be used from the plugin?

Code coverage functionality requires compiled files. I don't have the list of rules available right now, that would currently only be a few (I probably have enough fingers to count them).

> Can webspeed htmls files also be scanned?

HTML files can't be parsed directly, but you can analyze the result of e4gl-gen.p

**Comment by silvasmarcus** [comment]
Mas precisa colocar o código fonte apcvat.p no diretório .pct na propriedade dos binários (.pct / apcvat.p) ?

O que eu perco se este código fonte não estiver no diretório .pct ?

O log de debug abaixo faz eu perder alguma regra de ser analisada ?

23: 53: 31.979 DEBUG: Listing file for 'change / apcvat.p' not found or contains space character - Was looking for '/Users/anderson/Softvaro/sonar/hdi/compile/.pct/apcvat.p'

**Comment by gquerret** [comment]
Structure should be:

```
sonar.sources
  \_ dir1
      \_ proc.p (source code, required)

sonar.oe.binaries
  \_ dir1
      \_ proc.r (rcode, optional, no code coverage if not present)
  \_ .pct  (everything being generated by PCT)
       \_ dir1
           \_ proc.p.warnings (warnings file, optional, no compiler warning reported if not present)
           \_ proc.p (listing file, optional, rule LargeTransactionScope not reported if not present)
           \_ proc.p.xref (XREF, optional, all XREF rules not executed if not present)
```

**Comment by silvasmarcus** [comment]
Thank you gquerret.

Can you tell me the rules that use warnings file, xref file, listing file?

How do I use the OpenEdgeDB Sonar way (extended) profile?

**Comment by gquerret** [comment]
> Can you tell me the rules that use warnings file, xref file, listing file?

You can filter them by tag (`compiler-warnings` and `xref`)

> How do I use the OpenEdgeDB Sonar way (extended) profile?

Please have a look at the quality profiles documentation: https://docs.sonarqube.org/display/SONAR/Quality+Profiles
