### ISSUE TITLE
Performance issues when scanning with multiple "else if" within an assignment

### ISSUE THREAD

**Issue by sbbe83** [Riverside-Software/sonar-openedge#526]
I have been trying to configure our existing source to use code analysis with and I ran into an issue with it. When running code like the below sample code through the Sonar Scanner the scanner takes exponentially longer to run the more `else if` statements are in the assignment. The full project took 14 hours to run which just isn't going to work.

When I looked into the logs the files that seemed to take the longest were files with this sort of code in it. I was able to exclude some of them during a scan which brought down the time to around 2 hours but I am going to be chasing this for a while to get it to run in a reasonable time and I would like to include them in the scan. 

Here are the times I tested on a sample project with nothing other than this sample code below. The first number is the number that myvar gets assigned to. 
21 = 8178ms
22 = 15546ms
23 = 30421ms

Setting `sonar.oe.skipProparse=true` will make this go away but from what I am seeing no rules really get used but I haven't tested this enough to know if this is a true workaround or not. It seems like the issue is with Propase but not 100% sure.

**Tested with:**
SonarQube version 6.7.4 (build 38452)
Sonar Scanner version 3.2.0.1227
sonar-openedge-plugin-2.1.5.3.jar
riverside-rules-plugin-2.1.5.jar. 

**Sample Code:**
`def var myvar as char no-undo.`
`def var myvar2 as char no-undo init "3".`

`myvar = if myvar2 = "1" then "1"`
`        else if myvar2 = "2" then "2"`
`        else if myvar2 = "3" then "3"`
`        else if myvar2 = "4" then "4"`
`        else if myvar2 = "5" then "5"`
`        else if myvar2 = "6" then "6"`
`        else if myvar2 = "7" then "7"`
`        else if myvar2 = "8" then "8"`
`        else if myvar2 = "9" then "9"`
`        else if myvar2 = "10" then "10"`
`        else if myvar2 = "11" then "11"`
`        else if myvar2 = "12" then "12"`
`        else if myvar2 = "13" then "13"`
`        else if myvar2 = "14" then "14"`
`        else if myvar2 = "15" then "15"`
`        else if myvar2 = "16" then "16"`
`        else if myvar2 = "17" then "17"`
`        else if myvar2 = "18" then "18"`
`        else if myvar2 = "19" then "19"`
`        else if myvar2 = "20" then "20"`
`        else if myvar2 = "21" then "21"`
`        else "0".`

**Log Message:**
`09:31:38.716 DEBUG: Parsing src/testSonarQube.p`
`09:31:38.723 DEBUG: Listing file for 'src/testSonarQube.p' not found or contains space character - Was looking for 'D:\vsi\Workspace\SonarTest\.pct\testSonarQube.p'`
`09:32:09.145 DEBUG: 30421 milliseconds to generate ParseUnit`

**Comment by gquerret** [comment]
For your information, the new ABL code parser (which will be available in the coming months) doesn't have problems with recursive rules anymore, and this kind of construct is parsed in the same amount of time as any other code.
Closing issue for now, as that won't be fixed in the current code parser.
