### ISSUE TITLE
Abbreviated keyword RCODE-INFO

### ISSUE THREAD

**Issue by movedoa** [Riverside-Software/sonar-openedge#534]
"Abbreviated keyword RCODE-INFO for RCODE-INFORMATION"

For some reason it still works even with RCODE-INFORMATION but the documentation states that it is "RCODE-INFO"

To make this even more confusing: The RCODE-INFORMATION option for TEMP-TABLES is only there for backwards compatibility reason so imho it can be ignored and so the RCODE-INFO keyword should not be RCODE-INFORMATION.

**Comment by gquerret** [comment]
Yes, you seem absolutely right.

**Comment by gquerret** [comment]
RCODE-INFORMATION added as an exception. Merged in develop
