### ISSUE TITLE
Unused Variable for public properties

### ISSUE THREAD

**Issue by lneumeier** [Riverside-Software/sonar-openedge#547]
I'm getting a false positive for public properties.
![sonar](https://user-images.githubusercontent.com/39283158/43186316-9a77b8b8-8fee-11e8-993e-0aace91b2d12.png)
![getter](https://user-images.githubusercontent.com/39283158/43186342-a663a68c-8fee-11e8-9ac6-ba2167be5401.png)
![setter](https://user-images.githubusercontent.com/39283158/43186345-a96e4242-8fee-11e8-8dc1-a158c081d6d5.png)

**Comment by gquerret** [comment]
Fixed in develop
