### ISSUE TITLE
ANTLR4 Tests - no .proparse directory

### ISSUE THREAD

**Issue by movedoa** [Riverside-Software/sonar-openedge#551]
I added the following prpoerties to my ant buildscript
```
<property name="sonar.oe.antlr4" value="true" />
<property name="sonar.oe.antlr4.proparse" value="true" />
```

I dont get a .proparse directory in my workspace.
I see some new stuff in the ant output so ANTLR4 seems to run.

```

[sonar:sonar] File Common/Address/AdditionalFinalCustomerData.cls - 1242 ms ANTLR4 - 53 ms visitor
....
no viable alternative at input 'SELECT'
Parser switching to LL prediction mode for Iss/$dlciss/$txtsys/P/CHGFONTS.P
Tokens still available in the stream...
....
Trying to define inline variable, but no ID symbol availble

```

**Comment by gquerret** [comment]
Documentation was wrong, one page mentioned `sonar.oe.antlr4.proparse` while the other mentioned `sonar.oe.antlr4.profiler`... `sonar.oe.antlr4.profiler` is the right property name.

**Comment by gquerret** [comment]
And message `Trying to define inline variable, but no ID symbol availble` is already known, you'll probably have a few in your logs.

**Comment by movedoa** [comment]
Still no .proparse directory but i get the "ANTRL4 - longest rules" output now

**Comment by movedoa** [comment]
Can't find it in either

**Comment by gquerret** [comment]
Do you see the message "Unable to write proparse debug file" in your log ?

**Comment by movedoa** [comment]
No

**Comment by movedoa** [comment]
Ok found it, it was in a my svn source folder
I have no idea why, this is used in the build but nerver set anywhere in the sonar or ant properties
Maybe one of my scripts changes the work folder to this one, thats the only explanation i have
