### ISSUE TITLE
Sections of code should not be "commented out"

### ISSUE THREAD

**Issue by movedoa** [Riverside-Software/sonar-openedge#552]
![grafik](https://user-images.githubusercontent.com/13309951/43256918-90877b64-90ce-11e8-9bbb-b3ca9f0151f3.png)

![grafik](https://user-images.githubusercontent.com/13309951/43256947-a53abbac-90ce-11e8-9427-f93ff80ea6db.png)

![grafik](https://user-images.githubusercontent.com/13309951/43257409-0b4b000e-90d0-11e8-9db2-7eea8dd9a736.png)

![grafik](https://user-images.githubusercontent.com/13309951/43257529-5717f4ec-90d0-11e8-9215-f9833fa41644.png)

**Comment by gquerret** [comment]
The rule considers that if the comment is valid ABL code, and has more than 4 real nodes, then it's considered commented out code.

* `CHR(175)`: this is valid ABL code. Maybe the threshold with 4 nodes is too low
* `Import der/des Lieferanten des Eigners`: this is a perfectly valid ABL statement, if there are fields or variables with this name :-) OK, this kind of import statement shouldn't be considered valid.
* `Format für Zeilen die erzeugt werden`: once again, perfectly valid code :-)
* "Application server" ...: that's a valid expression, and probably the one I wouldn't consider a false positive

**Comment by gquerret** [comment]
Having a parameter for the threshold could be something good enough for most users to avoid too many false positives

**Comment by cverbiest** [comment]
@gquerret No, only with the eclipse plugin.
I've seen it in other appbuilder style sources.
When it occurs it falsely reports mulitple violations 3 lines apart.
Probably better reported as a separate issue

**Comment by gquerret** [comment]
Merged in develop, will be included in next release
