### ISSUE TITLE
USE DO TO instead of DO WHILE for counting loops

### ISSUE THREAD

**Issue by movedoa** [Riverside-Software/sonar-openedge#555]
DO TO is about 70% faster in my tests

```
DEFINE VARIABLE liCount AS INTEGER NO-UNDO.
DEFINE VARIABLE liTime1 AS INTEGER NO-UNDO.
DEFINE VARIABLE liTime2 AS INTEGER NO-UNDO.

liCount = 0.
ETIME(TRUE).
DO WHILE liCount < 50000:
   liCount = liCount + 1.
END.
liTime1 = ETIME.

ETIME(TRUE).
DO liCount = 0 TO 50000:
END.
liTime2 = ETIME.

MESSAGE
   "DO WHILE: " liTime1 SKIP
   "DO TO: " liTime2
   VIEW-AS ALERT-BOX
.
```

**Comment by gquerret** [comment]
Were you able to test that in multiple Progress versions ? Or just a single one ?
And what is the performance penalty when you do something in the loop, even just a simple assignment ?

**Comment by movedoa** [comment]
I only tested this in 11.7.2
The performace difference is pretty much the same if you assign some integer variable in the second loop, it is about 60% faster then.

**Comment by cverbiest** [comment]
On 11.7 linux 64 bit
DO WHILE:  20  
DO TO:  5    

modfied sample
´´´
DEFINE VARIABLE liCount AS INTEGER NO-UNDO.
DEFINE VARIABLE liTime1 AS INTEGER NO-UNDO.
DEFINE VARIABLE liTime2 AS INTEGER NO-UNDO.

DEFINE VARIABLE liEnd AS INTEGER NO-UNDO.

liCount = 0.
pause 0 before-hide.

ETIME(TRUE).
liEnd = 5.
DO WHILE liCount < liEnd:

   liCount = liCount + 1.
    disp liCount.
    liEnd = 50000.

END.

liTime1 = ETIME.
liEnd = 5.

liCount = 0.
ETIME(TRUE).
DO liCount = 0 TO liEnd:
    disp liCount.
    liEnd = 50000.

END.

liTime2 = ETIME.

MESSAGE
      "DO WHILE: " liTime1 SKIP
      "DO TO: " liTime2
      VIEW-AS ALERT-BOX
      .
´´´
DO WHILE:  266 
  DO TO:  244

**Comment by jurjendijkstra** [comment]
Lint might warn that the DO block is empty :-) 

I see liTime1 = 14 and liTime2 = 12 (openedge 11.7.2) when there is a simple assignment in the second loop (just iDummy = iDummy + 1).

When the do loop is empty then I get liTime2 = 4, which is a waste because the compiler could have removed the entire loop because it has no effect (except a bleeding liCount value of 50001).

**Comment by movedoa** [comment]
Yeah you are completely right, something went horribly wrong with my timing there
(In my tests there was the same code in the loops, i just removed it for this easy example)

Redoing the example i see no noteworthy difference, nevermind then :D
