### ISSUE TITLE
Unexpected token: on stop-after

### ISSUE THREAD

**Issue by cverbiest** [Riverside-Software/sonar-openedge#558]
Following valid code gives: `unexpected token: lTimeout in sonar/stopafter.p:25:35`

```
block-level on error undo, throw.
define variable lTimeout as integer no-undo initial 5.

do on stop undo, retry stop-after lTimeout:

end.
```

**Comment by gquerret** [comment]
Reproduced. Reserved keyword are currently accepted as block labels (which they shouldn't), so stop-after is considered blocklabel for retry statement, and lTimeout becomes an error.

**Comment by gquerret** [comment]
Fixed in develop
