### ISSUE TITLE
Provide easy way to disable CommentedOutCode for a single comment

### ISSUE THREAD

**Issue by cverbiest** [Riverside-Software/sonar-openedge#571]
Please provide an easy way to disable the **rssw-oe-main:eu.rssw.antlr.proparse.checks.CommentedOutCode** rule for a comment so that we can mark commented out "code" as compliant.

### documentation comments that contain sample code
```
    /**
     * Purpose: SomeTest
     * Notes:
     * usage
     * if SomeTest()
     * then do:
     * end.
     * @return logical result
     */
```
### comment on end.
For large blocks we sometime put a comment at the end indicating which block end here.
```
if somecondition and othercondtion
then do:
// lots of code here
end. /* somecondition and othercondtion */
```

## Proposal
Ignore comments that start with /** . That already fits the documentation format

**Comment by cverbiest** [comment]
I'd be happy with just one way of disabling the rule for a comment
e.g. `end. /** somecondition and othercondtion */`
but I need to check if those comments would pop-up in the generated docs. 

Another option could be detecting that the code in the comment is the same (or part of) the code that started the block. But that seems too much work for something a developer can fix her(/him)self by adding a character to the comment

**Comment by gquerret** [comment]
Merged in develop, will be included in next release
