### ISSUE TITLE
unexpected token: THIS-OBJECT with CREATE SERVER-SOCKET

### ISSUE THREAD

**Issue by movedoa** [Riverside-Software/sonar-openedge#58]
V1.9.4 
Basiaclly the same issue as #47 but with SERVER-SOCKET insead of SOCKET

**Comment by gquerret** [comment]
All `CREATE xxx` will be corrected as part of this fix.

**Comment by gquerret** [comment]
As part of the fix, CREATE SAX-ATTRIBUTES wasn't correctly handled.

**Comment by gquerret** [comment]
And found that `CREATE BUFFER THIS-OBJECT:hdlVar` can be compiled, but throws a runtime error due to the missing `FOR TABLE xxx` part.
The ABL compiler still amazes me :-)
