### ISSUE TITLE
Variable is read but never assigned

### ISSUE THREAD

**Issue by movedoa** [Riverside-Software/sonar-openedge#582]
![grafik](https://user-images.githubusercontent.com/13309951/46130730-4406fb00-c23a-11e8-8984-6d3962ae2b3d.png)

----------------------

![grafik](https://user-images.githubusercontent.com/13309951/46130970-db6c4e00-c23a-11e8-9a9f-41f9da2167e3.png)

**Comment by gquerret** [comment]
Confirmed

**Comment by movedoa** [comment]
Found another case, when you call a method with an output parameter but don't specify "OUTPUT" in the call, it also doesn't count as assiged, even though the Runtime correctly uses it as output parameter.

I guess #528 should solve this, one more reason for this rule to be important ;-)

**Comment by movedoa** [comment]
![grafik](https://user-images.githubusercontent.com/13309951/46142502-80951f80-c257-11e8-839d-abdca2be06f3.png)

Another case, RETURN doesn't count as read

**Comment by movedoa** [comment]
![grafik](https://user-images.githubusercontent.com/13309951/46662457-c1782700-cbbb-11e8-9c08-d0db06daa90a.png)

**Comment by lneumeier** [comment]
Another example (ASSIGN with THIS-OBJECT): 
<img width="886" alt="bildschirmfoto 2019-01-14 um 20 44 02" src="https://user-images.githubusercontent.com/39283158/51136825-baf1ef00-183d-11e9-84eb-69c6b7e374f9.png">

**Comment by gquerret** [comment]
Fixed for this-object reference. #528 still to be fixed.
