### ISSUE TITLE
Provide a way to mark false positives in code

### ISSUE THREAD

**Issue by movedoa** [Riverside-Software/sonar-openedge#6]
Afaik the only possible way to mark false positives at the moment is in the SonarQube GUI which means that every time i create a new project (for example for a new dev branch), all the false positives are back.

It would be really nice to have a way to mark false positives in code.
Maybe with a special comment like /* @SonarIgnore@ */ or something like that.

**Comment by jakejustus** [comment]
Depending on the rule definition, it's possible to use proparse directives to skip issues. Documentation will be updated soon.

**Comment by jakejustus** [comment]
Starting 1.8.0, please see rule documentation on how to skip an issue.
