### ISSUE TITLE
Unknown table name: dictdb._Db in null:-1:-1

### ISSUE THREAD

**Issue by patrickTingen** [Riverside-Software/sonar-openedge#600]
Code like
```
FIND FIRST dictdb._Db NO-ERROR.
```
Generates error
![image](https://user-images.githubusercontent.com/6008861/47090487-5239ad00-d223-11e8-8099-1eaaefdf9c83.png)

Source: [here](http://sonar.riverside-software.fr/project/issues?id=patrickTingen%3ADataDigger&issues=AWZC6NHMxLxY33vBxzLE&open=AWZC6NHMxLxY33vBxzLE)

**Comment by gquerret** [comment]
Property sonar.oe.databases included in the analysis
