### ISSUE TITLE
unused buffer: unable to suppress

### ISSUE THREAD

**Issue by stefandrissen** [Riverside-Software/sonar-openedge#605]
Our framework has certain expected signatures on certain procedures. One of these has a buffer that does not really need to be used.

The rule help is empty.

Please add a preprocessor to suppress the rule violation.

**Comment by gquerret** [comment]
That will added !

**Comment by gquerret** [comment]
`{&_proparse_ prolint-nowarn(buffer_usage)}` now suppresses the issue.
Merged in develop, will be available in next version
