### ISSUE TITLE
Avoid trailing whitespaces rule

### ISSUE THREAD

**Issue by movedoa** [Riverside-Software/sonar-openedge#618]
Even though we use an eclipse plugin to trim trailing whitespaces in our code, sometimes whitespaces slip in because other devs use a different editor or forgot to activate the plugin. A rule that checks for trailing whitespaces would be nice to catch these errors.

**Comment by gquerret** [comment]
Merged in develop, will be available in next version. Rule won't be included in default quality profile as it can generate lots of issues.
