### ISSUE TITLE
Too many parameters

### ISSUE THREAD

**Issue by stefandrissen** [Riverside-Software/sonar-openedge#619]
I'm currently going through some legacy code that is passing over 40 parameters to an internal procedure in another program. The risk of a (functional) mismatch is much too high.

Any `RUN` passing more than 10 (?) parameters could be flagged as code smell.

**Comment by jurjendijkstra** [comment]
May I do a suggestion, or a request really: would you be willing to provide a relatively simple rule like this one with sourcecode? I think it would be a good, practical example to teach how to write a custom rule 
(in fact any working example would be welcome, this new rule idea just seems like an easy one)

**Comment by cverbiest** [comment]
@jurjendijkstra +1

**Comment by gquerret** [comment]
Agreed

**Comment by gquerret** [comment]
Included in develop. Will be included in the rules-plugin-template (with source code) ASAP.

**Comment by gquerret** [comment]
It completely fell off the radar, but the rule has just been merged in master branch of the rules plugin template: https://github.com/Riverside-Software/rules-plugin-template/commit/b4bf9b641cf1251ebd588d4d3ecc6adfa2698db1
