### ISSUE TITLE
Unused variables - FP on .Net event methods

### ISSUE THREAD

**Issue by gquerret** [Riverside-Software/sonar-openedge#62]
Point 3 of issue #25, created its own issue for better management.
From initial issue : Nearly Every .net Event Method has falso positives for its input parameters (sender and e), there is no way to avoid the variables that the event wants, so parameters of event methods should be ignored

@movedoa Do you mean event handlers (procedure or method) which accepts a first parameter as an instance of System.Object and a second parameter as instance of any class extending System.EventArgs ?

And while browsing documentation for events, I stumbled upon this construct

```
DEFINE PUBLIC EVENT xxx SIGNATURE VOID ( ... ).
```

which also raises FP.

**Comment by movedoa** [comment]
Imho the parser should ignore the parameters for all event subscriptions (.Net and OE Events)
I think that in most cases some subscribers use parameters and some don't so i don't think this would ever be useful as an isse.
