### ISSUE TITLE
Documentation issue: How to specify where XREF files can be found

### ISSUE THREAD

**Issue by cverbiest** [Riverside-Software/sonar-openedge#620]
#417 seems to indicate that xref files are found in the binaries directory but that is not documented on https://github.com/Riverside-Software/sonar-openedge/wiki/Property-list

Our PCTCompile puts xref in a central .pct subdirectory

                        keepXref="true"
                        xmlXref="true"
                        xrefDir=".pct"

It's unclear to me
1. How I should specify the XREF directory to the scanner
2.  How I can verify in the scan output that xref files are found and processed

**Comment by jurjendijkstra** [comment]
In my ant script I have: 

            <property name="sonar.oe.binaries" value="${targetdirectory}/r" />

after having compiled using:

  <PCTCompile 
                 destDir="${targetdirectory}/r" 
  	          xmlXref="true" 
  	          keepXref="true" 
                  (and some more options)

**Comment by gquerret** [comment]
@cverbiest There's currently no way to specify an alternate directory for XREF files. But this is high on the TODO list, as that is required for managing XREF file in PDSOE. That probably be part of a late January release.

**Comment by cverbiest** [comment]
Would 

    sonar.oe.binaries=xrefdir,rcodedir

work or does it need to be

    sonar.oe.binaries=rcodedir

with xref files in the same directory as the rcode ?

### Second question (should propably be in the ticket for the alternate xref directory)
In our current setup all xref files, from multiple projects, are sent to a single .pct directory.
Would the scan be able to identify which xref files it needs based on the rcode it finds or would there have to be a seperate xref directory in each project

**Comment by lneumeier** [comment]
My current setup, but I don't know if this is correct:
```
build 
    .pct
sources
    src
    tests
    sonar-project.properties
```
sonar.oe.binaries=%path%/build

**Comment by gquerret** [comment]
Added new property `sonar.oe.dotpct` in PR-624.
Behavior is:
* Handle multiple dirs in `sonar.sources`
* Handle multiple dirs in `sonar.oe.binaries`. If property not defined, then defaults to `sonar.sources`
* Handle multiple dirs in `sonar.oe.dotpct`. If property not defined, then defaults to each dir in `sonar.oe.binaries` with `.pct` appended

Xref, listing and warning files are read in `sonar.oe.dotpct`

**Comment by gquerret** [comment]
Merged in develop
