### ISSUE TITLE
Question/enhancement request Sonarlint Visual Code

### ISSUE THREAD

**Issue by cverbiest** [Riverside-Software/sonar-openedge#621]
Sonarlint supports Visual code , see https://www.sonarlint.org/vscode/ 
Does this also work for the OpenEdge fork of Sonarlint ?
If not, can this be done, or are there other alternatives on the fly analysis when a PDSOE environment is not available ?

Docs at https://github.com/Riverside-Software/sonar-openedge/wiki/SonarLint still refer for the deprecated command line version of Sonarlint

**Comment by gquerret** [comment]
From what I've seen, this requires an LSP server implementation, which is not available yet. The only on-the-fly analysis tool remains PDSOE, as SonarLint CLI is deprecated.
