### ISSUE TITLE
Code coverage - exclude file type

### ISSUE THREAD

**Issue by lneumeier** [Riverside-Software/sonar-openedge#623]
Hello,

Is it possible to exclude, for example window files (\*.w) and procedure file (\*.p), from the code coverage? We only write tests for classes and the computation of possible executed lines in window files takes a hugh amount of time because of all the includes that are used in window files...

**Comment by lneumeier** [comment]
Here is an example
[test.log](https://github.com/Riverside-Software/sonar-openedge/files/2680015/test.log)

**Comment by gquerret** [comment]
That's 0.8 second per file (which is quite long), but I wonder how much is spent logging every line number. What is the total time for CoverageSensor ? As in `Sensor ProfilerCoverageSensor [openedge] (done) | time=XXXX`

**Comment by lneumeier** [comment]
Total time without logging (from a previous build):
INFO: Sensor ProfilerCoverageSensor [openedge] (done) | time=8757273ms

**Comment by lneumeier** [comment]
> Yes, you can use `sonar.coverage.exclusions=**/*.p,**/*.w`
> Do you have some figures for computation of executed lines (i.e. time and number of lines) ?

Sonarqube is logging ....w is excluded from code coverage, but still getting:
```
14:55:42.365 DEBUG: Executable line #20424 - File basis/sv/hkr/buchk_68.w:1984 - Found E:\sonarqube\v409.66\prodoppik\src\basis\sv\hkr\buchk_68.w - FS src/basis/sv/hkr/buchk_68.w
```

**Comment by gquerret** [comment]
Merged in develop an enhancement for the code coverage performance. This does not specifically exclude files from being read, but this lets SQ internally discard data for excluded files much faster.
