### ISSUE TITLE
Which files from pct are necessary?

### ISSUE THREAD

**Issue by lneumeier** [Riverside-Software/sonar-openedge#625]
Hello,

I would like to integrate the output of pct into our buildsystem, what files are necessary for sonarqube?

- rcode files for parsing
- xref xml for parsing
- code-listing files for transaction scope rule?

What about .crc, .hierarchy and .inc files?

**Comment by gquerret** [comment]
The .crc, .hierarchy and .inc are not used in SonarQube.
