### ISSUE TITLE
Sonarlint Update for Eclipse 

### ISSUE THREAD

**Issue by lneumeier** [Riverside-Software/sonar-openedge#629]
Hello, 

The current version of Sonarlint for eclipse is 4.0.0 (https://www.sonarlint.org/eclipse/). The current supported version is 3.3.999. Any updates planed?

**Comment by gquerret** [comment]
Version 3.6.999 is almost ready (and already included in OE12 CVP), that will be part of the next release of the OE plugin (ETA end of January). Version 4.0 will then follow.
