### ISSUE TITLE
No license found

### ISSUE THREAD

**Issue by niandy** [Riverside-Software/sonar-openedge#636]
I've got this message on SonarQube 7.5 community edition and SonarLint plugin versions 2.2.5 and 2.2.6.
Here's the verbose output
[sonarlint.log](https://github.com/Riverside-Software/sonar-openedge/files/2764854/sonarlint.log)

**Comment by gquerret** [comment]
Did you install an evaluation or permanent license for the Riverside rules ?

**Comment by niandy** [comment]
Actually none, because that part was quite unclear in the instructions. I was not going to execute commercial rules, so I thought that no license was needed. Am I wrong? Or the commercial rules are included by default and I need to disable them somehow?

**Comment by gquerret** [comment]
Commercial rules are in the riverside-rules package. If you just want to execute the OSS version, just install sonar-openedge.jar

**Comment by niandy** [comment]
Thanks for your help. Everything is working now
