### ISSUE TITLE
Plugins crash non OpenEdge analysis

### ISSUE THREAD

**Issue by calimero1000582** [Riverside-Software/sonar-openedge#644]
I have a couple of project I want to plug in Sonarqube (C# and OpenEdge). Without sonar-openedge, analysis on my C# project works flawlessly. After installing the plugin, in my C# project, I have a log saying "Using PROPATH", then a ton of errors (1 error per file in my project) saying "Unable to resolve source directory '"C:\BuildDirectory\MyProject\MyFile.cs"'". 

Any way to fix or disable/enable plugin by project?

**Comment by gquerret** [comment]
The OE plugin should play well with other plugins, and you should only see those two messages:
```
[INFO] Loading OpenEdge settings for server ID 'XXXXXXXX' ''
[INFO] Using PROPATH : 
```
The string `"Unable to resolve source directory"` could come from one of the commercial rules. However, those rules are not supposed to be executed on .cs files. Did you force file extensions at some point ?

**Comment by calimero1000582** [comment]
Got this without any modification. In an attempt to solve the problem, I forced default values explicitly, but no success

sonar.oe.file.suffixes = p,w,cls,i,t
sonar.oe.include.suffixes = i

**Comment by gquerret** [comment]
Could you include a verbose log (-X with sonar-scanner, or -v with Ant) on your sample project ?

**Comment by calimero1000582** [comment]
Here a log file
[CompletingSonarQubeAnalysis.log](https://github.com/Riverside-Software/sonar-openedge/files/2817900/CompletingSonarQubeAnalysis.log)

**Comment by gquerret** [comment]
sonar.sources is supposed to contain a comma-separated list of source directories, not of source files.

**Comment by calimero1000582** [comment]
This is automatically generated by a plugin from SonarSource (https://marketplace.visualstudio.com/items?itemName=SonarSource.sonarqube). As all other plugin work with this, any way you just ignore path if it is not a folder (or use parent folder if file)  instead of having an error?

**Comment by gquerret** [comment]
I'll have a look at the VS behavior. Please also note that you need a license to execute the riverside-rules package.

**Comment by gquerret** [comment]
Fixed in develop branch, will be part of next release.
OpenEdgeSettings object (which was the source of the log messages) is now initialized later during the analysis, and only if OpenEdge files are part of the analysis.
