### ISSUE TITLE
Rule idea: compile failed

### ISSUE THREAD

**Issue by cverbiest** [Riverside-Software/sonar-openedge#646]
Is it possible to log failed compilations as a rule violation ?
It may seem like improper use of sonar to flag compile errors, but the benefit I see is that we could see all issues with a codebase in a single user interface

**Comment by gquerret** [comment]
Proparse errors are already reported in SonarQube, although this is not strictly a 1:1 mapping with compiler errors.
However, I think it would be better to have your CI tool be the user interface for issues in the codebase. There are some options (which may involve the Developer edition of SQ) to report SQ issues in the CI tool.

**Comment by cverbiest** [comment]
Ok, I'll create a PCTCompile issue ;-)
