### ISSUE TITLE
How to use custom rule 'Matching keyword in source code'

### ISSUE THREAD

**Issue by dominickdm** [Riverside-Software/sonar-openedge#652]
Hi,

I'm trying to configure a custom rule based on the rule template 'Matching keyword in source code'. Is there any documentation about this?

We want to avoid that SESSION:CHARSET is used since it obsolete (see progress documentation) (https://documentation.progress.com/output/ua/OpenEdge_latest/index.html#page/dvref/charset-attribute.html).

Below you can find my configuration, can you tell me what i'm doing wrong? The rule is linked to the quality gate and i refreshed my project bindings..

![image](https://user-images.githubusercontent.com/40289256/53799409-990e1200-3f3a-11e9-8723-f978e3416f5a.png)

**Comment by cverbiest** [comment]
Hi Dominick
This is an example from our enviroment.
I think you can't test for session:charset, only for charset. 

![image](https://user-images.githubusercontent.com/1312691/53800131-4e8d9500-3f3c-11e9-94f4-12a31946d108.png)

**Comment by dominickdm** [comment]
Hi Carl,

Thank you for your example, it works for the 'MESSAGE'-keyword, but it doesn't seems to work for CHARSET.
Maybe it's because CHARSET is not a keyword, but an attribute.. If so, maybe a new rule 'Matching attribute in source code' could be considered?

**Comment by gquerret** [comment]
That's probably the same issue as this one: https://github.com/Riverside-Software/sonar-openedge/issues/651

And yes, matching keyword rule detects single keyword (such as SESSION) , not group of keyword (as SESSION:CHARSET).

**Comment by gquerret** [comment]
I confirm that `CHARSET` is not considered as a keyword. Will be fixed

**Comment by dominickdm** [comment]
Ok, thank you for the feedback. 

Looking forward for the fix.

**Comment by gquerret** [comment]
Merged in develop, will be available in next release
