### ISSUE TITLE
Strict NoRoutineInWhere rule

### ISSUE THREAD

**Issue by movedoa** [Riverside-Software/sonar-openedge#655]
There is the startup parameter -noroutineinwhere and there is a rule idea for a sonar check that does the same thing https://github.com/Riverside-Software/sonar-openedge/issues/554.

But a strict version of this would be very good.
By strict i mean absolutely no routine, function or other keywords in queries.

Example:

```
FOR EACH Foo WHERE TRIM(Foo.Dsc) = "Foo":U NO-LOCK:
   /* The Trim kills the performance */
END.
```

I tried it with a few tables in our Database.
Without the TRIM (and having an index) everything is fast.

As soon as I add the TRIM, i get the same performance that I get without any index, so basically whole-index.

**Comment by gquerret** [comment]
Included in 2.27
