### ISSUE TITLE
commented out code not always detected?

### ISSUE THREAD

**Issue by dominickdm** [Riverside-Software/sonar-openedge#656]
Hi,

What could be the reason that the second block of commented code is not detected by the 'commented out'-rule?

![image](https://user-images.githubusercontent.com/40289256/55542232-e3fc8000-56c6-11e9-9f7f-ee8dc12473a4.png)

**Comment by gquerret** [comment]
There are some criteria to limit the number of false positives (considering it's better not to highlight an issue than highlighting a false positive). I'll have a look at this case, and see why this is not detected.

**Comment by gquerret** [comment]
A similar text has been included in a comment, and it's detected as commented-out code. Are you sure the first issue is a commented-out issue, and not for example the "empty block" issue ?

**Comment by dominickdm** [comment]
I'm not able to reproduce exactly the same source, but here is another similar example.

![image](https://user-images.githubusercontent.com/40289256/55717524-c8141980-59f9-11e9-9ac4-af9a2dd2974a.png)

**Comment by gquerret** [comment]
Only in SonarLint, or do you have the same (non-)issue in the Web UI ?

**Comment by dominickdm** [comment]
That source didn't make it to our master-branch so it's difficult to tell you if the issue is also in the Web UI. 
I tried isolating the code into a separate class, but there everything was ok..
Does it help you if I send you the whole file?

**Comment by gquerret** [comment]
Yes, you can send the file. If possible, remove any unnecessary code (especially include file reference) for the smallest reproducible case.

**Comment by dominickdm** [comment]
Hi,

I have reduced the code to a minimum; see file attached and screenshot below:
![image](https://user-images.githubusercontent.com/40289256/56219861-bff65280-6067-11e9-8389-b09a72607bda.png)
[GlimsFamilyOfGeneticExamEditorView.zip](https://github.com/Riverside-Software/sonar-openedge/files/3085453/GlimsFamilyOfGeneticExamEditorView.zip)
* if i comment the content of the method, the issue is detected
![image](https://user-images.githubusercontent.com/40289256/56220100-254a4380-6068-11e9-8b5d-b5c700374867.png)

* if i remove the method 'test', the issue is detected
![image](https://user-images.githubusercontent.com/40289256/56219998-fb911c80-6067-11e9-9938-5a957982e5a0.png)

**Comment by gquerret** [comment]
Thanks for the test case ! This allowed me to understand why this is not reported as an issue... Comments preceding method declaration are skipped, as this is the position for documentation, which in many times contains code snippets. In order to reduce false positives, those comments are not considered for this rule.
