### ISSUE TITLE
Parse error on code that uses DYNAMIC-PROPERTY

### ISSUE THREAD

**Issue by danielbecroft** [Riverside-Software/sonar-openedge#657]
Running the scanner over code that uses the `DYNAMIC-PROPERTY` method fails with an antlr parse error:

     ERROR: Error during code parsing for openedge/source/library/active-directory.p at position openedge/source/library/active-directory.p:124:92
    antlr.NoViableAltException: unexpected token: (

I am using the most recent build of sonar-openedge.

The line of code is below:

    buffer ttUserPrincipal:buffer-field(vIndex):buffer-value = dynamic-property(objUserPrincipal, buffer ttUserPrincipal:buffer-field(vIndex):name)

**Comment by gquerret** [comment]
Confirmed, DYNAMIC-PROPERTY is not recognized correctly.

**Comment by gquerret** [comment]
Fixed in develop
