### ISSUE TITLE
Empty field list

### ISSUE THREAD

**Issue by dominickdm** [Riverside-Software/sonar-openedge#665]
Hi,

Since OE 12 changes the behavoir of the empty fields()- phrase (see https://docs.progress.com/bundle/openedge-whats-new/page/Behavior-change-for-empty-FIELDS-list.html), we want to avoid the usage of the empty FIELDS()-phrase.

Can we have that rule? If so, it there any roadmap available or can we have an expected date of when the rule will be available?

**Comment by gquerret** [comment]
Looks like a simple rule that could be included in next version.

**Comment by gquerret** [comment]
Merged in develop, rule was a good test for what I was looking for this morning :-)
