### ISSUE TITLE
NO-UNDO not specified with input parameter defined with like

### ISSUE THREAD

**Issue by movedoa** [Riverside-Software/sonar-openedge#677]
![grafik](https://user-images.githubusercontent.com/13309951/58785478-d5a6e380-85e5-11e9-85d0-cc8b2fc6d986.png)

Since 2.5.0

In the output log i see the following line:
`[sonar:sonar] Syntax error -- Iss/$dlciss/$WARSYS/P/CvWarVNr.p:27:40 -- no viable alternative at input 'pOwnId          NO-UNDO'`

**Comment by gquerret** [comment]
Confirmed

**Comment by gquerret** [comment]
Merged in develop
