### ISSUE TITLE
Syntax error while parsing our .df file

### ISSUE THREAD

**Issue by keeneym** [Riverside-Software/sonar-openedge#68]
We are currently getting errors while parsing our .df file. 
The .df file was created using a standard PCTDumpSchema in ant.

It appears that the parser may be missing support for Alternate Buffer pools.
Here are two example log lines (we actually have 37  lines with this error, but all result from the same issue)
```
[sonar:sonar] Syntax error <unknown>:65056:22 mismatched input 'OF' expecting 'ON'
[sonar:sonar] Syntax error <unknown>:65059:27 mismatched input 'OF' expecting 'ON'
```
and here are the corresponding lines in our .df file. 

```
UPDATE INDEX "bycity" OF "contact"
  BUFFER-POOL "Alternate"

UPDATE INDEX "bycontactid" OF "contact"
  BUFFER-POOL "Alternate"
```

**Comment by gquerret** [comment]
Accepted, and will be included in next version.
Will also include the TDE syntax :
```
UPDATE TABLE "xxx"
  ENCRYPTION YES
  CIPHER-NAME [a-zA-Z][a-zA-Z_]*
```
