### ISSUE TITLE
SonarLint - confusion between ProjectKey & ProjectName

### ISSUE THREAD

**Issue by clement-brodu** [Riverside-Software/sonar-openedge#680]
## Subject of the issue
In PDS, I try to bind a project with my sonarqube Project, but it fails : 

![image](https://user-images.githubusercontent.com/37274615/58788051-5e744e00-85eb-11e9-9ba4-bcfef8ae51b4.png)

It's probabaly because the project key and project Name are not equals : 

![image](https://user-images.githubusercontent.com/37274615/58788131-895ea200-85eb-11e9-9d14-634a2cd71867.png)

To deal with it I have 2 options : 
* Use the same value for `sonar.projectKey` and `sonar.projectName`
* Write the projectKey and not use autocompletion when I bind the projet.

It's not a big problem, but It works fine in Sonarlint 3.3.999, so It's probably a regression 

## Your environment
OpenEdge version 11.7.4
SonarLint 3.6.1008

## Steps to reproduce
Try to Bind a project with different ProjectKey and ProjectName

**Comment by gquerret** [comment]
You probably still have files (like sonarlint.json) in the project directory, or in the .settings directory. Make sure you remove them before assigning the project to a SonarQube project. 
Anyway, I didn't reproduce in my environment.

**Comment by clement-brodu** [comment]
I use a clean new projet set like this on sonarqube  :

![image](https://user-images.githubusercontent.com/37274615/58859172-7c07ed00-86a9-11e9-89e3-628267d149dd.png)

And I create a new clean an simple project in PDS, so it can't be due to a previous configuration.

**Comment by gquerret** [comment]
Error message is misleading, but only happens when no analysis has been executed on the project (i.e. project has just been provisioned).
