### ISSUE TITLE
Avoid fortran style operator reports methods that are named like fortran operators

### ISSUE THREAD

**Issue by Ton-Pe** [Riverside-Software/sonar-openedge#683]
We have some methods in validation classes and in table model classes that are named like fortran operators. ie EQ, LT etc. Sonar now reports usage of these methods as a code smell.
![image](https://user-images.githubusercontent.com/25682299/58892624-3b36c500-86f7-11e9-999a-d081077c27c4.png)

I think this is a false positive. Is it possible to fix this and not to report if method name equals to fortran operator?

**Comment by gquerret** [comment]
Sonar-openedge version ?

**Comment by Ton-Pe** [comment]
Sorry, my bad. I forget the  version. The version is 2.2.6. I know that's way old. I just realized after sending this, that we updated our server to an old version. We'll update to 2.5.0 and I will test this again and let you know.

**Comment by Ton-Pe** [comment]
Tested on sonar-openedge 2.5.0 and sonarlint 3.6.1008. Problem still exists.

**Comment by Ton-Pe** [comment]
Hi @gquerret , just a note that problem still exists in version 2.8.2. Any plans to fix this in future releases?

**Comment by gquerret** [comment]
The ANTLR4 migration makes it easier to deal with this kind of case. I'll see how I can put that higher on the list.

**Comment by gquerret** [comment]
Fixed in develop
