### ISSUE TITLE
Default buffer usage reports DEFINE DATA-SOURCE

### ISSUE THREAD

**Issue by Ton-Pe** [Riverside-Software/sonar-openedge#684]
`DEFINE PRIVATE DATA-SOURCE src_BankData FOR BankData .`

Is reported as a code smell if **default buffer usage** rule is activated. Is this really a code smell and against the rule or is it a bug/need for improvement? Do I need to first define buffers for every table and then the data-sources, if I still want to use that rule? Sounds weird, but maybe there is something that I'm not aware of :)

**Comment by gquerret** [comment]
sonar-openedge version ?

**Comment by Ton-Pe** [comment]
Sorry, my bad. I forget the  version. The version is 2.2.6. I know that's way old. I just realized after sending this, that we updated our server to an old version. We'll update to 2.5.0 and I will test this again and let you know.

**Comment by Ton-Pe** [comment]
Tested on sonar-openedge 2.5.0 and sonarlint 3.6.1008. Problem still exists.

**Comment by gquerret** [comment]
Fixed in develop
