### ISSUE TITLE
Parser - SQL Select Distinct

### ISSUE THREAD

**Issue by clement-brodu** [Riverside-Software/sonar-openedge#685]
## Subject of the issue
When I have a SQL instruction in my programe and the parser stop before this instruction.

All the code after is ignored.

```abl
    DEF VAR numcpt  AS INT  NO-UNDO.
    DECLARE liscpt_ach CURSOR FOR SELECT DISTINCT matable.cpta FROM matable WHERE matable.type_tab = "FP".
    OPEN liscpt_ach.
    REPEAT.
        FETCH liscpt_ach INTO numcpt.
        
    END.
    CLOSE liscpt_ach.
```

I agree, it's not very clean, but Progress Compiler allow it.

## Your environment
OpenEdge version 11.7.4
SonarLint 3.6.1008
Sonar Openedge Rules : 2.5.0

**Comment by gquerret** [comment]
SQL statements support was dropped in 2.5.0. Unless there's very strong demand for those statements, it's extremely unlikely to be fixed.
