### ISSUE TITLE
Case sensitivity issue when parsing .df file

### ISSUE THREAD

**Issue by keeneym** [Riverside-Software/sonar-openedge#69]
We are currently getting errors while parsing our .df file. 
The .df file was created using a standard PCTDumpSchema in ant.

It appears that the parser is looking for some keywords in a case sensitive way when it does not need to.
Here is the log line output for our error:
```
[sonar:sonar] Syntax error <unknown>:55405:16 mismatched input 'Assign' expecting '"ASSIGN"'
```
and here are the corresponding lines in our .df file.  (line 55405 mentioned in the error log is the final line of my quoted code below)

```
ADD FIELD "ordr-nbr" OF "scanlog" AS character 
  FORMAT "x(6)"
  INITIAL ""
  LABEL "Order"
  POSITION 12
  MAX-WIDTH 12
  HELP "Order number"
  ORDER 110
  MANDATORY
  FIELD-TRIGGER "Assign" NO-OVERRIDE PROCEDURE "sydir/tgscanlog.t" CRC "?" 
```

**Comment by gquerret** [comment]
I've actually seen this kind of issue in a few places, but nobody was able to tell me how this came in their DF file (didn't search long however).
Does this only appear on Assign triggers ? 
That will be fixed however.
