### ISSUE TITLE
ASSIGN with dangerous WHEN

### ISSUE THREAD

**Issue by stefandrissen** [Riverside-Software/sonar-openedge#698]
The WHEN on an ASSIGN statement is evaluated with the values of any variables /before/ the ASSIGN. The following snippet will not set myvar to true since when the when is evaluated, foo is still empty.
````
def var foo as char.
def var bar as char.
def var myvar as logical.

bar = "with value".

assign
   foo = bar
   myvar = true when foo > ""
   .
````
Inspired by an actual bug.

**Comment by gquerret** [comment]
Very interesting !

**Comment by jurjendijkstra** [comment]
the old Prolint had a rule for this:  http://www.oehive.org/prolint/rules/when

**Comment by gquerret** [comment]
Added in develop branch
