### ISSUE TITLE
Empty code block rule cannot be suppressed for if then

### ISSUE THREAD

**Issue by stefandrissen** [Riverside-Software/sonar-openedge#699]
The comment in a single statement empty then cannot be suppressed:
````
if true then 
   /* nothing */ .
else
   message 'foo'.
```` 
If I change this to a real block, then the issue is suppressed:
````
if true then do:
   /* nothing */
end.
else
   message 'bar'.
````

**Comment by gquerret** [comment]
Will be implemented as an option in the rule (i.e. allow IF THEN ELSE blocks with just a comment)

**Comment by gquerret** [comment]
Fixed in develop branch
