### ISSUE TITLE
Unknown block type DESTRUCTOR

### ISSUE THREAD

**Issue by movedoa** [Riverside-Software/sonar-openedge#7]
This error gets thrown when analyzing a class with a destructor. (Version 1.6.2)

**Comment by jakejustus** [comment]
This should be in the ListingParser phase, right ?
And it should also be just a message in the log, but shouldn't abort the analysis. Could you confirm that ?

**Comment by movedoa** [comment]
yes this is in the "OpenEdgeListingSensor" phase and the analysis doesn't abort

**Comment by jakejustus** [comment]
That will be added.

**Comment by jakejustus** [comment]
Fixed in 1.7.1
