### ISSUE TITLE
Integer overflow

### ISSUE THREAD

**Issue by jurjendijkstra** [Riverside-Software/sonar-openedge#701]
Consider this example:

```
DEF VAR begintime AS INTEGER.
begintime = ETIME(FALSE).
```

In this example the ETIME function returns an INT64 value but it is assigned to an integer variable. If ETIME is very large you will get a runtime error. This was not likely to happen with sessions that restart every night, but if a customers keeps his appserver agents running for days then ETIME may not fit in an integer. 
So the rule id is:  in expression a=b, warn when sizeof(b)>sizeof(a).
Or if it cannot be that generic, then perhaps only for a few specific built-in functions that are known to return an INT64, like ETIME

**Comment by gquerret** [comment]
Included in VariableOverflow rule, see #838
