### ISSUE TITLE
Invalid use of named include parameters

### ISSUE THREAD

**Issue by cverbiest** [Riverside-Software/sonar-openedge#705]
Named parameters for an include must include an equality sign and value.

https://community.progress.com/community_groups/openedge_development/f/19/p/58820/200850#200850

The equality sign and the value are required for a reliable result.
Contrary to the syntax the quotes are optional. if the value contains spaces the quoted are required.

**Comment by gquerret** [comment]
Information is not directly available to the rules engine (include file expansion is somewhat hidden), a small enhancement would be required to have it included. Need to have a look at the time it takes to add this information.

**Comment by gquerret** [comment]
A test case showed that named parameters were not correctly handled in this case. Lexer will be fixed first, and hopefully that will fix some issues related to preprocessing in very large codebase that were hard to investigate. The rule will then follow in a second stage.

**Comment by gquerret** [comment]
Merged in develop, found some interesting issues with this rule !

**Comment by cverbiest** [comment]
@gquerret shouldn't this be flagged by this rule ?
I added &dat2 to an include, expecting the rule to fire but it doesn't. Shall I create a new issue for this ?
![image](https://user-images.githubusercontent.com/1312691/68680871-acaa5780-0562-11ea-98ff-f4a90b7bb6dd.png)

**Comment by gquerret** [comment]
This case should be detected.

**Comment by gquerret** [comment]
@cverbiest Does that also happen in the batch analysis ? Or only in SonarLint ?

**Comment by gquerret** [comment]
@cverbiest Do you still have the same problem ? Or can this issue be closed ?

**Comment by cverbiest** [comment]
Still active, attached sonarlint log 
[sonarlint_mainb.log](https://github.com/Riverside-Software/sonar-openedge/files/4648521/sonarlint_mainb.log)

**Comment by gquerret** [comment]
@cverbiest Also visible in SonarQube ?

**Comment by cverbiest** [comment]
I don't know, the source was fixed. I had to re-introduce the bad code to test on-the-fly.

**Comment by gquerret** [comment]
Is it possible that this section is not analyzed due to previous preprocessor statements ? Could you try adding a new variable to check if UnusedVariable is triggered ?

**Comment by cverbiest** [comment]
The rest seems OK
![image](https://user-images.githubusercontent.com/1312691/82305047-73451f80-99bd-11ea-9888-2f0a7126adb4.png)

**Comment by gquerret** [comment]
Fixed in develop branch. Thanks @cverbiest for your offline comment !
