### ISSUE TITLE
Sonarqube & Plugin default quality profil

### ISSUE THREAD

**Issue by clement-brodu** [Riverside-Software/sonar-openedge#712]
## Subject of the issue 
Each time I restart my serveur, the Default openedge DB quality profile is set on "Sonar way (Extended)" but It was forced to "Sonar way" before I restart.

I don't know if its a bug or if it comes from my settings.

![image](https://user-images.githubusercontent.com/37274615/62119564-2b36fe00-b2c0-11e9-9dac-efc8fcf56fd8.png)

**Comment by gquerret** [comment]
You perhaps removed the riverside-rules plugin.

**Comment by clement-brodu** [comment]
No, I update my own rules plugin then I restart the server.

I made new test, if I create my own Quality Profiles, the problem disappeared.
