### ISSUE TITLE
Oracle schema holder parsing

### ISSUE THREAD

**Issue by dominickdm** [Riverside-Software/sonar-openedge#713]
With oracle we have the following situation:

database connections linked in the eclipse project:
 - glims
 - glims_sh (schema holder)

2 .schema files are created in the .sonartlint-folder:
- glims.schema        => empty
- glims_sh.schema   => structure all the tables

When we sonarlint a source file we get the error 'Table XXX not found' because the table isn't found in the glims.schema-file.

If we rename glims_sh.schema to glims.schema and delete the original glims.schema it works.

Is there anything that we can do to make this work properly?

note: in the 'data dictionary', the link is shown as below:
![DatabaseConnections](https://user-images.githubusercontent.com/40289256/62212893-087d1600-b3a2-11e9-809f-6b23fb391e12.png)

**Comment by cverbiest** [comment]
Maybe the old style config using a sonar.oe.databases property that contains the path to a df will help.  Dump a df and reference it in the sonar properties

example : https://i.imgur.com/Yh1ZDuP.png

**Comment by gquerret** [comment]
Schema holders are not yet supported, so as Carl said, the best solution is to manually inject the schema through the DF files.
