### ISSUE TITLE
AST access for custom xref rules

### ISSUE THREAD

**Issue by cverbiest** [Riverside-Software/sonar-openedge#715]
#370 mentions the xref rules could have access to the AST.
Could the same be done for xquery based custom xref rules ? 
e.g. by adding a prolintnowarn tag field to the rule definition

**Comment by gquerret** [comment]
I'm confident that it will be possible to find the statement associated with a WHOLE-INDEX reference, and then find the associated `prolintnowarn` annotation. The same heuristic can be used, but it may not be 100% precise. Are you looking for something specific in XREF ?

**Comment by cverbiest** [comment]
Currently, I have two types of xquery based rules.

* Usage of a deprecated include 
* Usage of a deprecated table

### Example
rule : alert.i should no longer be used,
xpath `//Reference[contains(@Object-identifier, 'cceinc/alert.i')]`

it would be nice if I could add a prolintnowarn tag `cceinc_alert` in the rule configuration. 
The effect would be that you could then use
`{&_proparse_ prolint-nowarn(cceinc_alert)}` 
to flag intentional breaking of the rule

If a custom name of the tag is difficult to achieve,
`{&_proparse_ prolint-nowarn(XPathAnalyzer)}` 
would be helpful as well.

### related issues
This is related to  #664.

I'd gladly replace our xpath rules by java-style AST custom rules you mention in #702 if those would have that capability.
I would not need those rules if #164 and #381 are implemented but I might find other uses of xpath rules

**Comment by gquerret** [comment]
Groovy rule included in next release.
