### ISSUE TITLE
ClassNameCasing should also detect references to the class

### ISSUE THREAD

**Issue by cverbiest** [Riverside-Software/sonar-openedge#716]
I found that ClassNameCasing rule only fires when the name of the class does not match the filename of the class.
I think it should also flag if references to the class in using statements, variable definitions, new () uses wrong casing.

**Comment by gquerret** [comment]
Does that have any impact at runtime ?

**Comment by cverbiest** [comment]
Our developer usually develop on windows where this goes unnoticed. Linux compile will fail because of this but that is in a later stage, often after the code has already been committed.

**Comment by gquerret** [comment]
Will raise priority of this issue, a customer has just been hit by this issue in a very nasty and unpredictable way. Short story:
* File was written classfile.cls
* Usually referenced with `define variable as classfile`
* But a few `define variable as CLASSFILE` through the code
* Using 4 threads build, so depending on which procedure was first compiling the code (and that changed for each Jenkins build), the resulting rcode was referencing classfile or CLASSFILE.

**Comment by gquerret** [comment]
See additional comments on #795

**Comment by gquerret** [comment]
Fixed in develop
