### ISSUE TITLE
Detect deprecated GLOBAL_DEFINE or procedure call

### ISSUE THREAD

**Issue by dominickdm** [Riverside-Software/sonar-openedge#721]
Hello,

We want to avoid that our developers use the a GLOBAL_DEFINE &ApplicationVersion anymore. 

Is it somehow possible to do this with the current set of rules? Is it an idea to add a rule template with a certain RegEx to be scanned in the whole source file or will it too slow? Also, is the file preprocessed before it is linted?

&IF **{&ApplicationVersion}** = "5.5":U OR **{&ApplicationVersion}** = "6":U
&THEN /* do something */
&ELSE /* do something else */
&ENDIF

**Comment by gquerret** [comment]
There's currently no rule to detect preprocessor variable usage. Information is available at the ParseUnit level so it could be possible to write the rule.

**Comment by stefandrissen** [comment]
Assuming the global is defined somewhere in a central include file, you can let the preprocessor trigger another rule, for example the missing string attribute rule:
````
&global-define ApplicationVersion true ~&then message 'Deprecated preprocessor: ApplicationVersion'. ~&endif ~&if "6.0"

&if {&ApplicationVersion} = "5.5" or {&ApplicationVersion} = "6.0" &then
  message 'new':u.
&else
  message 'old':u.
&endif
````

**Comment by dominickdm** [comment]
Thank you for the feedback.

If this would be implemented; is it also possible to deprecate a certain procedure call?
for example we would like to avoid that our programmers use:
'RUN gp_calld' 
=> a procedure that checks the stack using PROGRAM-NAME, which is bad programming and slow but sometimes we don't have any alternative..

**Comment by cverbiest** [comment]
run results in xref data,
e.g. `<Reference Reference-type="RUN" Object-identifier="init-appl">`
you could try to create a custom xref for that.

**Comment by dominickdm** [comment]
Thank you for the hint Carl, i'll try it out :-)

**Comment by gquerret** [comment]
Just about the custom XREF rule, they will be deprecated soon (although still available in ruleset). Next version of OE plugin will generate an object out of the XREF, that could be browsed with the Groovy rule. XPath syntax can be a bit limited, and all those rules were very slow. WholeIndex and SortAccess rules have been rewritten with this new object, and are much faster.

**Comment by dominickdm** [comment]
@gquerret: good to hear, will this also fix the issue that the XML is sometimes parsed before it the file is completly written?

@cverbiest : //Reference[@Object-identifier="gp_calld"]: it works with the following XPATH //Reference[@Object-identifier="gp_calld" and @Reference-type="RUN"]. Thanks again!

**Comment by gquerret** [comment]
> good to hear, will this also fix the issue that the XML is sometimes parsed before it the file is completly written?

Unfortunately, this is coming from something different

**Comment by cverbiest** [comment]
@dominickdm You're welcome
@gquerret Great News, I'll gladly replace my xref rules by groovy rules.

**Comment by gquerret** [comment]
@dominickdm In case you're interested in a custom rule: https://stackoverflow.com/questions/61524216/sonarqube-openedge-custom-rule-to-verify-if-preprocessor-with-proparse/61595033#61595033

**Comment by gquerret** [comment]
Should be done by custom Groovy rules, won't be implemented directly in the commercial rules.
