### ISSUE TITLE
Proparse error: Unknown table name: <table> in null:-1:-1

### ISSUE THREAD

**Issue by stefandrissen** [Riverside-Software/sonar-openedge#730]
Since I'm now copying relevant directories into a separate directory for SonarQube analysis (see question #725), I am getting some great results, but also these:

![image](https://user-images.githubusercontent.com/5297464/65122588-a2039400-d9f1-11e9-8ce1-1e65555eb659.png)

Line 12 of the include is:
````
   DEFINE NEW GLOBAL SHARED TEMP-TABLE ttcache_admdat NO-UNDO LIKE admdat.
````

**Comment by gquerret** [comment]
Is admdat a TT or a DB table ? If DB table, can you confirm if it's read from the sonar.oe.databases property ?
And can you reproduce with just this line in a separate file ?

**Comment by stefandrissen** [comment]
admdat is a database table - I now also see that I am getting this on every source - also on a simple FIND. But I know see that I made a mistake in copying the df files to tmp.sonar resulting in the df files not being where I wanted them to be.
