### ISSUE TITLE
OpenEdgeDBSensor: syntax error <unknown>: no viable alternative at input 'RENAME TABLE'

### ISSUE THREAD

**Issue by stefandrissen** [Riverside-Software/sonar-openedge#733]
````
[sonar:sonar] Analyzing exactcs35-70.df
[sonar:sonar] Syntax error <unknown>:161:7 no viable alternative at input 'RENAME TABLE'
````
The line in question:
````
RENAME TABLE "fas_gll" TO "x_fas_gll"
````

**Comment by gquerret** [comment]
The DF parser is there to analyze (and report issues on) full database schema, not on incremental dump file, so all update / rename / drop operations are not supported.

**Comment by gquerret** [comment]
Those incremental DF files can be skipped by using `sonar.exclusions` properties
