### ISSUE TITLE
Variable is read but never assigned - overlay / substring / entry

### ISSUE THREAD

**Issue by stefandrissen** [Riverside-Software/sonar-openedge#737]
````
DEFINE VARIABLE cfoo AS CHARACTER NO-UNDO.

OVERLAY( cfoo, 1, 3 ) = "bar":u.

IF cfoo = "bar":u THEN
   MESSAGE 1.
````
Also applies to:
- SUBSTRING( cfoo, 1, 3 ) = "bar":u
- ENTRY( 1, cfoo ) = "bar":u

**Comment by gquerret** [comment]
Confirmed

**Comment by movedoa** [comment]
See also https://github.com/Riverside-Software/sonar-openedge/issues/582

**Comment by gquerret** [comment]
Expressions that are part of the lvalue of an assignment don't have the UPDATING status correctly propagated. To be fixed in TreeParser

**Comment by gquerret** [comment]
Merged in develop
