### ISSUE TITLE
Can we improve styling of the rule description?

### ISSUE THREAD

**Issue by mikefechner** [Riverside-Software/sonar-openedge#758]
This looks so 1990 ....

![image](https://user-images.githubusercontent.com/13220627/68081107-cc29dd80-fe08-11e9-83df-7f1c340afb07.png)

**Comment by PeterJudge-PSC** [comment]
I know. All that upper-case code ..

**Comment by gquerret** [comment]
What do you want to improve ? The background color ? Fonts ? Overall look and feel ? Emoji ? 

My opinion (but I never thought that was an issue, even if I see this widget every day), is that the background color is not really beautiful but makes text readable. Code blocks could be made better with different bg color and smaller font size.

**Comment by cverbiest** [comment]
I think it would best follow the colour scheme rest of the eclipse viewers. 
That probably also includes a dark mode that is getting more and more popular.

A quick test shows a rather decent dark rendering
![image](https://user-images.githubusercontent.com/1312691/68316474-d3c3dd80-00b9-11ea-8df7-656410a8e14b.png)

**Comment by mikefechner** [comment]
> What do you want to improve ? The background color ? Fonts ? Overall look and feel ?

You must have adopted WebSpeed 1.0 templates from the late 1990 here. Yes it's about colors and fonts. Following the Eclipse Styling is what I'm hoping for. 

@cverbiest is there a setting for achieve what you show? Or is that a mock?

**Comment by cverbiest** [comment]
No mock, there are a few dark options
![image](https://user-images.githubusercontent.com/1312691/68372352-f2b98280-0140-11ea-8783-c33d2aecc0d8.png)
Unfortunately the editor looks really ugly in dark

**Comment by gquerret** [comment]
The rule documentation view colors can be configured with "Information Background / Text Color":
![image](https://user-images.githubusercontent.com/6498723/91189885-43f82a00-e6f3-11ea-90c9-d5250087ca89.png)
