### ISSUE TITLE
Variable is assigned but never read

### ISSUE THREAD

**Issue by dominickdm** [Riverside-Software/sonar-openedge#759]
When the variable name is the same as the class-name, i get a variable is assigned but never read error in the example below. 

I agree in this case the variable name could be improved..

![image](https://user-images.githubusercontent.com/40289256/69140700-5473d800-0ac3-11ea-915f-72c5c3f63478.png)

**Comment by gquerret** [comment]
Confirmed

**Comment by dominickdm** [comment]
Is a fix for this planned in one of the futur versions?

**Comment by gquerret** [comment]
There are multiple branches currently worked on for the expression engine of the parser. Still a few issues, but that will improve the recognition of this kind of expression.

**Comment by gquerret** [comment]
So yes, a fix will come

**Comment by gquerret** [comment]
Fixed in develop
