### ISSUE TITLE
Position wrong by one on backslash rule

### ISSUE THREAD

**Issue by mikefechner** [Riverside-Software/sonar-openedge#763]
![image](https://user-images.githubusercontent.com/13220627/70036824-cb29ce80-15b5-11ea-9758-d10abc85fa77.png)

I see the backslash at position four ... the rule message says three.

**Comment by stefandrissen** [comment]
All real programming languages are zero-based ;-)

**Comment by mikefechner** [comment]
Sorry - I was mistaken to think this was a tool for ABL developers ;)

**Comment by cverbiest** [comment]
![image](https://user-images.githubusercontent.com/1312691/70069152-99cef400-15f1-11ea-923b-4a13b2e71903.png)

**Comment by gquerret** [comment]
Will fix that !

**Comment by gquerret** [comment]
Fixed in develop
