### ISSUE TITLE
suppress buffer_usage cannot be provided per buffer

### ISSUE THREAD

**Issue by stefandrissen** [Riverside-Software/sonar-openedge#772]
In #605 suppression for the buffer_usage rule was added - to my surprise this only works on the entire function declaration and not on individual parameters as varusage suppression does:
````
DEFINE TEMP-TABLE ttbar NO-UNDO
   FIELD cc AS CHARACTER
   .

FUNCTION notSuppressed RETURNS LOGICAL (
   {&_proparse_ prolint-nowarn(buffer_usage)}
   BUFFER foo FOR ttbar
):

   RETURN TRUE.

END FUNCTION.
````
The suppression needs to be added above the function:
````
DEFINE TEMP-TABLE ttbar NO-UNDO
   FIELD cc AS CHARACTER
   .

{&_proparse_ prolint-nowarn(buffer_usage)}
FUNCTION isSuppressed RETURNS LOGICAL (
   BUFFER foo FOR ttbar
):

   RETURN TRUE.

END FUNCTION.
````

**Comment by gquerret** [comment]
I'm having a look at that. Historically, the nowarn preprocessor had to be located in the statement level. I'll see if it's possible to move that at the parameter level in some cases.

**Comment by gquerret** [comment]
In case it's really not convenient to have it at the parameter level, would something like `prolint-nowarn(buffer_usage_bufferName)` would be acceptable ?

**Comment by stefandrissen** [comment]
Ah, I see the nuance between an input variable on a procedure and an input variable on a function. 

This is on generated code. The code generator only knows of a block after it starts, which means I currently cannot add the preprocessor to the block. 

So a block level nowarn does not directly help - I'll just ignore the warnings for now.

**Comment by stefandrissen** [comment]
I just noticed that ``{&_proparse_ prolint-nowarn(varusage)}`` has always worked on parameter level for functions.

**Comment by gquerret** [comment]
The preprocessor directive has to be specified before the buffer name, not before the `BUFFER` keyword.
```
FUNCTION notSuppressed RETURNS LOGICAL ( BUFFER {&_proparse_ prolint-nowarn(buffer_usage)} foo FOR ttbar ):
   RETURN TRUE.
END FUNCTION.
```
