### ISSUE TITLE
EmptyBlock still fires on if then /* comment */

### ISSUE THREAD

**Issue by cverbiest** [Riverside-Software/sonar-openedge#773]
The empty block rule should fire when there is no code and not comment explaining why there is not statement.

This does not work for following code
```
define variable Name as character no-undo.
if Name > ""
then /* OK */ .
else do:
    undo, throw new Progress.Lang.AppError("Name is mandatory", 0).
end.
```
It shows *Empty code block in IF statement*

Can be worked around, but the extra block should not be necessary
```
define variable Name as character no-undo.
if Name > ""
then do: /* OK */ end.
else do:
    undo, throw new Progress.Lang.AppError("Name is mandatory", 0).
end.
```

**Comment by gquerret** [comment]
Reproduced, will be fixed.

Personal taste, but don't you find that
```
define variable Name as character no-undo.
if not (Name > "") then
    undo, throw new Progress.Lang.AppError("Name is mandatory", 0).
```
is more readable ?

**Comment by stefandrissen** [comment]
>Personal taste, but don't you find that
>
    define variable Name as character no-undo.
    if not (Name > "") then
        undo, throw new Progress.Lang.AppError("Name is mandatory", 0).
>is more readable ?

More readable, but also not equivalent. You are falling into the unknown value trap. The equivalent that does handle the unknown value is:

    if (Name > "") <> true then
       undo,...

Which I find a bit of an abomination - when the expression is more complex, inverting it often just makes it messy.

**Comment by gquerret** [comment]
> More readable, but also not equivalent. You are falling into the unknown value trap. 

Definitely right !

**Comment by gquerret** [comment]
This is controlled by the property allowCommentInEmptyIfElse. Did you try setting it to true ?

**Comment by cverbiest** [comment]
@gquerret That solves it, thank you
