### ISSUE TITLE
Sonarlint - StackOverflowError

### ISSUE THREAD

**Issue by clement-brodu** [Riverside-Software/sonar-openedge#778]
Hello,

For some of my programs, I have this error with sonarlint each time I save the program, and then the question "would you like to exit the workbench" and it close eclipse if I select YES.

![image](https://user-images.githubusercontent.com/37274615/75769966-55193d00-5d47-11ea-96d4-db129d73773c.png)

I reproduced it with this class : 
[UcRemise.zip](https://github.com/Riverside-Software/sonar-openedge/files/4280913/UcRemise.zip)

I supposed its because it's a quite big program, but it's just a usercontrol with some controls.

I have to disable sonarlint on my project to avoid this error (not cool).

Have you got an idea about this ?

**Comment by gquerret** [comment]
Sonar-OpenEdge version ?
Probably same as #689

**Comment by clement-brodu** [comment]
You are right ! I added `-Xss2m` and it works fine.

May be it could be a interesting to add this in your [wiki](https://github.com/Riverside-Software/sonar-openedge/wiki/SonarLint-for-Eclipse) ? 


Sonarlint : 4.2.1200
sonar-openedge : 2.6.4.

**Comment by gquerret** [comment]
A fix is already added in the develop branch, so the parameter won't be required anymore in 2.7
