### ISSUE TITLE
Sonar Scanner unable to recognize Preprocessor directives, Skips remaining content in the code.

### ISSUE THREAD

**Issue by ShubhamJavra** [Riverside-Software/sonar-openedge#780]
**My Work Environment:**

- Apache Ant(TM) version 1.10.7
- OpenEdge version 11.7.5
- PCT version 213
- sonarqube-8.1.0.31237
- sonar-scanner-4.2.0.1873-windows

My sonar.properties file looks something like this:
![image](https://user-images.githubusercontent.com/62879103/77897813-e5409880-7299-11ea-8929-0222d3fb1fb2.png)

And my build configurations are as follows:
![image](https://user-images.githubusercontent.com/62879103/77903973-79632d80-72a3-11ea-9152-c0dd903e6b8e.png)

Every time I run Sonar scanner on my Project the following error pops us on scan of any codefile containing a Preprocessor directive:
![image](https://user-images.githubusercontent.com/62879103/77898085-554f1e80-729a-11ea-8b65-e8627942545e.png)

Can anyone help me to solve this issue?

**Comment by gquerret** [comment]
This **usually** comes from a mix of CR and CRLF in the same file. You can open those files with Notepad++ for example, and enable View -> Show symbols -> Show end of line, then verify that they're consistent through the file.
Please also note that this "only" breaks the syntax highlight in the web view, but the rules will still be executed.
