### ISSUE TITLE
Update rules-plugin-template

### ISSUE THREAD

**Issue by clement-brodu** [Riverside-Software/sonar-openedge#782]
Hello, 

Is it possible to update your project rules-plugin-template please ?

I cant build my own plugin because of this line :

https://github.com/Riverside-Software/rules-plugin-template/blob/cd809f5ea2edbab90210cb8b9dbaeb9bf8b7a644/src/main/java/org/sonar/plugins/openedge/AcmeRulesDefinition.java#L29

 I don't know what is the third parameter of the constructor.

Thank you,

**Comment by gquerret** [comment]
Fixed
