### ISSUE TITLE
Coverage in SonarQube Dashboard is Blank

### ISSUE THREAD

**Issue by rishiraja18** [Riverside-Software/sonar-openedge#788]
Hi,
I am first time trying to set up the sonarqube for openedge ABL programs.I have followed the GitHub link https://github.com/Riverside-Software/sonar-openedge/wiki/Getting-started.

I have created one single ABL procedure for that i have created the ABLTest procedure and test suite.Compiled the code using <PCTCompile> and Unit test by <ABLUnit> enabled with profiler.

Compiling with OpenEdge 11.7, SonarQube 8.2(Free and OpenSource), SonarOpenEdge 2.7.1. The Code Coverage is blank in the SonarQube dashboard.

Shall i get the coverage information in the sonarQube free and open source version with the open-edge 2.7.1 plugin installed?.

Is that possible to install the cabl-security-rules-plugin-2.7.1.jar and riverside-rules-plugin-2.7.1.jar
in the sonarQube 8.2(free and OpenSource)??

Note:I have attached the build.xml,Debug log file and sonar-project.properties we have used.
![Build_xml](https://user-images.githubusercontent.com/62167071/79973368-af37a400-8454-11ea-8595-4bf3acb127ef.png)
[CMD_X_sonarlog_1.txt](https://github.com/Riverside-Software/sonar-openedge/files/4515593/CMD_X_sonarlog_1.txt)
![sonar_properties](https://user-images.githubusercontent.com/62167071/79973369-af37a400-8454-11ea-806d-b659cec02b8e.png)

Kindly guide me on this setup.Let me know if you need more info.
Thanks,
Raja

**Comment by gquerret** [comment]
Code coverage is available in the commercial set of rules, you can install an evaluation license ( see https://github.com/Riverside-Software/sonar-openedge/wiki/Getting-started#getting-an-evaluation-license-for-the-commercial-rules )
Apart from that, you build script seems ok to have code coverage info.

**Comment by rishiraja18** [comment]
Hi Gilles,
Thanks for your information.Let me create the evaluation license.
Thanks,
Raja
