### ISSUE TITLE
org.sonarlint.eclipse.core.prefs - 12.2 vs 11.7.5

### ISSUE THREAD

**Issue by stefandrissen** [Riverside-Software/sonar-openedge#789]
I have an 11.7.5 and a 12.2 PDOSE installation. They have a different opinion on what should be in the org.sonarlint.eclipse.core.prefs file.

11.7.5 wants:

    projectKey=Exact\:7.29-ui

but 12.2 wants:

    moduleKey=Exact\:7.29-ui

In source control I just have both lines, but every time I switch from 11.7.5 to 12.2 I need to rebind (after which I undo changes to the prefs file).

PDSOE 11.7.5 contains:

    SonarLint for Eclipse 4.2.1200
        SonarLint Core - Client API 4.5.0.RSSW
        ...
        SonarLint for Eclipse PDT 4.2.1201

PDSOE 12.2 contains:

    SonarLint Core - Client API 4.5.0.RSSW
    SonarLint for Eclipse 4.2.1203
    ...
    SonarLint for Eclipse PDT 4.2.1203

**Comment by stefandrissen** [comment]
Just to be sure - since I'm a bit overwhelmed with what I'm looking at - 12.2 seems to automatically contain the OEWhiteList-4.2-PSC branch (4.2.1203) version and you are recommending that I also use this with my 11.7.5?

**Comment by gquerret** [comment]
Yes, 12.2 contains OEWhiteList-4.2-PSC.
You can install:
* 4.2.1202 from OEWhiteList-4.2
* or 4.2.1203 from OEWhiteList-4.2-PSC
The only difference is that you have the demo rules in the PSC version. But you already have the full set of commercial rules with your subscription.

**Comment by stefandrissen** [comment]
Thanks - with 4.2.1202 11.7.5 also wants the projectKey instead of the moduleKey just like 12.2.

The last sonar-openedge release to include org.sonarlint.eclipse.site(-4.2.1200) was 2.6.0, will 4.2.1202 be released at some point?

**Comment by gquerret** [comment]
SonarLint and the OE plugin don't have the same release cycle. A download page will appear soon on https://cabl.riverside-software.fr, so there will be a central location for downloads.

I was a bit surprised at first with your issue, because there was no dependency change between 4.2.1201 and 4.2.1203. So I guess that's probably a side effect of some Eclipse internal API change.

**Comment by stefandrissen** [comment]
Great!
