### ISSUE TITLE
Unused buffer

### ISSUE THREAD

**Issue by stefandrissen** [Riverside-Software/sonar-openedge#791]
````
define temp-table tt no-undo
   field hb as handle
   .

procedure foo:
   define parameter buffer bu for tt.

   message bu.hb:buffer-field( "bar" ).

end procedure.
````

**Comment by hpmBravura** [comment]
Same issue when the buffer is passed to a class method:

METHOD PUBLIC LOGICAL Test( BUFFER pbttTest FOR ttTest):
    MESSAGE pbttTest.Field VIEW-AS ALERT-BOX.
  END METHOD.

**Comment by gquerret** [comment]
Probably too old, can't reproduce in 2.20 development
