### ISSUE TITLE
Security hotspot reopening false positives?

### ISSUE THREAD

**Issue by stefandrissen** [Riverside-Software/sonar-openedge#794]
Since the update to the latest version of the rules which include the security hotspot rules, I am seeing a source repeatedly reappear with 'new' code smells since leak.

In SonarQube I have marked the code smells as 'false positive'. 
When analysis is run again, the false positives have been cleared and are marked as code smell again, appearing as 'new' code smell since leak.

This source happens to also have two open Security Hotspot issues - coincidence?

**Comment by gquerret** [comment]
Regarding security hotspots, I'd say it's a coincidence. False positives and issue reopening is handled by SQ itself ; which version are you using ? If using 7.x, it may be worth trying with 7.9.x

**Comment by stefandrissen** [comment]
I'm on 7.3, I'll need to find some time to upgrade to 7.9, will close this issue (and keep closing the false positives) for now.
