### ISSUE TITLE
java.util.ConcurrentModificationException IN pdsoe 12.2 log file

### ISSUE THREAD

**Issue by cverbiest** [Riverside-Software/sonar-openedge#799]
I reported an OEDT issue and Lars Neumeier noted the log file contains the same error for Sonarlint.
see issue
[pdsoe.log](https://github.com/Riverside-Software/sonar-openedge/files/4680343/pdsoe.log)
 https://github.com/omecra/de.omecra.oedt.updatesite/issues/92 
and attached logfile

**Comment by gquerret** [comment]
Will be reported to Progress

**Comment by gquerret** [comment]
New version of SonarLint is using ABL code for DB connection, so this problem won't happen anymore
