### ISSUE TITLE
False positives with "Variables and parameters without NO-UNDO" rule

### ISSUE THREAD

**Issue by movedoa** [Riverside-Software/sonar-openedge#8]
The "Variables and parameters without NO-UNDO" rule finds a rule violation in the following code.
`DEFINE PARAMETER BUFFER lbBuffer FOR tTable.`

This is wrong, no-undo isn't allowed here.

**Comment by jakejustus** [comment]
Will be added as an exception, thanks for reporting.

**Comment by jakejustus** [comment]
Fixed in development (not available yet in 1.7.1)
