### ISSUE TITLE
"No RETURN statement in method" when method always throws error

### ISSUE THREAD

**Issue by LievenDeFoor** [Riverside-Software/sonar-openedge#801]
When a method always throws an error (e.g. NotImplementedException) you still get a warning saying the method has no return statement.

**Comment by gquerret** [comment]
Confirmed

**Comment by cverbiest** [comment]
I searched for NoReturnInFuncOrMethod in the issues but could not find any. Now it should turn up.

**Comment by gquerret** [comment]
Fixed in develop
