### ISSUE TITLE
Default buffer usage appears only once per file

### ISSUE THREAD

**Issue by maelstraggiotti** [Riverside-Software/sonar-openedge#806]
Hi,

The default buffer usage rule is only applied for the first occurence of a given buffer in a file. I'm not sure if that is a wanted behavior, or if it has always been the case. 

We upgraded to 2.8.0 some days ago.

For instance, the second line is not considered an issue: 
![image](https://user-images.githubusercontent.com/2782049/85991992-8ef80880-b9f4-11ea-998a-fd6e889d8ae9.png)

Thanks

**Comment by gquerret** [comment]
Yes, that was done on purpose, in order to reduce the noise (raising two issues doesn't bring more information). From the source code history, this has been the case since the beginning.
