### ISSUE TITLE
Space missing in rssw-oe-main:eu.rssw.antlr.proparse.checks.ClassNameCasing message 

### ISSUE THREAD

**Issue by cverbiest** [Riverside-Software/sonar-openedge#810]
The message
`Case of variable declaration doesn't match case of compiled classProgress.Lang.Object`
should have a space between class & the class name.
`Case of variable declaration doesn't match case of compiled class Progress.Lang.Object`

**Comment by gquerret** [comment]
Will be fixed, thanks for reporting !

**Comment by gquerret** [comment]
Fixed
