### ISSUE TITLE
Question: how to Create a custom rule (sonar-openedge-2.8.2)

### ISSUE THREAD

**Issue by T0RJMEN** [Riverside-Software/sonar-openedge#813]
hello :) , i want to write a custom rule for sonar-openedge-2.8.2 .
i have followed the instructions form this link : 
https://riverside-software.atlassian.net/wiki/spaces/OESONAR/pages/24510467/Write+custom+rules
but it' lock they do not have the same architecture ,
i need your help plz , thank you

**Comment by gquerret** [comment]
You should clone this repository: https://github.com/Riverside-Software/rules-plugin-template
It contains the entire structure to work with custom rules.

This [presentation](https://www.pugchallenge.eu/docs/default-source/presentations-2018/custom-rules-development-with-sonarqube.pdf?sfvrsn=91765e8_2) has details on what to modify in the source, and how to deploy it to your SQ instance.
