### ISSUE TITLE
vst table _Startup not known by parser

### ISSUE THREAD

**Issue by jurjendijkstra** [Riverside-Software/sonar-openedge#814]
the following statement results in Syntax errror -- no viable alternative at input 'mtc._Startup\r\n     no-lock' 

`find first mtc._Startup
     no-lock no-error.
`

(mtc is the logical dbname of the connected database)
Plugin version 2.8.2 in Sonarqube version 7.9.3

**Comment by gquerret** [comment]
Confirmed

**Comment by gquerret** [comment]
From Database Administration Guide:

> Note: Starting in OpenEdge Release 11.5, this VST is no longer updated. Use the _DbParams VST. See Database startup parameters file status (_DbParams) on page 857.

Table has been brought back to the metaschema, will be available in next version.

**Comment by jurjendijkstra** [comment]
ooh that's interesting, thanks! In that case I am glad with the syntax error :-)

**Comment by gquerret** [comment]
I'll probably add a quick rule to report usage of this table.
