### ISSUE TITLE
Class properties marked as assigned but never read when not referenced directly

### ISSUE THREAD

**Issue by bennettBuckley** [Riverside-Software/sonar-openedge#816]
![image](https://user-images.githubusercontent.com/8454993/88408828-15a8c700-cda2-11ea-86ca-d70dcd3ad25a.png)

So far, I've observed this with method calls and properties.

The issue does not appear when I drop the `this-object:`

**Comment by gquerret** [comment]
Confirmed.

**Comment by gquerret** [comment]
Long standing issue, raising priority, there's no good reason this bug is still there...

**Comment by gquerret** [comment]
Fixed
