### ISSUE TITLE
How JPnode class work

### ISSUE THREAD

**Issue by T0RJMEN** [Riverside-Software/sonar-openedge#817]
hello , i gonna create a new custom rule for openEdage , but the problem is  i don't know how to work with Jnode class 
(it's take block of code work on it ? or all the programm ) , please can you give more informations ,thank you very much

**Comment by gquerret** [comment]
There's no specific tutorial for JPNode usage. But if you turn on property `sonar.oe.proparse.debug`, you'll be able to browse the syntax tree. You can search for specific nodes using the various `query` methods.
