### ISSUE TITLE
Abbreviated keyword RCODE-INFO

### ISSUE THREAD

**Issue by movedoa** [Riverside-Software/sonar-openedge#818]
#534 is back with the current version.
Not sure when it regressed, could be broken a while already.

**Comment by gquerret** [comment]
What's the value of the attribute in the AbbreviatedKeyword rule in your profile ?

**Comment by movedoa** [comment]
I'm not sure what you mean with "attribute of the rule". Do you mean the excludedKeywords setting of the rule?
The value is `INITIAL,FILE-INFORMATION,FORWARDS,ASCENDING,DESCENDING,ABSOLUTE,MODULO,COLUMN`

**Comment by gquerret** [comment]
Yes, that's what I was talking about. The value of this attribute in the default quality profile is: `DEFINE,VARIABLE,CHARACTER,INTEGER,DECIMAL,LOGICAL,PARAMETER,COLUMN,NO-LABELS,FILE-INFORMATION,FORWARDS,ACCUMULATE,RCODE-INFORMATION`

![image](https://user-images.githubusercontent.com/6498723/88709350-4a57ae00-d115-11ea-9d3f-53eef3a16f1b.png)

Just change the value in the profile you're using.

**Comment by gquerret** [comment]
The default value was changed in the rule 2 years ago. But if you upgraded SonarQube, that may have affected the way quality profiles are updated when default values are changed.

**Comment by movedoa** [comment]
Strange stuff, i'm sure i tried this after the initial fix. Anyway, I added the keyword to the ignore list. Thx.
