### ISSUE TITLE
Parser syntax error

### ISSUE THREAD

**Issue by bennettBuckley** [Riverside-Software/sonar-openedge#820]
![image](https://user-images.githubusercontent.com/8454993/88966760-d33c2a00-d27a-11ea-9173-66552c4dfd97.png)

Error encountered when trying to create a database record. The actual code runs fine.

**Comment by gquerret** [comment]
This table is probably not available in your database schema. Check the value of `sonar.oe.databases`, and verify that the table could be found here.

**Comment by bennettBuckley** [comment]
I checked my configs, and sure enough, the schema file wasn't there. Adding it resolved the issue. I just got thrown off because there were record creates in other files that weren't resulting in this.
