### ISSUE TITLE
Code coverage scanner missing some lines

### ISSUE THREAD

**Issue by bennettBuckley** [Riverside-Software/sonar-openedge#821]
![image](https://user-images.githubusercontent.com/8454993/89072457-9c334a80-d346-11ea-9edd-f6c241f366a7.png)
![image](https://user-images.githubusercontent.com/8454993/89072616-e4eb0380-d346-11ea-8d98-35ff62159092.png)
![image](https://user-images.githubusercontent.com/8454993/89072665-fc29f100-d346-11ea-830a-e6685f1025c9.png)

It appears that `CATCH` block openers, `FINALLY` block openers, and `CASE` block closers don't get marked as covered for some reason, even if the contents of their blocks is fully covered.

**Comment by gquerret** [comment]
That's a Progress issue, which is already reported.

**Comment by bennettBuckley** [comment]
Is there a Progress case number, community post, or a vote link we can keep track of?

**Comment by gquerret** [comment]
That was direct communication with the engineering team, I don't have any case number available for now. I'll try to find it. That was reported in 2018 :-)

**Comment by bennettBuckley** [comment]
Just following up to see if you found that correspondence you mentioned. I'm also curious if you intend to follow up with a trackable report with Progress.

**Comment by gquerret** [comment]
No answer from Progress yet. I'll reply as soon as I have an answer.

**Comment by bennettBuckley** [comment]
Any update on this?

**Comment by gquerret** [comment]
No news, I'll open the issue and see if they already have a ticket for that.

**Comment by gquerret** [comment]
@bennettBuckley https://community.progress.com/s/article/profiler-code-coverage-doesn-t-record-the-end-case-or-the-finally-statements
