### ISSUE TITLE
preprocessor directives

### ISSUE THREAD

**Issue by T0RJMEN** [Riverside-Software/sonar-openedge#829]
hello , where can find documentation about each preprocessor directives of AblNodeType.class plz

![Capture](https://user-images.githubusercontent.com/68420659/89638849-cb007200-d8ac-11ea-8ad1-37a22632e166.PNG)

**Comment by gquerret** [comment]
Many are unused, and the only source of documentation is the source code itself. Your IDE should give you the references where each type is being used. As this is assigned to the node type of JPNode, if you don't find a reference then it's just that this specific type is unused.
