### ISSUE TITLE
File exclusions: not working?

### ISSUE THREAD

**Issue by dominickdm** [Riverside-Software/sonar-openedge#834]
Hello,

Is there anyone who is able to use the 'file exclusion' feature? This is not working for me (plugin version 4.2.1221)

Use case: we have some files with a processingtime of +20 sec, so we don't want to analyse them on every save. 
![image](https://user-images.githubusercontent.com/40289256/90635588-a18b0300-e229-11ea-86ba-0eaf90406340.png)

FYI: log of the sonar analysis of the mentioned file:
```
AST Generation | time=11829 ms
XML Parsing    | time=0 ms
Rule mips-rules:be.mips.sonar.rules.ChrAscRule | time=72 ms
Rule rssw-oe-main:Deprecated_gp_calld | time=0 ms
Rule rssw-oe-main:SESSION_CHARSET_obsolete | time=36 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.AbbreviatedKeywords | time=45 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.AbbreviatedTableName | time=40 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.BackslashCurlyBrace | time=641 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.BackslashInIncludeFile | time=3 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.BackslashInString | time=80 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.BlockLabel | time=654 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.BufferUsage | time=699 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.ClassNameCasing | time=2 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.ColonForBlock | time=37 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.ColonTTrim | time=39 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.CommentedOutCode | time=2193 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.DefaultWidgetName | time=644 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.DisableTriggers | time=37 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.DosKeyword | time=37 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.DotComment | time=41 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.DuplicateCase | time=35 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.EmptyBlock | time=765 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.EmptyFieldsList | time=36 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.EmptyStatement | time=36 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.EndType | time=599 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.ExpressionNoEffect | time=36 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.HiddenVariable | time=12359 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.I18NLength | time=105 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.InvalidUseIndex | time=630 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.LongStrings | time=45 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.NestedDo | time=36 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.NoReturnInFinally | time=35 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.NoReturnInFuncOrMethod | time=2 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.NoRoutineInLoop | time=35 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.NoRoutineInWhere | time=581 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.NoUndo | time=670 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.NoWait | time=601 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.PublicVariable | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.SerializableError | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.ShareLock | time=623 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.StringAttribute | time=40 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.SubstituteLongChar | time=36 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.ToDoTracker | time=73 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.UndoWithoutOption | time=36 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.UnixKeyword | time=589 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.UnusedBuffer | time=4 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.UnusedVariable | time=7 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.UpperCaseKeywords | time=600 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.UsingStars | time=26 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.VariableAssignedButNotRead | time=3 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.VariableReadButNotAssigned | time=27 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.WhereCanDo | time=29 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.WrongAssignWhen | time=37 ms
Rule rssw-oe:org.sonar.plugins.openedge.checks.ClumsySyntax | time=0 ms
Rule rssw-oe:org.sonar.plugins.openedge.checks.LargeTransactionScope | time=36 ms
```

**Comment by stefandrissen** [comment]
From your screenshots I cannot see what directory the files you intend to exclude are in.

For me it works fine with ``**/g*.p``

** = any level of directories deep.

I am using:
- SonarLint Core - Client API 4.5.0.RSSW 
- SonarLint for Eclipse 4.2.1203

**Comment by gquerret** [comment]
I hope that Stefan comment will help. But I'd like to improve the parse time, 11 seconds is way too much. Can you generate a preprocessed version of the file (with the ABL compiler), and try to run the analysis on it ? I'd first like to know if it comes from the lexer / preprocessor, or from the parser itself.

**Comment by dominickdm** [comment]
@stefandrissen : thanks for your suggestion Stefan, unfortunately adding '**/ed_ord.p' didn't help either. Even with right mouse click in the Project explorer, 'SonarLint=>Exclude' (full path is added), the file is still processed.

@gquerret: the SonarLint processing time of the preprocessed file is faster, generating the _pp file takes about 6 seconds.

1 files proparse'd, 0 XML files, 0 listing files, 0 failure(s), 0 NCLOCs
AST Generation | time=1464 ms
XML Parsing    | time=0 ms
Rule mips-rules:be.mips.sonar.rules.ChrAscRule | time=31 ms
Rule rssw-oe-main:Deprecated_gp_calld | time=0 ms
Rule rssw-oe-main:SESSION_CHARSET_obsolete | time=15 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.AbbreviatedKeywords | time=17 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.AbbreviatedTableName | time=16 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.BackslashCurlyBrace | time=528 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.BackslashInIncludeFile | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.BackslashInString | time=33 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.BlockLabel | time=31 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.BufferUsage | time=39 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.ClassNameCasing | time=1 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.ColonForBlock | time=17 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.ColonTTrim | time=16 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.CommentedOutCode | time=680 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.DefaultWidgetName | time=17 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.DisableTriggers | time=16 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.DosKeyword | time=519 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.DotComment | time=15 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.DuplicateCase | time=16 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.EmptyBlock | time=54 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.EmptyFieldsList | time=15 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.EmptyStatement | time=16 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.EndType | time=15 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.ExpressionNoEffect | time=16 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.HiddenVariable | time=2131 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.I18NLength | time=44 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.InvalidUseIndex | time=16 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.LongStrings | time=17 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.NestedDo | time=16 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.NoReturnInFinally | time=15 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.NoReturnInFuncOrMethod | time=1 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.NoRoutineInLoop | time=15 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.NoRoutineInWhere | time=16 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.NoUndo | time=37 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.NoWait | time=17 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.PublicVariable | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.SerializableError | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.ShareLock | time=17 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.StringAttribute | time=18 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.SubstituteLongChar | time=15 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.ToDoTracker | time=33 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.UndoWithoutOption | time=16 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.UnixKeyword | time=15 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.UnusedBuffer | time=4 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.UnusedVariable | time=4 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.UpperCaseKeywords | time=16 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.UsingStars | time=16 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.VariableAssignedButNotRead | time=23 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.VariableReadButNotAssigned | time=7 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.WhereCanDo | time=16 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.WrongAssignWhen | time=16 ms
Rule rssw-oe:org.sonar.plugins.openedge.checks.ClumsySyntax | time=0 ms
Rule rssw-oe:org.sonar.plugins.openedge.checks.LargeTransactionScope | time=16 ms
Found 209 issue(s)

**Comment by stefandrissen** [comment]
> @stefandrissen : thanks for your suggestion Stefan, unfortunately adding '**/ed_ord.p' didn't help either. Even with right mouse click in the Project explorer, 'SonarLint=>Exclude' (full path is added), the file is still processed.
 
I just noticed that you are adding the exclusion on the project preferences. I added the GLOB exclusion in the workspace preferences. 

After moving it to the project preferences, exclusion behavior is still correct. At one point I did think the progress view was SonarLinting files it should not, but the SonarLint console contradicted that and did not show files that are excluded.

**Comment by gquerret** [comment]
I confirm I have some problems with FILE exclusions, I'll investigate this problem.
But the GLOB exclusion at the project or workspace level always worked for me.

**Comment by gquerret** [comment]
As opposed to what's written in the "Create exclusion" window, you have to use backslashes when excluding files.

![image](https://user-images.githubusercontent.com/6498723/91048531-18564080-e61c-11ea-85f4-c034d4b4dd7e.png)

This is a bug.

**Comment by dominickdm** [comment]
Great, that works indeed, thanks @gquerret 

Is it normal that I can't analyze the file manually after it has been added to the exclude list? I was hoping to exclude it only for automatic processing, but it seems that the SonarLint options are both grayed out.

![image](https://user-images.githubusercontent.com/40289256/91130136-7847f800-e6ab-11ea-9086-ac3d3edc52d8.png)

**Comment by gquerret** [comment]
Unfortunately, once a file is excluded, it won't be analyzed (even when manually triggered). I'll contact you offline regarding the time it takes to parse the code. Finding the bottleneck will improve parse time for everybody.
