### ISSUE TITLE
Too many parameters in call: non default numParameters ignored

### ISSUE THREAD

**Issue by stefandrissen** [Riverside-Software/sonar-openedge#835]
Yesterday I changed the value for numParameters from it's default 15 to 16 before checking in some sources that needed 16 parameters:

![image](https://user-images.githubusercontent.com/5297464/90725581-b1a1f180-e2c0-11ea-9f2b-df68fbafeada.png)

After check in, SonarQube analysis was executed, but the change in parameters seems to have been ignored and I have new leaks:

![image](https://user-images.githubusercontent.com/5297464/90725723-e57d1700-e2c0-11ea-8d42-ede93c8d453e.png)

**Comment by gquerret** [comment]
Somebody else reported an issue (not in the issue tracker) with this rule at the beginning of the week. It just seems that the rule doesn't know how to count (or perhaps starts counting at 0). I'll confirm today or tomorrow.

**Comment by gquerret** [comment]
I confirm the rule doesn't report the right number (starts counting at 0). So in your example, I'd say you have 16 parameters, while it incorrectly says there 15.
This has been fixed in the development branch.

**Comment by stefandrissen** [comment]
How it can it just be about reporting the right number? My rule has been changed from default 15 to 16 and my run statement has 16 parameters, so nothing should be reported.

**Comment by gquerret** [comment]
Comparison is done with "greater or equal" so if you have 16 parameters and parameter set to 16, then it has to report an issue.

**Comment by stefandrissen** [comment]
Aha, of course. The error was throwing me off. Thanks.
