### ISSUE TITLE
Variable x is assigned but never read

### ISSUE THREAD

**Issue by movedoa** [Riverside-Software/sonar-openedge#839]
Version 2.9.0 (But not a new bug afaik)

Setting a property in an object doesn't count as using the variable.

```
CLASS Foo:

   DEFINE VARIABLE oData AS DataClass NO-UNDO.

   CONSTRUCTOR PUBLIC Foo(
      poData AS DataClass
   ):
      THIS-OBJECT:oData = poData.
   END CONSTRUCTOR.

   METHOD PUBLIC VOID SetFooData(
      cValue AS CHARACTER
   ):
      THIS-OBJECT:oData:SomeProp = cValue.
   END METHOD.

END CLASS.
```

**Comment by gquerret** [comment]
THIS-OBJECT references should have been improved in 2.9. I'll have a look at this kind of reference.

**Comment by movedoa** [comment]
> THIS-OBJECT references should have been improved in 2.9. I'll have a look at this kind of reference.

2.9 fixed about 1000 THIS-OBJECT FPs for us. I guess this is a different problem  that got lost in the noise before.

**Comment by gquerret** [comment]
> 2.9 fixed about 1000 THIS-OBJECT FPs for us.

Still a lot of room for improvement, but good to hear lots of FPs are gone.

**Comment by gquerret** [comment]
Fixed in develop
