### ISSUE TITLE
Proparse error when parsing "disable triggers for load of"

### ISSUE THREAD

**Issue by lparcerisa** [Riverside-Software/sonar-openedge#843]
`disable triggers for load of Foo.`

This is triggering a "Proparse error" issue.
Could this be enhanced so the parsing works fine?

As a note, this workds fine: `disable triggers for dump of Bar.`

**Comment by gquerret** [comment]
Not able to reproduce for now ; are you using sonar-openedge 2.9.0 ?
And can you confirm if you have a table "Foo" in the DF files referenced by sonar.oe.databases ?

**Comment by lparcerisa** [comment]
Hi Gilles,

We are using sonar-openedge-plugin-2.8.2 ; we can retest it once we've
upgraded to 2.9.0.

We will also double-check the access to "Foo", but just above the flagged
line there is the following statement that is not throwing any error:

   - disable triggers for dump of Foo.

Br,
Lluís.

Missatge de Gilles QUERRET <notifications@github.com> del dia dc., 23 de
set. 2020 a les 11:20:

**Comment by lparcerisa** [comment]
Hi Gilles,

we tried with plugin 2.9.0 and were getting the same error.

However, it appears the project does not have access to the schema during
the analysis (we don't have the sonar.oe.databases pointing to the df
file), so we might need to reconsider our setup (or the rules we apply to
the file).

Thank you for the attention!

Br,
Lluís.

Missatge de Lluís Parcerisa Giné <parcerisa@gmail.com> del dia dc., 23 de
set. 2020 a les 11:26:
