### ISSUE TITLE
IConstants

### ISSUE THREAD

**Issue by T0RJMEN** [Riverside-Software/sonar-openedge#845]
hello , i'm trying to create a custom rule on temp-tables , i want know my RECORD_NAME  is temp-table or not 
 * nodeC : RECORD_NAME (TempTable)
 * nodeC.attrGet(IConstants.ST_TTABLE)  always give me false value 
can anyone help me plz

**Comment by gquerret** [comment]
Use `node.attrGet(IConstants.STORETYPE) == IConstants.ST_DBTABLE`

**Comment by T0RJMEN** [comment]
it's work , Thank you very much sir !!
