### ISSUE TITLE
Variable x is assigned but never read should ignore catch

### ISSUE THREAD

**Issue by movedoa** [Riverside-Software/sonar-openedge#852]
The ABL doesn't allow CATCH without a parameter.
The rule should ignore the parameter in catch since it produces a lot of FPs.

![grafik](https://user-images.githubusercontent.com/13309951/96147667-d05ee600-0f07-11eb-9fd9-c5fc79006a80.png)

**Comment by movedoa** [comment]
Sorry fogot the version.
This is with 2.10

**Comment by gquerret** [comment]
> This is with 2.10

Fast upgrade :-)
I'll reproduce and fix issue.

**Comment by stefandrissen** [comment]
As Jurjen says. This rule also correctly catches unused error objects in previous versions.
You need to throw e or check something of e.

**Comment by gquerret** [comment]
There's another rule which should be triggered in this case.

**Comment by gquerret** [comment]
This rule should be triggered: https://sonar.riverside-software.fr/coding_rules?languages=oe&open=rssw-oe-main%3Aeu.rssw.antlr.proparse.checks.LogRethrowException&q=rethrow
The unused variable should not be triggered in this case in order to avoid raising two identical issues

**Comment by stefandrissen** [comment]
Ah - that's the one I was mixing it up with. :-) Thanks @movedoa - I'll postpone my upgrade a bit.

**Comment by gquerret** [comment]
Small change was introduced in 2.10, and unit tests were incorrect for this case... Fixed in develop, that will go in 2.11
