### ISSUE TITLE
ERROR: Unable to parse TTest/PROG.P - Can't find include file 'testInclude.i' from 'TTest/PROG.P'

### ISSUE THREAD

**Issue by T0RJMEN** [Riverside-Software/sonar-openedge#856]
my program can't find the include file in the same directory, any help plz 

**my properties file**
_sonar.oe.propath.dlc		= 	true
sonar.oe.file.suffixes  	=   p,w,t,sha*,CLS,t
sonar.oe.include.suffixes	=	sha,i01,i02,i03,i04,i05,i06,i07,fra,i_

**Comment by gquerret** [comment]
Did you define `sonar.oe.propath` ?
