### ISSUE TITLE
Mismatch input "SELECT"

### ISSUE THREAD

**Issue by hpmBravura** [Riverside-Software/sonar-openedge#859]
Hi Gilles,
Getting `Mismatched input ''SELECT'', expecting '{<EOF>, END}' in <filename>`. Not sure what's the problem, the code compiles OK.

![Mismatch input SELECT](https://user-images.githubusercontent.com/75454805/101098699-792be680-3617-11eb-86b8-bf5b5bfc241a.png)
.

**Comment by gquerret** [comment]
SQL statements support was dropped in version 2.5. See issue #685.
If you're running 2.10, you can add `{&_proparse_ skip-section}` directives to skip some sections of the code. See issue #851 and [release notes of 2.10](https://github.com/Riverside-Software/sonar-openedge/releases/tag/V2.10.0)
