### ISSUE TITLE
No attribute in string for external procedures

### ISSUE THREAD

**Issue by stefandrissen** [Riverside-Software/sonar-openedge#861]
````
procedure WideCharToMultiByte external "kernel32.dll".

end procedure.
````
These strings are not translated, so while a :u can be added, it has no significance.

**Comment by jurjendijkstra** [comment]
you mean the string is not exported and sent to the (external) translators team, so they get no chance to screw it up and translate this into "pit32.dll"?  (after all they do get payed per translated word).

Are you sure? I am not. When in doubt then just add the :U

**Comment by stefandrissen** [comment]
Yes, I am sure.

And just for confirmation, with procedure:
````
procedure hello external "debtor".
end procedure.

procedure world:    
   message "creditor".   
end procedure.   

````
Compiled as (with connection to translat database):
````
compile "procedure.p" language( "nl,fr" ) save.
````
Results in one translation warning:
````
WARNING: Translation of 'creditor' to 'crediteur' 
in language 'nl' exceeds allocated length of 8 characters. (4788)
````
If I turn the two strings around, then I also only get one translation warning:
````
WARNING: Translation of 'debtor' to 'debiteur' 
in language 'nl' exceeds allocated length of 6 characters. (4788)
````

**Comment by gquerret** [comment]
Fixed in develop
