### ISSUE TITLE
Use colon instead of period to start a block

### ISSUE THREAD

**Issue by stefandrissen** [Riverside-Software/sonar-openedge#862]
````
procedure WideCharToMultiByte external "kernel32.dll".

end procedure.
````
While I have always been a colon starts a block supporter, the [documentation](https://documentation.progress.com/output/ua/OpenEdge_latest/index.html#page/dvref/procedure-statement.html) does state a nuance for external procedures which I can appreciate:

> You can terminate a PROCEDURE statement with either a period (.) or a colon (:), but typically use a colon (:) for a procedure definition or prototype that includes procedure-body and a period (.) for a procedure definition or prototype that omits any procedure-body.

**Comment by gquerret** [comment]
Fixed in develop
