### ISSUE TITLE
Whole index not recognized and "couldn't be assigned" error

### ISSUE THREAD

**Issue by daanflore** [Riverside-Software/sonar-openedge#869]
Hello,

After following the steps we found in #866 we noticed we still have some problems with the whole-index not being detected or annotated.

## couldn't be assigned error
For this error we have a program that contains if else logic and depending if we use the "DO" keyword the whole-index can be assigned or not.

```OpenEdge ABL
IF lvInteger = 1 
THEN DO:
  FIND FIRST Sports2000.Customer NO-LOCK WHERE Sports2000.Customer.Balance = 10.
END.
ELSE
  FIND FIRST Sports2000.Customer NO-LOCK WHERE Sports2000.Customer.Balance = 10.
```
In the example above sonarlint detects the whole index on both lines but is only able to show to error on the line with the "DO" keyword.
![image](https://user-images.githubusercontent.com/10918566/106754519-5cb72500-662d-11eb-80f3-20b27080f792.png)

For the other whole index we find the following error in the sonarlint console.
![image](https://user-images.githubusercontent.com/10918566/106754713-9851ef00-662d-11eb-9027-a81676df8393.png)

Based on the line nr of error it looks like the whole-index is on the line of the else and not the query itself.
If I check the Xref file the line nr there is also 7.

```Xml
    <Reference Reference-type="SEARCH" Object-identifier="Sports2000.Customer">
      <Source-guid>sc+XfLMUBpl5FFN3ID+1IA</Source-guid>
      <File-num>1</File-num>
      <Ref-seq>9</Ref-seq>
      <Line-num>7</Line-num>
      <Object-context>CustNum</Object-context>
      <Access-mode/>
      <Data-member-ref/>
      <Temp-ref/>
      <Detail>WHOLE-INDEX</Detail>
      <Is-static>false</Is-static>
      <Is-abstract>false</Is-abstract>
    </Reference>
```

## Whole index not detected

The second situation we have is, that in structured procedures without db-Required the "WHOLE-INDEX" isn't detected by sonarlint in the main block.
If  the same code is added in a internal procedure sonarlint detects the whole index.
![image](https://user-images.githubusercontent.com/10918566/106758389-bd486100-6631-11eb-92e2-feb5494f226a.png)

If I look in the sonar-lint log I see the some "WHOLE-INDEX" errors are found but not all of them:
```Text
WHOLE-INDEX search on 'Sports2000.Customer' with index 'CustNum' couldn't be assigned to C:\PSCWORKSPACES\DAFL\git\test\src\StructuredProcedure.p at line 85
WHOLE-INDEX search on 'Sports2000.Customer' with index 'CustNum' couldn't be assigned to C:\PSCWORKSPACES\DAFL\git\test\src\StructuredProcedure.p at line 93
WHOLE-INDEX search on 'Sports2000.Customer' with index 'CustNum' couldn't be assigned to C:\PSCWORKSPACES\DAFL\git\test\src\StructuredProcedure.p at line 119
WHOLE-INDEX search on 'Sports2000.Customer' with index 'CustNum' couldn't be assigned to C:\PSCWORKSPACES\DAFL\git\test\src\StructuredProcedure.p at line 122
WHOLE-INDEX search on 'Sports2000.Customer' with index 'CustNum' couldn't be assigned to C:\PSCWORKSPACES\DAFL\git\test\src\StructuredProcedure.p at line 127
WHOLE-INDEX search on 'Sports2000.Customer' with index 'CustNum' couldn't be assigned to C:\PSCWORKSPACES\DAFL\git\test\src\StructuredProcedure.p at line 153
WHOLE-INDEX search on 'Sports2000.Customer' with index 'CustNum' couldn't be assigned to C:\PSCWORKSPACES\DAFL\git\test\src\StructuredProcedure.p at line 155
WHOLE-INDEX search on 'Sports2000.Customer' with index 'CustNum' couldn't be assigned to C:\PSCWORKSPACES\DAFL\git\test\src\StructuredProcedure.p at line 158
```
In the xref file I find the line 83 contains a "WHOLE-INDEX"
```XML
<Reference Reference-type="SEARCH" Object-identifier="Sports2000.Customer">
      <Source-guid>sc+XfLMUBpl5FJl3DEnAkg</Source-guid>
      <File-num>1</File-num>
      <Ref-seq>8</Ref-seq>
      <Line-num>83</Line-num>
      <Object-context>CustNum</Object-context>
      <Access-mode/>
      <Data-member-ref/>
      <Temp-ref/>
      <Detail>WHOLE-INDEX</Detail>
      <Is-static>false</Is-static>
      <Is-abstract>false</Is-abstract>
    </Reference>
```
The same file without the preprocessors show the correct errors without taking in account the "couldn't be assigned error"

# Environment info
Name | Value
------------ | -------------
Progress | 12.2.3
Sonarlint| 5.5.1510
Database| sports2000

Here is a zip that contains the log of sonarlint and the .p I used to simmulate the problems.
[example.zip](https://github.com/Riverside-Software/sonar-openedge/files/5919097/example.zip)

**Comment by gquerret** [comment]
For the first issue, I'm still waiting for a fix from Progress. As you already noticed, the XREF file has the wrong line number when there's no `DO` block, and it was decided not to try to guess which line the WHOLE-INDEX really belongs to. This is also the case when you multiple `CAN-FIND` in the same statement for example. I don't know when Progress will fix this problem, but I don't think that's a P1 for them.
For the second part, and as explained in #866, some code sections just discard all issues. Let me check how this is done is your example, but I'd say it's a bug.

**Comment by gquerret** [comment]
Reproduced, the `&ANALYZE-SUSPEND _UIB-CODE-BLOCK _CUSTOM _MAIN-BLOCK Procedure` preprocessor incorrectly hides issues. That will be fixed in next version.

**Comment by gquerret** [comment]
Fixed

**Comment by gquerret** [comment]
Just in case if you want to test the fix, a temp version is available here:
https://dl.rssw.eu/org.sonarlint.eclipse.site-5.5.1511.zip
