### ISSUE TITLE
syntax error : no viable alternative at input: 'table name

### ISSUE THREAD

**Issue by VandaelePeter** [Riverside-Software/sonar-openedge#871]
Hi,
I get errors parsing files that have buffers on one database. The buffers on other databases are parsed correctly.
In this specific case the error is:
```
Syntax error -- glims-abl-sources/man/stn_qce.p:460:36 -- no viable alternative at input 'gp_Translator'
Error during code parsing for [uri=file:/C:/workspace/dv/glims_dev_pro/glims-abl-sources/man/stn_qce.p] at position glims-abl-sources/man/stn_qce.p:460:36
```

the content of that line:
```
    DEFINE BUFFER b_Translator FOR gp_Translator.
```
But as you can see in the attached image, the db is connected and the table is in place
![gp_language](https://user-images.githubusercontent.com/79246632/108319260-66aa5d80-71c1-11eb-8e38-85d26c39b6c4.png)

**Comment by VandaelePeter** [comment]
I found out that 2 of my connected databases had the same identifier. So I restored one of those databases with the -newinstance option to get a unique GUID. But the problem persists.

**Comment by gquerret** [comment]
What is your SonarLint version ?

**Comment by VandaelePeter** [comment]
it is 5.5.1509

**Comment by VandaelePeter** [comment]
For some reason there was only one DB in the dblist.txt. I removed all the schema holders and dblist file.
Now it's back up and running.
