### ISSUE TITLE
ON statement in class

### ISSUE THREAD

**Issue by gquerret** [Riverside-Software/sonar-openedge#878]
On behalf of CASOL and RBC

This code can't be parsed by Proparse:
```
class package.foobar:

  define private static property prop1 as int64 no-undo get.

  on 'entry':u anywhere do:
    // Triggers are valid
  end.

  method private static int64 xxx(zz as int64):
    // Impl
  end method.

end class.
```

Error message:
```
No viable alternative at input 'method private'
```

**Comment by gquerret** [comment]
Fixed in develop

**Comment by mikefechner** [comment]
@gquerret do you remember what the issue was here? Because "our" proparse implementation has no problem with the sample code from this ticket here.

**Comment by gquerret** [comment]
The ANTLR4 parser limits the statements that can be found in a class. The `ON` statement was not supported. IIRC, the ANTLR2 parser allowed any statement in a class so your version is probably not affected.

😈 Time to drop this implementation 😈

**Comment by mikefechner** [comment]
... but it works so well ;)
