### ISSUE TITLE
Shared lock record access - FIND-BY-ROWID

### ISSUE THREAD

**Issue by clement-brodu** [Riverside-Software/sonar-openedge#880]
Hello,

I had a bug in my code because of a `FIND-BY-ROWID` without `NO-LOCK`.

Is it possible to have a rule to detect this case and encourage the developer to explicitly specify the desired lock for those kind of functions ?

Thank you

**Comment by gquerret** [comment]
ShareLock rule can be enhanced to handle this case

**Comment by gquerret** [comment]
Included as an option of the ShareLock rule.
