### ISSUE TITLE
do you recommend SonarQube 8.9 LTS

### ISSUE THREAD

**Issue by jurjendijkstra** [Riverside-Software/sonar-openedge#881]
Just a question. Are the plugins version 2.13.0 compatible with the brand new SonarQube 8.9 LTS? 

(I know my question is a little bit too soon because 8.9 is not released yet. It is planned for today)

**Comment by gquerret** [comment]
SonarQube 8.9 was released a few hours after your question. On my side, I delayed the 2.13 version to validate the compatibility  with 8.9, but finally had to release it before 8.9... Compatibility will be verified this week, but as it's already compatible with 8.8, I don't expect any breaking change.

**Comment by jurjendijkstra** [comment]
That's good to know, thanks, then I will delay the update to 8.9 a week or two, just to be on the safe side.

**Comment by gquerret** [comment]
Initial tests of SonarQube 8.9 don't show any regression, but we'll continue with the full suite.
One thing that changed since 8.9 is the risk consent dialog box when using non-SonarSource plugins ; this is explained here: https://jira.sonarsource.com/browse/MMF-2301
No real impact apart from the small annoyance when first time connecting as an administrator.

**Comment by gquerret** [comment]
Full test suite has been executed, no regression has been found on those projects (apart from the minor annoyance in the previous comment).

**Comment by jurjendijkstra** [comment]
Thanks!

**Comment by tom9k** [comment]
Hi, 

may I ask you to initiate an update of the Plugin version matrix?
https://docs.sonarqube.org/latest/instance-administration/plugin-version-matrix/

Is the latest version (2.14.4) compatible with SQ 8.9 LTS?

Thank you.

**Comment by gquerret** [comment]
I'll update the version matrix. 
FYI, 8.9 is the recommended version as of today.
