### ISSUE TITLE
Add DLC when sonar.oe.propath.dlc=true 

### ISSUE THREAD

**Issue by cverbiest** [Riverside-Software/sonar-openedge#887]
I found `sonar.oe.propath.dlc=true` does not add the $DLC directory itself to the propath.

We have a large number of sources that have references to dlc includes using { src/adm/... }.

This is because the default propath used by OpenEdge does include $DLC but not $DLC/src.

Can sonar.oe.propath.dlc be enhanced to also add $DLC itself to the propath ?

Alternative solution : variable expansion in sonar.oe.propath 
`sonar.oe.propath = dir1,dir2,${sonar.oe.dlc}`

**Comment by gquerret** [comment]
That's already the case, here is the [code](https://github.com/Riverside-Software/sonar-openedge/blob/develop/openedge-plugin/src/main/java/org/sonar/plugins/openedge/foundation/OpenEdgeSettings.java#L192).

Are you sure the `sonar.oe.dlc` variable is also correctly set ?

**Comment by cverbiest** [comment]
I found I have one project with the issue and one without. 
Scan is done on a windows jenkins agent

project without this issue has `sonar.oe.dlc=c:/progress/oe122`
project with issue has `sonar.oe.dlc=c:\progress\oe122`

I guess that caused it, will close
