### ISSUE TITLE
Parser error when table name and field name is separated by a space

### ISSUE THREAD

**Issue by gquerret** [Riverside-Software/sonar-openedge#897]
This ABL code raises an error in Proparse (but not in the ABL compiler):
```
DEFINE TEMP-TABLE tt
  FIELD fld1 AS CHAR.
FIND tt WHERE tt .fld1 = "1".
```
Similar syntax with a DB table works in both Proparse and the compiler. 
```
FIND customer WHERE customer .name = "1".
```

**Comment by jurjendijkstra** [comment]
Ok but why would anyone want to use a space there? It raises a parse error in my head too.

**Comment by gquerret** [comment]
I'd say nobody does that on purpose ; but when used in combination with preprocessor, it can become necessary. Unfortunately, they even extended this behavior to class names, making this kind of abomination possible:

```abl
MESSAGE 
Progress  /*FooBar */ /* Test */ .Security.PAMStatus 
//Test
//Test2
:AccessDenied.
```

**Comment by PeterJudge-PSC** [comment]
Can you add a rule that reports on such constructs?

**Comment by gquerret** [comment]
Issue is fixed in the parser.

> Can you add a rule that reports on such constructs?

Yes, will do. Note to self: RECORD_NODE, FIELD_REF and TYPE_NAME nodes with more than 1 child.

**Comment by gquerret** [comment]
Added in develop
