### ISSUE TITLE
Proparse issues since 2.14.1

### ISSUE THREAD

**Issue by gquerret** [Riverside-Software/sonar-openedge#902]
On behalf of RITS

Issues found in the 2.14.1 prerelease:
```
NO-RETURN-VALUE mh-g-explorer:QUIT(). // Where mh-g-explorer is a com-handle variable
```
leads to `mismatched input 'NO-RETURN-VALUE' expecting {<EOF>, END}`

And multiple issues with `SUPER` keyword, as reported in #899.

**Comment by gquerret** [comment]
In case anybody is reading comments, how many of you are using this keyword `NO-RETURN-VALUE`?

Grammar for this keyword:
```
[ { field | COMProperty } = | NO-RETURN-VALUE ]
Com-Handle-Var :COMMethod [ NO-ERROR ]
```

> NO-RETURN-VALUE indicates that you are invoking the COM object method directly, as a statement, without returning its value

Seems it could be skipped as well.

**Comment by kenherring** [comment]
> In case anybody is reading comments, how many of you are using this keyword `NO-RETURN-VALUE`?

Looks like the only references we have to the `NO-RETURN-VALUE` keyword come from `adm/treeview.p`, which is a progress supplied file and not something we wrote. 🤷‍♂️

**Comment by movedoa** [comment]
> > In case anybody is reading comments, how many of you are using this keyword `NO-RETURN-VALUE`?
> 
> Looks like the only references we have to the `NO-RETURN-VALUE` keyword come from `adm/treeview.p`, which is a progress supplied file and not something we wrote. 🤷‍♂️
> 
> 

Same here, didn't even know this existed :D

**Comment by PeterJudge-PSC** [comment]
New to me too.

I'm glad we went for `VOID` for classes ... that's a little verbose

**Comment by cverbiest** [comment]
did not know it existed. I searched our codebase and found it in just one source.

**Comment by gquerret** [comment]
> I'm glad we went for VOID for classes ... that's a little verbose

`method public no-return-value execute():` 😄

**Comment by gquerret** [comment]
> I searched our codebase and found it in just one source.

Same syntax ? i.e. statement `no-return-value comHdl:method().` ?

**Comment by gquerret** [comment]
> Looks like the only references we have to the NO-RETURN-VALUE keyword come from adm/treeview.p

Thanks, found it in `adm2/treeview.p`. There's also a reference in `dynamics/af/sup/afspelchkp.p`.

**Comment by gquerret** [comment]
Offline report mentioned a couple dozen files impacted. Support for this keyword has been backported (with a better implementation than before).
