### ISSUE TITLE
Method output parameter reported as unused

### ISSUE THREAD

**Issue by mikefechner** [Riverside-Software/sonar-openedge#91]
![2016-11-05_23h15_40](https://cloud.githubusercontent.com/assets/13220627/20033937/d51b3438-a3ad-11e6-88ee-a71b1029432f.png)

**Comment by gquerret** [comment]
Should have been fixed (see issue #25), but will see the test case again.

**Comment by movedoa** [comment]
I am still having this issue with V1.9.5

**Comment by gquerret** [comment]
Reproduced. Silly me...

**Comment by gquerret** [comment]
Fixed in master (riverside-rules)
