### ISSUE TITLE
JsonConstruct:Write(OUTPUT LONCHAR) should not be used

### ISSUE THREAD

**Issue by movedoa** [Riverside-Software/sonar-openedge#910]
When using the JsonConstruct:Write method (JsonArray/JsonObject) with a LONGCHAR variable, you have to use it with INPUT-OUTPUT since the OUTPUT version is defined with CHARACTER and produces errors if the output is longer than 32k chars.

If you don't specify a parameter mode is also works, but you shouldn't do that (#528).

This should be a general rule, not just for these types since one could produce the same with custom methods.

```abl
DEFINE VARIABLE loJsonObject AS Progress.Json.ObjectModel.JsonObject NO-UNDO.
DEFINE VARIABLE liCount AS INTEGER NO-UNDO.
DEFINE VARIABLE llcOutoput AS LONGCHAR NO-UNDO.

loJsonObject = NEW Progress.Json.ObjectModel.JsonObject().

DO liCount = 1 TO 1000:
   loJsonObject:Add(STRING(liCount), "01234567890123456789012345678901234567890123456789":U).   
END.

// Error -> Attempt to exceed maximum size of a CHARACTER variable. (9324)
// loJsonObject:Write(OUTPUT llcOutoput).

// Works
loJsonObject:Write(INPUT-OUTPUT llcOutoput).

// Also works
loJsonObject:Write(llcOutoput).

```

**Comment by akompanas** [comment]
I recently got burnt by this exact issue. Is there away to get more traction to this?

**Comment by gquerret** [comment]
> I recently got burnt by this exact issue. Is there a way to get more traction to this?

Yes, could be done

**Comment by gquerret** [comment]
Merged in develop branch, will be available in next release.

**Comment by akompanas** [comment]
Thanks! That was quick.

Is the code available for it? I wanted to test my own skills but could only find a small subset of rules that are actually available in our SQ.

**Comment by gquerret** [comment]
No, the code of the commercial set of rules is not available. The code of the plugin itself (with full 4GL parser) is available in this repo.
