### ISSUE TITLE
Wrong error message for "Invalid number of parameters in SUBSTITUTE statement" rule with no parameters

### ISSUE THREAD

**Issue by movedoa** [Riverside-Software/sonar-openedge#914]
2.14.3

This statement
`SUBSTITUTE("Foo.":U).`
produces the following error:
`-1 parameter(s) expected by SUBSTITUTE string, but 0 provided`

Should be a different message, like "Unnecessary SUBSTITUTE function".

The message is correct for 1 or more missing parameters.

**Comment by gquerret** [comment]
Looks like I missed something while merging branches, this change should already be in 2.14.3

**Comment by gquerret** [comment]
Fixed in develop
