### ISSUE TITLE
False positive on variable hiding

### ISSUE THREAD

**Issue by mikefechner** [Riverside-Software/sonar-openedge#92]
This cannot be right:

![2016-11-06_08h13_57](https://cloud.githubusercontent.com/assets/13220627/20035954/0b7bd30c-a3f9-11e6-97fe-3e3bfb36afcc.png)

and I believe the engine is getting confused by the e as an event parameter in the same class:

![2016-11-06_08h15_09](https://cloud.githubusercontent.com/assets/13220627/20035957/27263502-a3f9-11e6-987a-977531bcedc9.png)

**Comment by gquerret** [comment]
Not enough information to reproduce, I'll add some more information in the description of the issue so that we know which variable is being hidden (with the line number of the declaration of the hidden variable).

**Comment by gquerret** [comment]
You can try this version if you have time : https://ci.rssw.eu/job/sonar-openedge-rules/job/PR-15/
Shouldn't break anything.

**Comment by gquerret** [comment]
Parameters from event signature are (incorreclty) sent to the class-wide scope.
