### ISSUE TITLE
Resources are not available for download 

### ISSUE THREAD

**Issue by JohnnyShen88** [Riverside-Software/sonar-openedge#921]
Cannot open installation guide
Short - https://docs.sonarqube.org/display/SONAR/Get+Started+in+Two+Minutes
Long - https://docs.sonarqube.org/display/SONAR/Installing+the+Server

**Comment by JohnnyShen88** [comment]
Scanner is also not available for download: https://docs.sonarqube.org/display/SCAN/Analyzing+with+SonarQube+Scanner

**Comment by gquerret** [comment]
Dead links have been updated!
