### ISSUE TITLE
Question/Enhancement request : differentiate between rules checked in PDSOE and scan during build

### ISSUE THREAD

**Issue by cverbiest** [Riverside-Software/sonar-openedge#922]
Is it possible to ignore certain rules during scan that is sent to SonarQube server but keep them active in PDSOE Sonarlint ?

Use case : 
In our coding standard we use unabbreviated lowercase keywords.

I'd like to keep checks for that active in PDSOE when a developer is currently editing a source.
When scanning our entire codebase, I'm not interested in violations of this.

Can this be achieved ?

**Comment by jurjendijkstra** [comment]
You can create a second project in Sonarqube, with a stricter ruleset. Sonarlint can link to that project, and you don't need to send nightly builds to that project.

**Comment by cverbiest** [comment]
@jurjendijkstra Thank you for the tip. 

Wouldn't that break the link with the build analyses in PDSOE ?
I must admit I don't see much of the build analyses results in PDSOE

**Comment by gquerret** [comment]
When the PDS project is bound to the SonarQube project, you have to use the same quality profile, so it's not possible to active a different set of active rules.
The behavior you're looking for will be available in the VSCode plugin (which is not available yet).
