### ISSUE TITLE
Abbreviated keywords doesn't recognize SESSION:TEMP-DIR and other attributes

### ISSUE THREAD

**Issue by movedoa** [Riverside-Software/sonar-openedge#924]
I guess it doesn't check any attributes of the build in handles.
Would be a nice addition to the rule.

**Comment by gquerret** [comment]
This change would require [this branch](https://github.com/Riverside-Software/sonar-openedge/tree/feature/KeywordRefactor) to be merged (in order to recognize all keywords), but there are some minor regressions associated to the change.
Not first priority, but can be done

**Comment by movedoa** [comment]
Would still be very useful. 
We have a few of these attributes by now that should not be used because we have our own custom property.

**Comment by gquerret** [comment]
The aforementioned branch was merged in 2.18. This issue was not updated, but as a side effect this kind of pattern should now be detected. Example in VSCode:

![image](https://user-images.githubusercontent.com/6498723/205050156-25065a09-63c2-4a7f-a232-b9c3f3d9fb86.png)
