### ISSUE TITLE
False positive on RETURN ERROR with no expression detection.

### ISSUE THREAD

**Issue by mikefechner** [Riverside-Software/sonar-openedge#93]
![2016-11-06_10h42_13](https://cloud.githubusercontent.com/assets/13220627/20036644/c627ddd6-a40d-11e6-8fbb-da1066cf5cf1.png)

**Comment by gquerret** [comment]
Reproduced, test case added

**Comment by gquerret** [comment]
Fixed in master (riverside-rules)
