### ISSUE TITLE
FP with executables statements order rule

### ISSUE THREAD

**Issue by PeterJudge-PSC** [Riverside-Software/sonar-openedge#931]
The code below is fails the statement order rule at the "@Before" and "@Setup" markers.

The markers in PDSOE are on the annotations.

Description	Resource	Rule name	Rule key
Don't mix PROCEDURE declaration and executable statements [+2 locations]	test_proc.p	Procedure or function declaration found between executable statements	rssw-oe-main:eu.rssw.antlr.proparse.checks.StatementOrder

OpenEdge plugin version: 2.14.4-645d363d

````
define variable hProc as handle no-undo.
define variable cStatus as character no-undo.

cStatus = 'PROCEDURE-RAN'.

@Before.
procedure before-all:
    cStatus = 'BEFORE-ALL-RAN'.
end procedure.

@Setup.
procedure before-each:
    hProc = this-procedure.
end procedure.

````

**Comment by gquerret** [comment]
Reproduced

**Comment by gquerret** [comment]
Fixed in develop
