### ISSUE TITLE
Sonar-openedge is not recognizing dead code

### ISSUE THREAD

**Issue by ivanbrizida** [Riverside-Software/sonar-openedge#933]
I´m running the command below

```
@echo off
cd C:\temp\DSV\build_id_63645\sonar
"C:\Program Files\Java\jdk-11.0.12\bin\java.exe" -classpath C:\BuildAgent\tools\sonar-qube-scanner.4.2.0.1873-scanner\lib\sonar-scanner-cli-4.2.0.1873.jar org.sonarsource.scanner.cli.Main "-Dproject.home=." "-Dsonar.host.url=http://sonar.capemisa.com.br:9000" "-Dsonar.jdbc.url=sqlserver://cap-dev-common-us01-sql.producao.capemi;databaseName=SNRCapemisa_HML" "-Dsonar.jdbc.username=UH_SONAR_BD" "-Dsonar.jdbc.password=****" "-Dsonar.projectKey=Progress_Fbadtcto" "-Dsonar.projectName=Progress_Fbadtcto" "-Dsonar.projectVersion=3.0..27" "-Dsonar.password=*****" "-Dsonar.login=admin" "-Dsonar.oe.propath=c:\temp\DSV\build_id_63645\sonar" "-Dsonar.sources=c:\temp\DSV\build_id_63645\sonar" "-Dsonar.oe.databases=\\rjopvauto01\TC-Control\conexoes\bd\DSV\cap.df,\\rjopvauto01\TC-Control\conexoes\bd\DSV\prv.df,\\rjopvauto01\TC-Control\conexoes\bd\DSV\DBcon.df" "-Dscanner.home=C:\BuildAgent\tools\sonar-qube-scanner.4.2.0.1873-scanner" > c:\temp\DSV\build_id_63645\sonar.log
pause
```

The sonar.sources directory contains the files below

```
 Volume in drive C has no label.
 Volume Serial Number is BCEE-9D08

 Directory of C:\temp\DSV\build_id_63645\sonar

01/17/2022  11:09 AM    <DIR>          .
01/17/2022  11:09 AM    <DIR>          ..
01/12/2022  05:49 PM    <DIR>          .sonarlint
01/12/2022  09:47 PM               956 fbbal232.i
01/12/2022  09:47 PM               848 fbbcs232.i
01/12/2022  09:47 PM               956 fbbin232.i
01/12/2022  09:47 PM             1,715 fbdefine.i
01/12/2022  09:47 PM             2,438 fberro.i
01/17/2022  09:40 AM            11,666 fbnal232.p
01/12/2022  09:47 PM             2,787 fbncs232.p
01/12/2022  09:47 PM            11,152 fbnin232.p
01/17/2022  11:09 AM                 0 ivan.txt
               9 File(s)         32,518 bytes
               3 Dir(s)  63,352,942,592 bytes free
```

The program with dead code is:

[fbnal232.p.txt](https://github.com/Riverside-Software/sonar-openedge/files/7882599/fbnal232.p.txt)

The log is:

[sonar.log.txt](https://github.com/Riverside-Software/sonar-openedge/files/7882602/sonar.log.txt)
			   
Sonar is scanning these files fine because I put some errors in it, and sonar reported them (I deleted the erros afterwards). But I have put also in the fbnal232.p file the exact example of the dead code active rule and it does not appear in the project report. The project Oreview page shows zero bugs. 

![overview](https://user-images.githubusercontent.com/97895563/149791130-260fdfc6-6318-4ec5-a833-4bc300173d66.png)

And the project quality profiles page shows 18 active rules. 

![quality_profiles](https://user-images.githubusercontent.com/97895563/149791224-8e90212f-f801-4393-9e9e-3a63d686f0b2.png)

The third rule is the dead code rule. 

![rules](https://user-images.githubusercontent.com/97895563/149791312-df955708-5e15-48af-8bc7-b1da08413fff.png)

Then I suppose the rule should be being applyed to the code, but it is not. How can I make it work ? Thanks for any help.

**Comment by gquerret** [comment]
The "Dead code" rule is based on ABL compiler warnings. If you want the compiler warnings to be imported in SonarQube, then you have to use [PCT](https://github.com/Riverside-Software/pct) to compile your code. PCT will generate warning output files in the build directory, which will be read by Sonar.
The output looks like this : https://sonar.riverside-software.fr/project/issues?id=RSSW%3ATestProject&issues=AXenPw45y1SdDFXsH2_t&open=AXenPw45y1SdDFXsH2_t

**Comment by ivanbrizida** [comment]
I see. I´ll try it.

Thanks!!
