### ISSUE TITLE
Unused variable field_ref issue

### ISSUE THREAD

**Issue by mikefechner** [Riverside-Software/sonar-openedge#94]
Got a lot of those messages appearing at the beginning of classes. Looks like an issue parsing the xref: 
Unused variable Field_ref 

![2016-11-06_18h09_38](https://cloud.githubusercontent.com/assets/13220627/20039871/7f3c4440-a44c-11e6-8181-6cee4cc8263e.png)

**Comment by movedoa** [comment]
Same error here (V1.9.5)

**Comment by gquerret** [comment]
Reproduced with this simple procedure:
```
CATCH err AS Progress.Lang.Error :
  DISPLAY err:toString().
END CATCH.
```

**Comment by gquerret** [comment]
See TP01Support#field(...), variable lookup doesn't work correctly in this case, so numReads/numWrites is not incremented.

**Comment by gquerret** [comment]
Fixed in master

**Comment by mikefechner** [comment]
Seems to work!
