### ISSUE TITLE
Identify the database is not an error

### ISSUE THREAD

**Issue by ivanbrizida** [Riverside-Software/sonar-openedge#940]
**Describe the bug**

The syntax error is not correct, because the compiler accepts it, but sonar does not.

![sonarError](https://user-images.githubusercontent.com/97895563/154481650-009e0f10-7b0d-4a98-ac7f-0f834b7ea4fa.jpg)

**Expected behavior**

This sintax is exactly what is REQUIRED by the compíler because there are two different databases. Is there any property to switch off this behavior ?

**Environment**

[Build_e_Deploy_Progress_DSV_TQS_e_MNT_Build_e_Deploy_Progress_com_SONAR_DSV_TQS_e_MNT_3.0..47.log.txt](https://github.com/Riverside-Software/pct/files/8088609/Build_e_Deploy_Progress_DSV_TQS_e_MNT_Build_e_Deploy_Progress_com_SONAR_DSV_TQS_e_MNT_3.0.47.log.txt)

**Comment by gquerret** [comment]
Use the `sonar.oe.databases` and `sonar.oe.aliases` properties (see https://github.com/Riverside-Software/sonar-openedge/wiki/Property-list ). You're just missing the `prv` logical name of the DB

**Comment by ivanbrizida** [comment]
I included the line bellow:

`<property name="sonar.oe.aliases" value="cap,con,prv,spc" />`

and this too:

`<jvmarg value="-Dsonar.oe.aliases=cap,con,prv,spc"/>`

**but they did not work**

the ant build xml goes bellow:

[sonar.xml.txt](https://github.com/Riverside-Software/sonar-openedge/files/8097387/sonar.xml.txt)

**Comment by gquerret** [comment]
The syntax of `sonar.oe.aliases` is `dbname1,alias1,alias2,alias3;dbname2,alias4,alias5` --> semicolon separated list of entries, each entry being a comma separated list of the aliases following the db logical name.
The `prv` alias has to be defined for the database holding the cdsthab table.

**Comment by ivanbrizida** [comment]
It worked, thanks, but I had to do one more thing: the name of the database is NOT the name of the database, but the name of the .df file, so the line became:

`<jvmarg value="-Dsonar.oe.aliases=cap4,cap;con4,con;prv4,prv;spc4,spc"/>`

Now there are no more bugs or code smells as it should.

**Merci beaucoup. :))**
