### ISSUE TITLE
The parser says that this valid syntax cannot be parsed.

### ISSUE THREAD

**Issue by ivanbrizida** [Riverside-Software/sonar-openedge#942]
The parser says that this valid syntax cannot be parsed.

![sonarError](https://user-images.githubusercontent.com/97895563/155007593-a41cae37-7bd0-47d1-8369-08bd17869c1f.jpg)

And that with a few changes, it can be parsed. On the other hand, my progress team says that this syntax was suggest by a consultant because it has more performance than the normal bellow:

`for each .. : nNumhabben = nNumhabben + 1 . End. `

What would be the most performatic code alternative that the parser accepts ?

**Comment by gquerret** [comment]
Issue transferred to sonar-openedge, please open issues in the right repository.

The syntax is accepted by the compiler, but not by Proparse. You can use preprocessor expressions to skip parts of the source (see https://github.com/Riverside-Software/sonar-openedge/releases/tag/V2.10.0).

**Comment by stefandrissen** [comment]
Another reason to avoid embedded SQL select statements is that they were [deprecated](https://knowledgebase.progress.com/articles/Article/000034659) with the release of Progress OpenEdge 10.0A in 2003!

See also the De-supported Features and Functionality List in the [product availability documentation for 11.7](https://community-archive.progress.com/documents/OpenEdge/OpenEdge_11x_availability_guide_2020_03_31.pdf):

> SQL in 4GL | OpenEdge 10.0A | SQL statements in 4GL code require the Progress V9 SQL-89 product. The SQL-89 interface is obsolete.

**Comment by ivanbrizida** [comment]
Now I will have all that changed. Thanks !
