### ISSUE TITLE
problem with jar on maven ?

### ISSUE THREAD

**Issue by clement-brodu** [Riverside-Software/sonar-openedge#944]
Hello, 

Is there a problem with the jars you uploaded on maven ?
https://mvnrepository.com/artifact/eu.rssw.sonar.openedge/sonar-openedge-plugin/2.14.7

![image](https://user-images.githubusercontent.com/37274615/155154926-b604db74-e2ca-4882-b968-af2ae37e23d4.png)

I can't use the dependency in my sonar rule project 😢 

Thanks,

**Comment by gquerret** [comment]
Looks like there's a problem, don't even know why this didn't fail !
You can still use the previous version, there are no API signature changes in this version.

**Comment by gquerret** [comment]
2.14.9 is now available, with the right dependencies.
