### ISSUE TITLE
configuration code coverage

### ISSUE THREAD

**Issue by MedAmineTorjmen** [Riverside-Software/sonar-openedge#951]
Hello, can you told me how can i make the configuration for the code coverage please.
Thank you

**Comment by gquerret** [comment]
The only poperty you have to set during the analysis is sonar.oe.coverage.profiler.dirs (besides the usual sonar.sources, sonar.oe.binaries, ...). Full list is here: https://github.com/Riverside-Software/sonar-openedge/wiki/Property-list#general
Note that you have to execute the Unit tests with profiler enabled (see PCT project).

You can use this project as an example : https://github.com/Riverside-Software/sonaroe-test-project
You can execute "ant build" followed by sonar-scanner, and that will analyze the project locally. It contains unit tests and code coverage, so it could be helpful to test that.

The most important thing in code coverage is to have the right mapping between the files names in the .profiler files and what sonar-scanner sees locally, especially regarding to propath.
Verbose output will show you the entries found in the profiler output and if that can be mapped to a local file.

**Comment by MedAmineTorjmen** [comment]
yes I understood this step, but I still have a blurry point about how to launch the PCT/ANT to generate the .profiler files.
can you help me with this step please ? or if you have an example to be followed 

Thanks.

**Comment by gquerret** [comment]
You have to include the <Profiler> node in your ABLUnit (or PCTRun) task ; see this example : https://github.com/Riverside-Software/sonaroe-test-project/blob/master/build.xml#L64 . That will generate the profiler output in the `profiler` directory.

You can use the sonaroe-test-project as an example ; the Ant targets can be executed, and the Sonar analysis result is pushed to your local SonarQube instance.
