### ISSUE TITLE
Use tableusage to detect usage of a particular buffer

### ISSUE THREAD

**Issue by cverbiest** [Riverside-Software/sonar-openedge#958]
Is it possible to enhance the tableusage rule to detect usage of a particular buffer ?

### Use case 
In our legacy code we have a particular shared buffer ALT-XUS on a table XUSER.

We'd like to flag all code that accesses this buffer. 
The definition of the buffer is in an include file that is used by all legacy code, the definition in itself should not trigger the rule or it should be possible to add a prolint-nowarn directive.

* Is this feasible as an enhancement of this rule
* Could this be achieved using one of the other rules ?

**Comment by gquerret** [comment]
It's technically feasible in this rule to see the buffer name as well as the initial table name. I'll have a look if it's possible to configure it in an easy way; otherwise, that would have to go in a custom rule.

**Comment by gquerret** [comment]
Now available in develop
