### ISSUE TITLE
Code converage shows END CASE statement as not covered

### ISSUE THREAD

**Issue by movedoa** [Riverside-Software/sonar-openedge#964]
![grafik](https://user-images.githubusercontent.com/13309951/165080402-af1e3847-0fe4-4e02-acc4-e766b3094daf.png)

Every WHEN in this case is covered, only this line is shown as not covered.

**Comment by movedoa** [comment]
Just saw that this is a progress issue.

**Comment by stefandrissen** [comment]
Just a small heads up that this ``case`` (pun intended) has been fixed in 12.8.4 - see [OCTA-9112](https://docs.progress.com/bundle/openedge-product-notes/page/Issues-fixed-in-OpenEdge-12.8.4.html).
