### ISSUE TITLE
Silent install 

### ISSUE THREAD

**Issue by KevinIlPazzo** [Riverside-Software/sonar-openedge#965]
Is there a possibility to install sonarlint silently by copying files to eclipse/plugins?

**Comment by gquerret** [comment]
I don't think there is a way to install any Eclipse plugin by copying files, you have to use the "Install new software" menu entry.

**Comment by cverbiest** [comment]
I have not tried it but maybe this helps https://stackoverflow.com/questions/11633529/installing-plugin-into-eclipse-using-command-line
