### ISSUE TITLE
Differences in scanner results and sonarlint on the fly

### ISSUE THREAD

**Issue by cverbiest** [Riverside-Software/sonar-openedge#966]
The issues below are only shown in the scanner results, not on-the-fly

![image](https://user-images.githubusercontent.com/1312691/167083276-940737f0-25b8-469a-abdc-ebaf0700c2e9.png)

I found it is related to xref info and that this may not be present in the on-the-fly analysis.

I'm looking for a list of 
* differences between scanner & on-the-fly results
* rules depending on xref or other pct output that is not available in PDSOE

I activated XREF on the project and now these issues appear in Sonarlint as well

**Comment by gquerret** [comment]
I'll try to gather such a list.

**Comment by gquerret** [comment]
All rules with a `xref` tag need XREF information. `FindFirst` was missing this tag, now fixed in the develop branch.
