### ISSUE TITLE
sonar.oe.filter.invalidxref should filter CHR 3

### ISSUE THREAD

**Issue by movedoa** [Riverside-Software/sonar-openedge#97]
I don't know if there is any particular reason for not filtering chr 3? (afaik only 1 2 and 4 get filtered)
Valid OE Code can produce chr 3 in the xref xml
For example just a string with "~003"

**Comment by gquerret** [comment]
There's no good reason for not filtering CHR(3), apart from the codebase I had to deal with, and which didn't include this character. A range of characters to be skipped will be implemented in the next version, something like:
```
sonar.oe.filter.invalidxref.bytes=1-4,6,8
```
In order to skip CHR(1) to CHR(4), then CHR(6) and CHR(8)

**Comment by gquerret** [comment]
Fixed in master
