### ISSUE TITLE
class org.prorefactor.treeparser.symbols.TableBuffer cannot be cast to class org.prorefactor.treeparser.Primative

### ISSUE THREAD

**Issue by stefandrissen** [Riverside-Software/sonar-openedge#970]
sonar-openedge-plugin-2.14.8
````
class org.prorefactor.treeparser.symbols.TableBuffer cannot be cast to class org.prorefactor.treeparser.Primative (org.prorefactor.treeparser.symbols.TableBuffer and org.prorefactor.treeparser.Primative are in unnamed module of loader org.sonar.classloader.ClassRealm @608707d)
````
If I strip the .p that is throwing this error, it is caused by a temp-table buffer definition in an internal procedure:
````
define buffer bubrowse for s_ttbrowses.
````
The same definition is used in three earlier internal procedures and also in subsequent ones. If I strip out all actual code from this internal procedure the presence of the define buffer results in the failure:

![image](https://user-images.githubusercontent.com/5297464/172316482-1b9a1947-5515-4e89-abd3-97ba7970d8ea.png)

When I comment out the define, normal issue scanning resumes:

![image](https://user-images.githubusercontent.com/5297464/172316660-fbeb982a-3baf-474c-99c7-27fc16f48a72.png)

**Comment by stefandrissen** [comment]
Just found the culprit, it's a subsequent function that contains:
````
message 'foo' view-as alert-box question buttons yes-no update lfoo as logical.
````
When the logical variable is defined before the message, then the problem goes away.

**Comment by gquerret** [comment]
Issues #953 and #954 are related (though they don't seem to be duplicates). Both are included in 2.15.0
The message statement is enough to trigger the error ?

**Comment by stefandrissen** [comment]
It's the ``as logical`` in the message that triggers the error.

**Comment by gquerret** [comment]
Additional checks added when converting symbols to Primative. Included in the develop branch
