### ISSUE TITLE
Cannot flag unused temp tables

### ISSUE THREAD

**Issue by hpmBravura** [Riverside-Software/sonar-openedge#971]

**Comment by gquerret** [comment]
Could you provide more details ?

**Comment by hpmBravura** [comment]
Sure Gilles, 
Happens on OpenEdge Release: 11.7.13 and SonarLint 6.2.2204 plug in.
The tt is defined inside a .p file, see example below.
![tt-noflag](https://user-images.githubusercontent.com/75454805/174008710-ee22b164-a242-4d62-a327-a5e5d58a85f1.png)

**Comment by gquerret** [comment]
Default buffer of temp-tables are skipped in this rule. Main reason is that too many false positives were flagged, coming from TT defined in include files. It may be better to make a difference between TT defined in .i vs .p

**Comment by gquerret** [comment]
In SonarLint, yes. Issues found in include files are never reported in SonarLint. They can be seen in the Web UI after having executed the full analysis.

**Comment by gquerret** [comment]
Added in develop. A boolean parameter controls this behavior.
