### ISSUE TITLE
No viable alternative at input 'CONSTRUCTOR port' in port.cls

### ISSUE THREAD

**Issue by stefandrissen** [Riverside-Software/sonar-openedge#973]
![image](https://user-images.githubusercontent.com/5297464/174949661-bc0c6c93-0452-4856-8159-6a55eb761612.png)

The actual problem is a ``form header`` defined above the constructor:

````
class port:

   def var cc as char.

   form header cc.

   constructor port():
      // do something
   end constructor.

end class.
````

**Comment by gquerret** [comment]
Which version of the OE plugin do you use ?

I've done a quick test with the dev version of Proparse 2.16, and I'm getting:
`Mismatched input 'form' expecting { PERIOD, ANNOTATION, CONSTRUCTOR, DEFINE, DESTRUCTOR, END, FUNCTION, METHOD, ON, PROCEDURE, VAR }`

The [documentation](https://docs.progress.com/bundle/openedge-oo-abl-develop-applications-122/page/Define-classes_2.html) does not mention that the `FORM` statement is allowed in the main block of a class, so Proparse rejects the statement. I'll update that.

**Comment by stefandrissen** [comment]
Ah, I'm using 2.14.8 - will update. later on.

**Comment by gquerret** [comment]
Fixed in develop
