### ISSUE TITLE
Sonar lint online-analysis unstable in DevStudio? Works only sometimes.

### ISSUE THREAD

**Issue by Tranborg** [Riverside-Software/sonar-openedge#983]
Hi! Really hard to trace down whats wrong here. Se pic. Text in red. 

Perhaps it is the db connection missing. Same properties works fine for the batch analysis. Somtimes it works fine, but usually not.

![image](https://user-images.githubusercontent.com/42405751/182151071-e935d1ac-1d68-4306-8fc9-15cf930275e9.png)

Any help is preciated.

```
--------------------------------------------
sonar-project.properties
-------------------------------------------
sonar.projectName=Twin360BackEnd
#sonar.projectVersion=1.0
sonar.projectDescription=TWIN360 BackEnd code. Mostly with Progress 4GL
# Comma-separated list of directories - Dump contains .df files, and src/openedge contains source code
sonar.sources=df,src
# Comma-separated list of patterns to be excluded
sonar.exclusions=
sonar.sourceEncoding=iso8859-1
# Directory where r-code can be found
sonar.oe.binaries=tmp/build
# Comma-separated list of PL or directories
sonar.oe.propath=src
# OpenEdge installation path (see next property)
sonar.oe.dlc=D:/TWIN360/TWINSoftware/DLC
# Append $DLC/gui, $DLC/tty and $DLC/src to the propath
sonar.oe.propath.dlc=true
# Comma-separated list of full DF files
sonar.oe.databases=df/twin360.df
# Semi colon separated list of entries, each entry is a comma-separated list of aliases (first entry is the db name)
sonar.oe.aliases=twin360,twin360
# No Copy-Paste Detection on DF files
sonar.cpd.exclusions=df/**
# Set to true to generate token listing in .tokens subdirectory
sonar.oe.cpd.debug=false
# Set to true to generate AST for each file in .proparse subdirectory
sonar.oe.proparse.debug=false
# Default extensions are .p, .w, .i and .cls. Use this option if you have additional extensions to analyze
# sonar.oe.file.suffixes=p,w,t
# Comma-separated list of directories where *.out files will be parsed for code coverage
#sonar.oe.coverage.profiler.dirs=tmp/profiler
# Analytics data (number of OE files analyzed + timings) sent by default to Riverside Software. Set property to false to disable data collection
sonar.oe.analytics=true
```

**Comment by Tranborg** [comment]
GET 200 http://twsonar01:9000/api/developers/search_events?projects=twsonar01new&from=2022-08-01T08%3A39%3A12%2B0200 | response time=128ms
Trigger: MANUAL
Clear markers on 0 excluded files
SonarLint processing file /Twin360BackEnd/src/ReportCreation/jx_AccBatch.p...
Connected mode (using configuration of 'Twin360BackEnd' in server 'twsonar01new')
Starting analysis with configuration:
[
  projectKey: Twin360BackEnd
  baseDir: D:\Workspace\tranborgl\TWIN360Agile\Branches\Development\MainFuture\Twin360BackEnd
  extraProperties: {sonar.oe.propath=src, sonar.sources=src}
  inputFiles: [
    file:/D:/Workspace/tranborgl/TWIN360Agile/Branches/Development/MainFuture/Twin360BackEnd/src/ReportCreation/jx_AccBatch.p (UTF-8)
  ]
]

Available languages:
  * Scala => "scala"
  * Python => "py"
  * OpenEdge => "oe"
  * OpenEdgeDB => "oedb"
  * HTML => "web"
  * JSP => "jsp"
  * XML => "xml"
  * Kotlin => "kotlin"
  * PHP => "php"
  * JavaScript => "js"
  * TypeScript => "ts"
  * Ruby => "ruby"
Start analysis
Declared extensions of language Scala were converted to scala: **/*.scala
Declared extensions of language Python were converted to py: **/*.py
Declared extensions of language OpenEdge were converted to oe: **/*.p,**/*.w,**/*.i,**/*.cls
Declared extensions of language OpenEdgeDB were converted to oedb: **/*.df
Declared extensions of language HTML were converted to web: **/*.html,**/*.xhtml,**/*.cshtml,**/*.vbhtml,**/*.aspx,**/*.ascx,**/*.rhtml,**/*.erb,**/*.shtm,**/*.shtml
Declared extensions of language JSP were converted to jsp: **/*.jsp,**/*.jspf,**/*.jspx
Declared extensions of language XML were converted to xml: **/*.xml,**/*.xsd,**/*.xsl
Declared extensions of language Kotlin were converted to kotlin: **/*.kt
Declared extensions of language PHP were converted to php: **/*.php,**/*.php3,**/*.php4,**/*.php5,**/*.phtml,**/*.inc
Declared extensions of language JavaScript were converted to js: **/*.js,**/*.jsx,**/*.mjs,**/*.vue
Declared extensions of language TypeScript were converted to ts: **/*.ts,**/*.tsx
Declared extensions of language Ruby were converted to ruby: **/*.rb
Index files
Language of file 'file:/D:/Workspace/tranborgl/TWIN360Agile/Branches/Development/MainFuture/Twin360BackEnd/src/ReportCreation/jx_AccBatch.p' is detected to be 'oe'
1 file indexed
Quality profiles:
  * js: 'Sonar way' (129 rules)
  * jsp: 'Sonar way' (0 rules)
  * kotlin: 'Sonar way' (29 rules)
  * oe: 'Sonar way (Twin360)' (86 rules)
  * oedb: 'Sonar way (extended)' (4 rules)
  * php: 'Sonar way' (112 rules)
  * py: 'Sonar way' (115 rules)
  * ruby: 'Sonar way' (28 rules)
  * scala: 'Sonar way' (28 rules)
  * ts: 'Sonar way' (119 rules)
  * web: 'Sonar way' (27 rules)
  * xml: 'Sonar way' (6 rules)
Registering CheckRegistrar class org.sonar.plugins.openedge.foundation.BasicChecksRegistration
Registering CheckRegistrar class org.sonar.plugins.openedge.RiversideChecksRegistration
Found COMMERCIAL license - <secret>
Found COMMERCIAL license - <secret>
Found COMMERCIAL license - <secret>
'Scala Sensor' skipped because there is no related file in current project
'Python Sensor' skipped because there is no related file in current project
Execute Sensor: OpenEdgeSensor
'OpenEdgeDBSensor' skipped because there is no related file in current project
Execute Sensor: OpenEdgeWarningsSensor
Execute Sensor: OpenEdgeProparseSensor
OpenEdge plugin version: 2.14.8-9dff4222
Loading OpenEdge settings for server ID <secret>
Adding source directory 'src' ...
  ... resolved to 'D:\Workspace\tranborgl\TWIN360Agile\Branches\Development\MainFuture\Twin360BackEnd\src'
No sonar.oe.binaries property, defaults to source directories
No sonar.oe.dotpct property, defaults to <binaries>/.pct directories
Using PROPATH : src
Adding D:\Workspace\tranborgl\TWIN360Agile\Branches\Development\MainFuture\Twin360BackEnd\src to PROPATH
CPD annotation : 'Generated'
CPD skip method : ''
CPD skip procedure : ''
Using backslash as escape character : false
XML XREF filter activated
Parsing [uri=file:/D:/Workspace/tranborgl/TWIN360Agile/Branches/Development/MainFuture/Twin360BackEnd/src/ReportCreation/jx_AccBatch.p]
Parsing hierarchy of '[uri=file:/D:/Workspace/tranborgl/TWIN360Agile/Branches/Development/MainFuture/Twin360BackEnd/src/ReportCreation/jx_AccBatch.p]' - Relative 'ReportCreation\jx_AccBatch.p'
  RCode found: 'D:\Workspace\tranborgl\TWIN360Agile\Branches\Development\MainFuture\Twin360BackEnd\src\ReportCreation\jx_AccBatch.r'
Parsing rcode D:\Workspace\tranborgl\TWIN360Agile\Branches\Development\MainFuture\Twin360BackEnd\src\ReportCreation\jx_AccBatch.r
Listing file for '[uri=file:/D:/Workspace/tranborgl/TWIN360Agile/Branches/Development/MainFuture/Twin360BackEnd/src/ReportCreation/jx_AccBatch.p]' not found or contains space character - Was looking for 'null'
Syntax error -- src/ReportCreation/jx_AccBatch.p:29:32 -- no viable alternative at input 'AreportB'
Error during code parsing for [uri=file:/D:/Workspace/tranborgl/TWIN360Agile/Branches/Development/MainFuture/Twin360BackEnd/src/ReportCreation/jx_AccBatch.p] at position src/ReportCreation/jx_AccBatch.p:29:32
Initializing metadata of file file:/D:/Workspace/tranborgl/TWIN360Agile/Branches/Development/MainFuture/Twin360BackEnd/src/ReportCreation/jx_AccBatch.p
1 files proparse'd, 0 XREF files, 0 listing files, 1 failure(s), 0 NCLOCs
AST Generation | time=0 ms
XREF Parsing   | time=0 ms
Rules          | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.AbbreviatedTableName | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.BackslashCurlyBrace | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.BackslashInIncludeFile | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.BackslashInString | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.BlockLabel | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.ClassNoPackage | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.ColonForBlock | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.CompileTimeArguments | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.DefaultImplementationForProperty | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.DefaultWidgetName | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.DisableTriggers | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.DosKeyword | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.DotComment | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.DuplicateCase | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.EmptyFieldsList | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.EmptyStatement | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.EndType | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.ExpressionNoEffect | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.ExtraCharactersInIdentifier | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.FindFirst | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.FindNoError | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.GlobalSharedVariable | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.HiddenVariable | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.IncludeNameCasing | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.IndentationCheck | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.InvalidUseIndex | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.LogRethrowException | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.NestedComments | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.NestedDo | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.NoReturnInFinally | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.NoReturnInFuncOrMethod | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.NoUndo | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.NoWait | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.OfLink | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.OneStatementPerLine | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.OutdatedDigest | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.PublicVariable | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.ReadkeyKeyword | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.RecidKeyword | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.RedundantCatch | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.ReturnError | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.SerializableError | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.ShareLock | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.SharedVariable | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.SortAccessAnalyzer | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.SortAccessWholeIndexAnalyzer | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.StatementOrder | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.SubstituteLongChar | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.SubstituteParameters | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.TableScanAndWhere | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.TempTableSortAccessWholeIndexAnalyzer | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.TempTableWholeIndexAnalyzer | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.ToDoTracker | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.TooManyParameters | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.UndefinedNamedInclude | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.UndoWithoutOption | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.UnixKeyword | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.UnquotedParameterOsCommand | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.UnusedBuffer | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.UnusedParameter | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.UnusedVariable | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.UsingStars | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.VariableAssignedButNotRead | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.VariableOverflow | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.VariableReadButNotAssigned | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.WhereCanDo | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.WholeIndexAnalyzer | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.WorkTableKeyword | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.WrongAssignWhen | time=0 ms
Rule rssw-oe:org.sonar.plugins.openedge.checks.ClumsySyntax | time=0 ms
Rule rssw-oe:org.sonar.plugins.openedge.checks.LargeTransactionScope | time=0 ms
'OpenEdgeDBRulesSensor' skipped because there is no related file in current project
Execute Sensor: HTML
'XML Sensor' skipped because there is no related file in current project
'Kotlin Sensor' skipped because there is no related file in current project
'PHP sensor' skipped because there is no related file in current project
'Analyzer for "php.ini" files' skipped because there is no related file in current project
'JavaScript analysis' skipped because there is no related file in current project
'TypeScript analysis' skipped because there is no related file in current project
'Ruby Sensor' skipped because there is no related file in current project
Found 0 issue(s)
Done in 42 ms
GET 200 http://twsonar01:9000/api/developers/search_events?projects=twsonar01new&from=2022-08-01T08%3A39%3A12%2B0200 | response time=163ms
GET 200 http://twsonar01:9000/api/developers/search_events?projects=twsonar01new&from=2022-08-01T08%3A39%3A12%2B0200 | response time=141ms

**Comment by gquerret** [comment]
In SonarLint, properties can be specified in Project properties -> SonarLint -> Analyzer properties.
If you don't specify sonar.oe.databases, then SonarLint will use the schema of the databases connected to the associated AVM. If you don't want this behavior, you have to specify the sonar.oe.databases property.

Also, does `db/twin360.df` contain a table named `AreportB` ?

**Comment by Tranborg** [comment]
sonar.oe.databases=df/twin360.df in Project properties -> SonarLint -> Analyzer properties did the trick.

So in fact the sonar-project.properties is NOT used by DevStudio sonar-lint as default*). My bad. And thnx a lot for the help.

*) The nightbuild script is by default using this properties without any extra param.
    
    <macrodef name="sonar.control.scanner">
    	<attribute name="project.name" />
        <sequential>
            <exec executable="cmd" dir="${workspace.dir}/@{project.name}">
                <arg value="/c" />
                <arg value="sonar-scanner" />
            	<arg value="-Dsonar.projectVersion=1.4.118.${twin360.build.num}" />
            	
            </exec>
        </sequential>
    </macrodef>

**Comment by gquerret** [comment]
> So in fact the sonar-project.properties is NOT used by DevStudio sonar-lint as default*). My bad. And thnx a lot for the help.

Yes, sonarlint scanner tries to read configuration from the IDE (if possible, see https://github.com/Riverside-Software/sonar-openedge/wiki/SonarLint-for-Eclipse), while the "standard" sonar-scanner reads config from `sonar-project.properties`

PS: you can use backticks to flag code blocks, see https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax
