### ISSUE TITLE
Generation of compilation files

### ISSUE THREAD

**Issue by MedAmineTorjmen** [Riverside-Software/sonar-openedge#985]
Hello,
how can i generate the complication (.r) files using SonarQube . 

Best regards

**Comment by gquerret** [comment]
First, you'll need an OpenEdge license, then you can use [PCT](https://github.com/Riverside-Software/pct) to write a build script ; you can find a quick introduction [here](https://github.com/Riverside-Software/pct/wiki/QuickStart)
