### ISSUE TITLE
Clumsy syntax with function forward declaration

### ISSUE THREAD

**Issue by movedoa** [Riverside-Software/sonar-openedge#986]
Version 2.16.0

This is in an include file, not sure if that matters or not.

![grafik](https://user-images.githubusercontent.com/13309951/184880154-d3790c28-d36f-494c-a165-092a45f544ec.png)

**Comment by gquerret** [comment]
How is `{1}` expanded ?

**Comment by movedoa** [comment]
```
DEFINE VARIABLE mGeneralMenuManagerHandle AS HANDLE NO-UNDO.
FUNCTION GetMenuHandle RETURNS WIDGET-HANDLE (
   phPopupParent AS HANDLE,
   pcSystemId AS CHARACTER,
   pcSystemLevel AS CHARACTER,
   pcSystemView AS CHARACTER,
   pcUsageType AS CHARACTER,
   pcId AS CHARACTER
) IN mGeneralMenuManagerHandle.
```

**Comment by gquerret** [comment]
Confirmed. Based on the grammar, the rule is looking for `MAP TO identifier IN expression`, but the `MAP TO` part is optional. Will be fixed.

**Comment by gquerret** [comment]
Fixed in develop
