### ISSUE TITLE
Dot comment line not recognized

### ISSUE THREAD

**Issue by gquerret** [Riverside-Software/sonar-openedge#987]
On behalf of NCC

This code block triggers rule ExtraCharactersInIdentifier on line 2, while that's in fact a dot comment.
```abl
hExcel:Worksheets(1):Cells(1, 1) = "XXX".
.hExcel:Worksheets(1):Cells(1, 2) = "YYY".
hExcel:Worksheets(1):Cells(1, 3) = "ZZZ".
```

Tested with 2.16. New customer, so no idea if that's a regression or not.

**Comment by PeterJudgeZA** [comment]
Is there a rule to flag dot-comments? They are not mentioned in the current ABL reference doc.

**Comment by gquerret** [comment]
> Is there a rule to flag dot-comments?

https://sonar.riverside-software.fr/coding_rules?languages=oe&open=rssw-oe-main%3Aeu.rssw.antlr.proparse.checks.DotComment&q=dot
