### ISSUE TITLE
error java.lang.String.isBlank()Z during sonarlint processing

### ISSUE THREAD

**Issue by dominickdm** [Riverside-Software/sonar-openedge#988]
Last week, we did an upgrade of our Sonar server from 7.9.4 to 9.5. In the meantime we also did an upgrade of the plugin to 2.16.0.

Plugin version: 2.16.0 (last)
Sonarlint eclipse version: 6.2.2208 (last)

Since that moment, we are encountering the error below on some files, only in an 11.7 development environment (12.2 is able to process the same file without the error) . 

![2022-08-22 10_06_19-Window](https://user-images.githubusercontent.com/40289256/185871364-217b6af0-2e01-4199-9d69-6f2a2ad00851.png)

The sonarlint console doesn't contain an error, these are the last lines:

> Parsing rcode C:\Workspace\Glims_9_9_pro\glims-abl-sources\be\mips\glims\manual\core\Discriminators.r
Injecting type info 'Type info be.mips.glims.manual.core.Discriminators - Parent Progress.Lang.Object'
Listing file for '[uri=file:/C:/Workspace/Glims_9_9_pro/glims-abl-sources/be/mips/glims/manual/core/Discriminators.cls]' not found or contains space character - Was looking for 'null'
No TypeInfo found for TheResult
No TypeInfo found for TheResult
No TypeInfo found for TheResult
No TypeInfo found for TheResult
No TypeInfo found for TheSpecimen
No TypeInfo found for TheSpecimen
No TypeInfo found for TheResult
No TypeInfo found for TheResult
No TypeInfo found for TheResult
No TypeInfo found for TheResult
No TypeInfo found for TheResult
No TypeInfo found for TheResult
No TypeInfo found for TheResult
No TypeInfo found for TheResult
No TypeInfo found for TheResult
No TypeInfo found for TheResult
No TypeInfo found for TheResult
No TypeInfo found for TheSpecimen
No TypeInfo found for TheSpecimen
No TypeInfo found for TheResult
No TypeInfo found for TheResult
No TypeInfo found for TheResult
No TypeInfo found for TheSpecimen
2282 milliseconds to generate ParseUnit
ActiveRule - Internal key  - Repository rssw-oe-main - Rule eu.rssw.antlr.proparse.checks.EndType
ActiveRule - Internal key  - Repository rssw-oe-main - Rule eu.rssw.antlr.proparse.checks.BackslashInIncludeFile
ActiveRule - Internal key  - Repository rssw-oe-main - Rule eu.rssw.antlr.proparse.checks.NestedComments
ActiveRule - Internal key  - Repository rssw-oe-main - Rule eu.rssw.antlr.proparse.checks.AvoidFortranOperators
ActiveRule - Internal key  - Repository rssw-oe-main - Rule eu.rssw.antlr.proparse.checks.UndoWithoutOption
ActiveRule - Internal key  - Repository rssw-oe-main - Rule eu.rssw.antlr.proparse.checks.EmptyStatement
ActiveRule - Internal key  - Repository rssw-oe-main - Rule eu.rssw.antlr.proparse.checks.CommentedOutCode
ActiveRule - Internal key  - Repository rssw-oe-main - Rule eu.rssw.antlr.proparse.checks.NestedDo
ActiveRule - Internal key  - Repository rssw-oe-main - Rule eu.rssw.antlr.proparse.checks.DefaultImplementationForProperty
ActiveRule - Internal key  - Repository rssw-oe-main - Rule eu.rssw.antlr.proparse.checks.ColonForBlock
ActiveRule - Internal key  - Repository rssw-oe-main - Rule eu.rssw.antlr.proparse.checks.UnusedVariable
Initializing metadata of file file:/C:/Workspace/Glims_9_9_pro/glims-abl-sources/be/mips/glims/manual/core/Discriminators.cls
ActiveRule - Internal key  - Repository rssw-oe-main - Rule eu.rssw.antlr.proparse.checks.UsingStars
ActiveRule - Internal key  - Repository rssw-oe-main - Rule eu.rssw.antlr.proparse.checks.StatementOrder
ActiveRule - Internal key  - Repository rssw-oe-main - Rule eu.rssw.antlr.proparse.checks.BlockLabel
ActiveRule - Internal key  - Repository rssw-oe-main - Rule eu.rssw.antlr.proparse.checks.I18NLength
ActiveRule - Internal key  - Repository rssw-oe-main - Rule eu.rssw.antlr.proparse.checks.HiddenVariable
ActiveRule - Internal key  - Repository rssw-oe-main - Rule eu.rssw.antlr.proparse.checks.EmptyFieldsList
ActiveRule - Internal key  - Repository rssw-oe-main - Rule eu.rssw.antlr.proparse.checks.SerializableError
ActiveRule - Internal key  - Repository rssw-oe-main - Rule eu.rssw.antlr.proparse.checks.NoReturnInFuncOrMethod
ActiveRule - Internal key  - Repository rssw-oe-main - Rule eu.rssw.antlr.proparse.checks.CompileTimeArguments
ActiveRule - Internal key  - Repository rssw-oe-main - Rule eu.rssw.antlr.proparse.checks.UnusedBuffer
ActiveRule - Internal key  - Repository rssw-oe-main - Rule eu.rssw.antlr.proparse.checks.AbbreviatedTableName
ActiveRule - Internal key  - Repository rssw-oe-main - Rule eu.rssw.antlr.proparse.checks.DuplicateCase
ActiveRule - Internal key  - Repository rssw-oe-main - Rule eu.rssw.antlr.proparse.checks.StringAttribute
ActiveRule - Internal key  - Repository rssw-oe-main - Rule eu.rssw.antlr.proparse.checks.IncludeNameCasing
ActiveRule - Internal key  - Repository rssw-oe - Rule org.sonar.plugins.openedge.checks.ClumsySyntax
ActiveRule - Internal key  - Repository rssw-oe-main - Rule eu.rssw.antlr.proparse.checks.NoRoutineInWhere
ActiveRule - Internal key  - Repository rssw-oe-main - Rule Deprecated_gp_calld
ActiveRule - Internal key  - Repository rssw-oe-main - Rule eu.rssw.antlr.proparse.checks.WhereCanDo
ActiveRule - Internal key  - Repository rssw-oe-main - Rule eu.rssw.antlr.proparse.checks.PublicVariable
ActiveRule - Internal key  - Repository rssw-oe-main - Rule eu.rssw.antlr.proparse.checks.ClassNoPackage
ActiveRule - Internal key  - Repository rssw-oe-main - Rule eu.rssw.antlr.proparse.checks.WrongAssignWhen
ActiveRule - Internal key  - Repository rssw-oe-main - Rule eu.rssw.antlr.proparse.checks.ShareLock
ActiveRule - Internal key  - Repository rssw-oe-main - Rule eu.rssw.antlr.proparse.checks.RedundantCatch
ActiveRule - Internal key  - Repository rssw-oe-main - Rule eu.rssw.antlr.proparse.checks.DotComment
ActiveRule - Internal key  - Repository rssw-oe-main - Rule eu.rssw.antlr.proparse.checks.LongStrings
ActiveRule - Internal key  - Repository rssw-oe-main - Rule SESSION_CHARSET_obsolete
ActiveRule - Internal key  - Repository rssw-oe-main - Rule eu.rssw.antlr.proparse.checks.DisableTriggers
ActiveRule - Internal key  - Repository rssw-oe-main - Rule eu.rssw.antlr.proparse.checks.SubstituteLongChar
ActiveRule - Internal key  - Repository rssw-oe-main - Rule eu.rssw.antlr.proparse.checks.BufferUsageInWhereClause
ActiveRule - Internal key  - Repository rssw-oe-main - Rule eu.rssw.antlr.proparse.checks.ClassNameCasing
No TypeInfo found for be.mips.glims.manual.objects.resultwrapper
No TypeInfo found for be.mips.glims.manual.objects.specimenwrapper
No TypeInfo found for be.mips.glims.manual.objects.specimenwrapper
No TypeInfo found for be.mips.glims.manual.objects.resultwrapper
No TypeInfo found for be.mips.glims.manual.objects.resultwrapper
No TypeInfo found for be.mips.glims.manual.objects.resultwrapper
No TypeInfo found for be.mips.glims.manual.objects.resultwrapper
No TypeInfo found for be.mips.glims.manual.objects.specimenwrapper
ActiveRule - Internal key  - Repository rssw-oe-main - Rule eu.rssw.antlr.proparse.checks.NoUndo
ActiveRule - Internal key  - Repository rssw-oe-main - Rule eu.rssw.antlr.proparse.checks.NoReturnInFinally
ActiveRule - Internal key  - Repository rssw-oe-main - Rule eu.rssw.antlr.proparse.checks.BufferUsage
ActiveRule - Internal key  - Repository rssw-oe-main - Rule eu.rssw.antlr.proparse.checks.VariableOverflow

Thanks for any help on debugging this issue

**Comment by gquerret** [comment]
Yes, this issue has been spotted with SonarLint 11.7,  a hotfix branch is already available here:
https://ci.rssw.eu/job/sonar-openedge/job/hotfix%252FV2.16.1/

It is safe to install this version in your environment, as it's only 2.16.0 + this fix. 
The final 2.16.1 version will be released this week (I was waiting for feedback about another issue, but it doesn't seem to be related with 2.16, that will be confirmed soon).

**Comment by dominickdm** [comment]
Installing the new plugin version on the sonar server fixed the error.

As always, thank you for the quick feedback @gquerret.
